// Code generated by "stringer -type=PageName -output=pagename_string_gen.go"; DO NOT EDIT.

package modes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Create-0]
	_ = x[Review-1]
	_ = x[Test-2]
	_ = x[Help-3]
	_ = x[Settings-4]
}

const _PageName_name = "CreateReviewTestHelpSettings"

var _PageName_index = [...]uint8{0, 6, 12, 16, 20, 28}

func (i PageName) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PageName_index)-1 {
		return "PageName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageName_name[_PageName_index[idx]:_PageName_index[idx+1]]
}
