// Code generated by gojsonstruct; DO NOT EDIT.

package questions

type Questions []Question

//go:tag mkunion:"Question"
type (
	MultipleChoiceEngtoLatQuestion struct {
		Answer  string   `json:"answer"`
		Choices []string `json:"choices"`
		Prompt  string   `json:"prompt"`
	}
	MultipleChoiceLatToEngQuestion struct {
		Answer  string   `json:"answer"`
		Choices []string `json:"choices"`
		Prompt  string   `json:"prompt"`
	}
	ParseWordComptoLatQuestion struct {
		Answers    []string `json:"answers"`
		Components string   `json:"components"`
		MainAnswer string   `json:"main_answer"`
		Prompt     string   `json:"prompt"`
	}
	ParseWordLattoCompQuestion struct {
		Answers         []string `json:"answers"`
		DictionaryEntry string   `json:"dictionary_entry"`
		MainAnswer      string   `json:"main_answer"`
		Prompt          string   `json:"prompt"`
	}
	PrincipalPartsQuestion struct {
		PrincipalParts []string `json:"principal_parts"`
		Prompt         string   `json:"prompt"`
	}
	TypeInEngtoLatQuestion struct {
		Answers    []string `json:"answers"`
		MainAnswer string   `json:"main_answer"`
		Prompt     string   `json:"prompt"`
	}
	TypeInLattoEngQuestion struct {
		Answers    []string `json:"answers"`
		MainAnswer string   `json:"main_answer"`
		Prompt     string   `json:"prompt"`
	}
)
