// Code generated by mkunion. DO NOT EDIT.
package questions

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(MultipleChoiceEngtoLatQuestionShape())
	shape.Register(MultipleChoiceLatToEngQuestionShape())
	shape.Register(ParseWordComptoLatQuestionShape())
	shape.Register(ParseWordLattoCompQuestionShape())
	shape.Register(PrincipalPartsQuestionShape())
	shape.Register(QuestionShape())
	shape.Register(QuestionsShape())
	shape.Register(TypeInEngtoLatQuestionShape())
	shape.Register(TypeInLattoEngQuestionShape())
}

//shape:shape

func QuestionShape() shape.Shape {
	return &shape.UnionLike{
		Name: "Question",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Variant: []shape.Shape{
			MultipleChoiceEngtoLatQuestionShape(),
			MultipleChoiceLatToEngQuestionShape(),
			ParseWordComptoLatQuestionShape(),
			ParseWordLattoCompQuestionShape(),
			PrincipalPartsQuestionShape(),
			TypeInEngtoLatQuestionShape(),
			TypeInLattoEngQuestionShape(),
		},
	}
}

func MultipleChoiceEngtoLatQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "MultipleChoiceEngtoLatQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "Answer",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "answer",
					},
				},
			},
			{
				Name: "Choices",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "choices",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}

func MultipleChoiceLatToEngQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "MultipleChoiceLatToEngQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "Answer",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "answer",
					},
				},
			},
			{
				Name: "Choices",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "choices",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}

func ParseWordComptoLatQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "ParseWordComptoLatQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "Answers",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "answers",
					},
				},
			},
			{
				Name: "Components",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "components",
					},
				},
			},
			{
				Name: "MainAnswer",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "main_answer",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}

func ParseWordLattoCompQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "ParseWordLattoCompQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "Answers",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "answers",
					},
				},
			},
			{
				Name: "DictionaryEntry",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "dictionary_entry",
					},
				},
			},
			{
				Name: "MainAnswer",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "main_answer",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}

func PrincipalPartsQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "PrincipalPartsQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "PrincipalParts",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "principal_parts",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}

func TypeInEngtoLatQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "TypeInEngtoLatQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "Answers",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "answers",
					},
				},
			},
			{
				Name: "MainAnswer",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "main_answer",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}

func TypeInLattoEngQuestionShape() shape.Shape {
	return &shape.StructLike{
		Name: "TypeInLattoEngQuestion",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Fields: []*shape.FieldLike{
			{
				Name: "Answers",
				Type: &shape.ListLike{
					Element: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "answers",
					},
				},
			},
			{
				Name: "MainAnswer",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "main_answer",
					},
				},
			},
			{
				Name: "Prompt",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "prompt",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Question",
			},
		},
	}
}
//shape:shape
func QuestionsShape() shape.Shape {
	return &shape.AliasLike{
		Name: "Questions",
		PkgName: "questions",
		PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
		Type: &shape.ListLike{
			Element: &shape.RefName{
				Name: "Question",
				PkgName: "questions",
				PkgImportName: "github.com/rduo1009/vocab-tuister/src/client/pkg/questions",
			},
		},
	}
}
