// Code generated by mkunion. DO NOT EDIT.
package questions

import (
	"github.com/widmogrod/mkunion/x/shared"
)

func init() {
	shared.TypeRegistryStore[MultipleChoiceEngtoLatQuestion]("MultipleChoiceEngtoLatQuestion")
	shared.TypeRegistryStore[MultipleChoiceLatToEngQuestion]("MultipleChoiceLatToEngQuestion")
	shared.TypeRegistryStore[ParseWordComptoLatQuestion]("ParseWordComptoLatQuestion")
	shared.TypeRegistryStore[ParseWordLattoCompQuestion]("ParseWordLattoCompQuestion")
	shared.TypeRegistryStore[PrincipalPartsQuestion]("PrincipalPartsQuestion")
	shared.TypeRegistryStore[TypeInEngtoLatQuestion]("TypeInEngtoLatQuestion")
	shared.TypeRegistryStore[TypeInLattoEngQuestion]("TypeInLattoEngQuestion")
}
