// Code generated by mkunion. DO NOT EDIT.
package questions

import (
	"github.com/widmogrod/mkunion/x/shared"
)

func init() {
	shared.TypeRegistryStore[MultipleChoiceEngToLatQuestion]("MultipleChoiceEngToLatQuestion")
	shared.TypeRegistryStore[MultipleChoiceLatToEngQuestion]("MultipleChoiceLatToEngQuestion")
	shared.TypeRegistryStore[ParseWordCompToLatQuestion]("ParseWordCompToLatQuestion")
	shared.TypeRegistryStore[ParseWordLatToCompQuestion]("ParseWordLatToCompQuestion")
	shared.TypeRegistryStore[PrincipalPartsQuestion]("PrincipalPartsQuestion")
	shared.TypeRegistryStore[TypeInEngToLatQuestion]("TypeInEngToLatQuestion")
	shared.TypeRegistryStore[TypeInLatToEngQuestion]("TypeInLatToEngQuestion")
}
