version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🚧 build(deps):"
    ignore:
      - dependency-name: "wn"
    cooldown:
      default-days: 7

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🚧 build(deps):"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🤖 ci(github-actions):"
    cooldown:
      default-days: 7

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🤖 ci(devcontainer):"
    cooldown:
      default-days: 7
