version: "2"

linters:
  default: none

  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errname
    - goconst
    - gocritic
    - godot
    - godox
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - tagalign
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - src/_vendor
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/rduo1009/vocab-tuister)
      custom-order: true
    gofumpt:
      extra-rules: true

  exclusions:
    generated: lax
    paths:
      - src/_vendor
      - third_party$
      - builtin$
      - examples$
