version: "2"

linters:
  default: none

  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errname
    - exhaustive
    - funcorder
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - modernize
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - rowserrcheck
    - staticcheck
    - tagalign
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wsl_v5

  settings:
    wsl_v5:
      branch-max-lines: 5
      case-max-lines: 1
      allow-whole-block: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - src/_vendor
      - src/client/internal/components/vocabeditor # TODO: Remove this
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/rduo1009/vocab-tuister)
      custom-order: true

    gofumpt:
      extra-rules: true

    golines:
      max-len: 120
      tab-len: 8

  exclusions:
    generated: lax
    paths:
      - src/_vendor
      - third_party$
      - builtin$
      - examples$
