[tool.poe.tasks.coverage]
shell = "./scripts/coverage.sh"
help = "Run coverage on the project."

[tool.poe.tasks.build]
cmd = "./scripts/build.sh"
help = "Build the project."
args = [
    { name = "debug", default = false, type = "boolean", help = "Build the project into a folder instead of a single file." },
]

[tool.poe.tasks.test]
cmd = "tox --parallel"
help = "Run tests on the project."

[tool.poe.tasks.badges]
cmd = "./scripts/badges.sh"
help = "Generate badges for the project."
