[tool.poe]
tasks.build.cmd = "./scripts/build.sh"
tasks.build.help = "Build the project."
tasks.test.cmd = "./scripts/tests.sh"
tasks.test.help = "Run the unit test suite."
tasks.generate.cmd = "./scripts/generate.sh"
tasks.generate.help = "Generate code."
