# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: vocab_tuister/v1/endingcomponents.proto, vocab_tuister/v1/question.proto, vocab_tuister/v1/sessionconfig.proto, vocab_tuister/v1/vocab_service.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Case",
    "CreateSessionRequest",
    "CreateSessionResponse",
    "Degree",
    "EndingComponents",
    "Gender",
    "Mood",
    "MultipleChoiceEngToLatQuestion",
    "MultipleChoiceLatToEngQuestion",
    "Number",
    "ParseWordCompToLatQuestion",
    "ParseWordLatToCompQuestion",
    "Person",
    "PrincipalPartsQuestion",
    "Question",
    "SessionConfig",
    "Tense",
    "TypeInEngToLatQuestion",
    "TypeInLatToEngQuestion",
    "VerifyConfigRequest",
    "VerifyConfigResponse",
    "VerifyVocabRequest",
    "VerifyVocabResponse",
    "VocabTesterServiceBase",
    "VocabTesterServiceStub",
    "Voice",
)

import typing
from collections.abc import AsyncIterator, Iterator
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
import pydantic
from betterproto2 import grpclib as betterproto2_grpclib
from pydantic import model_validator
from pydantic.dataclasses import dataclass

from ...message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class Case(betterproto2.Enum):
    UNSPECIFIED = 0

    NOMINATIVE = 1

    VOCATIVE = 2

    ACCUSATIVE = 3

    GENITIVE = 4

    DATIVE = 5

    ABLATIVE = 6

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CASE_UNSPECIFIED",
            1: "CASE_NOMINATIVE",
            2: "CASE_VOCATIVE",
            3: "CASE_ACCUSATIVE",
            4: "CASE_GENITIVE",
            5: "CASE_DATIVE",
            6: "CASE_ABLATIVE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CASE_UNSPECIFIED": 0,
            "CASE_NOMINATIVE": 1,
            "CASE_VOCATIVE": 2,
            "CASE_ACCUSATIVE": 3,
            "CASE_GENITIVE": 4,
            "CASE_DATIVE": 5,
            "CASE_ABLATIVE": 6,
        }


class Degree(betterproto2.Enum):
    UNSPECIFIED = 0

    POSITIVE = 1

    COMPARATIVE = 2

    SUPERLATIVE = 3

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "DEGREE_UNSPECIFIED",
            1: "DEGREE_POSITIVE",
            2: "DEGREE_COMPARATIVE",
            3: "DEGREE_SUPERLATIVE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "DEGREE_UNSPECIFIED": 0,
            "DEGREE_POSITIVE": 1,
            "DEGREE_COMPARATIVE": 2,
            "DEGREE_SUPERLATIVE": 3,
        }


class Gender(betterproto2.Enum):
    UNSPECIFIED = 0

    MASCULINE = 1

    FEMININE = 2

    NEUTER = 3

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "GENDER_UNSPECIFIED",
            1: "GENDER_MASCULINE",
            2: "GENDER_FEMININE",
            3: "GENDER_NEUTER",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "GENDER_UNSPECIFIED": 0,
            "GENDER_MASCULINE": 1,
            "GENDER_FEMININE": 2,
            "GENDER_NEUTER": 3,
        }


class Mood(betterproto2.Enum):
    UNSPECIFIED = 0

    INDICATIVE = 1

    SUBJUNCTIVE = 2

    IMPERATIVE = 3

    INFINITIVE = 4

    PARTICIPLE = 5

    GERUND = 6

    SUPINE = 7

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "MOOD_UNSPECIFIED",
            1: "MOOD_INDICATIVE",
            2: "MOOD_SUBJUNCTIVE",
            3: "MOOD_IMPERATIVE",
            4: "MOOD_INFINITIVE",
            5: "MOOD_PARTICIPLE",
            6: "MOOD_GERUND",
            7: "MOOD_SUPINE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "MOOD_UNSPECIFIED": 0,
            "MOOD_INDICATIVE": 1,
            "MOOD_SUBJUNCTIVE": 2,
            "MOOD_IMPERATIVE": 3,
            "MOOD_INFINITIVE": 4,
            "MOOD_PARTICIPLE": 5,
            "MOOD_GERUND": 6,
            "MOOD_SUPINE": 7,
        }


class Number(betterproto2.Enum):
    UNSPECIFIED = 0

    SINGULAR = 1

    PLURAL = 2

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "NUMBER_UNSPECIFIED",
            1: "NUMBER_SINGULAR",
            2: "NUMBER_PLURAL",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "NUMBER_UNSPECIFIED": 0,
            "NUMBER_SINGULAR": 1,
            "NUMBER_PLURAL": 2,
        }


class Person(betterproto2.Enum):
    UNSPECIFIED = 0

    FIRST = 1

    SECOND = 2

    THIRD = 3

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "PERSON_UNSPECIFIED",
            1: "PERSON_FIRST",
            2: "PERSON_SECOND",
            3: "PERSON_THIRD",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "PERSON_UNSPECIFIED": 0,
            "PERSON_FIRST": 1,
            "PERSON_SECOND": 2,
            "PERSON_THIRD": 3,
        }


class Tense(betterproto2.Enum):
    UNSPECIFIED = 0

    PRESENT = 1

    IMPERFECT = 2

    FUTURE = 3

    PERFECT = 4

    PLUPERFECT = 5

    FUTURE_PERFECT = 6

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "TENSE_UNSPECIFIED",
            1: "TENSE_PRESENT",
            2: "TENSE_IMPERFECT",
            3: "TENSE_FUTURE",
            4: "TENSE_PERFECT",
            5: "TENSE_PLUPERFECT",
            6: "TENSE_FUTURE_PERFECT",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "TENSE_UNSPECIFIED": 0,
            "TENSE_PRESENT": 1,
            "TENSE_IMPERFECT": 2,
            "TENSE_FUTURE": 3,
            "TENSE_PERFECT": 4,
            "TENSE_PLUPERFECT": 5,
            "TENSE_FUTURE_PERFECT": 6,
        }


class Voice(betterproto2.Enum):
    UNSPECIFIED = 0

    ACTIVE = 1

    PASSIVE = 2

    DEPONENT = 3

    SEMI_DEPONENT = 4

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "VOICE_UNSPECIFIED",
            1: "VOICE_ACTIVE",
            2: "VOICE_PASSIVE",
            3: "VOICE_DEPONENT",
            4: "VOICE_SEMI_DEPONENT",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "VOICE_UNSPECIFIED": 0,
            "VOICE_ACTIVE": 1,
            "VOICE_PASSIVE": 2,
            "VOICE_DEPONENT": 3,
            "VOICE_SEMI_DEPONENT": 4,
        }


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CreateSessionRequest(betterproto2.Message):
    vocab_list: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    number_of_questions: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_INT32
    )

    session_config: "SessionConfig | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "CreateSessionRequest", CreateSessionRequest
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CreateSessionResponse(betterproto2.Message):
    question: "Question | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "CreateSessionResponse", CreateSessionResponse
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class EndingComponents(betterproto2.Message):
    case: "Case" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: Case(0)
    )

    number: "Number" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: Number(0)
    )

    gender: "Gender" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: Gender(0)
    )

    tense: "Tense" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, default_factory=lambda: Tense(0)
    )

    voice: "Voice" = betterproto2.field(
        5, betterproto2.TYPE_ENUM, default_factory=lambda: Voice(0)
    )

    mood: "Mood" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: Mood(0)
    )

    person: "Person" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: Person(0)
    )

    degree: "Degree" = betterproto2.field(
        8, betterproto2.TYPE_ENUM, default_factory=lambda: Degree(0)
    )

    display_string: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "EndingComponents", EndingComponents
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MultipleChoiceEngToLatQuestion(betterproto2.Message):
    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    answer: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    choices: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        3, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "vocab_tuister.v1",
    "MultipleChoiceEngToLatQuestion",
    MultipleChoiceEngToLatQuestion,
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MultipleChoiceLatToEngQuestion(betterproto2.Message):
    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    answer: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    choices: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        3, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "vocab_tuister.v1",
    "MultipleChoiceLatToEngQuestion",
    MultipleChoiceLatToEngQuestion,
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ParseWordCompToLatQuestion(betterproto2.Message):
    answers: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )

    components: "EndingComponents | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    main_answer: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1",
    "ParseWordCompToLatQuestion",
    ParseWordCompToLatQuestion,
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ParseWordLatToCompQuestion(betterproto2.Message):
    answers: "list[EndingComponents]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    dictionary_entry: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    main_answer: "EndingComponents | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1",
    "ParseWordLatToCompQuestion",
    ParseWordLatToCompQuestion,
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class PrincipalPartsQuestion(betterproto2.Message):
    principal_parts: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )

    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "PrincipalPartsQuestion", PrincipalPartsQuestion
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Question(betterproto2.Message):
    """


    Oneofs:
        - kind:
    """

    mc_eng_to_lat: "MultipleChoiceEngToLatQuestion | None" = (
        betterproto2.field(
            1, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
        )
    )

    mc_lat_to_eng: "MultipleChoiceLatToEngQuestion | None" = (
        betterproto2.field(
            2, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
        )
    )

    parse_comp_to_lat: "ParseWordCompToLatQuestion | None" = (
        betterproto2.field(
            3, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
        )
    )

    parse_lat_to_comp: "ParseWordLatToCompQuestion | None" = (
        betterproto2.field(
            4, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
        )
    )

    principal_parts: "PrincipalPartsQuestion | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
    )

    type_in_eng_to_lat: "TypeInEngToLatQuestion | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
    )

    type_in_lat_to_eng: "TypeInLatToEngQuestion | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("vocab_tuister.v1", "Question", Question)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SessionConfig(betterproto2.Message):
    exclude_adjectives: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    exclude_adjective_212_declension: "bool" = betterproto2.field(
        2, betterproto2.TYPE_BOOL
    )

    exclude_adjective_third_declension: "bool" = betterproto2.field(
        3, betterproto2.TYPE_BOOL
    )

    exclude_adjective_masculine: "bool" = betterproto2.field(
        4, betterproto2.TYPE_BOOL
    )

    exclude_adjective_feminine: "bool" = betterproto2.field(
        5, betterproto2.TYPE_BOOL
    )

    exclude_adjective_neuter: "bool" = betterproto2.field(
        6, betterproto2.TYPE_BOOL
    )

    exclude_adjective_nominative: "bool" = betterproto2.field(
        7, betterproto2.TYPE_BOOL
    )

    exclude_adjective_vocative: "bool" = betterproto2.field(
        8, betterproto2.TYPE_BOOL
    )

    exclude_adjective_accusative: "bool" = betterproto2.field(
        9, betterproto2.TYPE_BOOL
    )

    exclude_adjective_genitive: "bool" = betterproto2.field(
        10, betterproto2.TYPE_BOOL
    )

    exclude_adjective_dative: "bool" = betterproto2.field(
        11, betterproto2.TYPE_BOOL
    )

    exclude_adjective_ablative: "bool" = betterproto2.field(
        12, betterproto2.TYPE_BOOL
    )

    exclude_adjective_singular: "bool" = betterproto2.field(
        13, betterproto2.TYPE_BOOL
    )

    exclude_adjective_plural: "bool" = betterproto2.field(
        14, betterproto2.TYPE_BOOL
    )

    exclude_adjective_positive: "bool" = betterproto2.field(
        15, betterproto2.TYPE_BOOL
    )

    exclude_adjective_comparative: "bool" = betterproto2.field(
        16, betterproto2.TYPE_BOOL
    )

    exclude_adjective_superlative: "bool" = betterproto2.field(
        17, betterproto2.TYPE_BOOL
    )

    exclude_adverbs: "bool" = betterproto2.field(18, betterproto2.TYPE_BOOL)

    exclude_adverb_positive: "bool" = betterproto2.field(
        19, betterproto2.TYPE_BOOL
    )

    exclude_adverb_comparative: "bool" = betterproto2.field(
        20, betterproto2.TYPE_BOOL
    )

    exclude_adverb_superlative: "bool" = betterproto2.field(
        21, betterproto2.TYPE_BOOL
    )

    exclude_nouns: "bool" = betterproto2.field(22, betterproto2.TYPE_BOOL)

    exclude_noun_first_declension: "bool" = betterproto2.field(
        23, betterproto2.TYPE_BOOL
    )

    exclude_noun_second_declension: "bool" = betterproto2.field(
        24, betterproto2.TYPE_BOOL
    )

    exclude_noun_third_declension: "bool" = betterproto2.field(
        25, betterproto2.TYPE_BOOL
    )

    exclude_noun_fourth_declension: "bool" = betterproto2.field(
        26, betterproto2.TYPE_BOOL
    )

    exclude_noun_fifth_declension: "bool" = betterproto2.field(
        27, betterproto2.TYPE_BOOL
    )

    exclude_noun_irregular_declension: "bool" = betterproto2.field(
        28, betterproto2.TYPE_BOOL
    )

    exclude_noun_nominative: "bool" = betterproto2.field(
        29, betterproto2.TYPE_BOOL
    )

    exclude_noun_vocative: "bool" = betterproto2.field(
        30, betterproto2.TYPE_BOOL
    )

    exclude_noun_accusative: "bool" = betterproto2.field(
        31, betterproto2.TYPE_BOOL
    )

    exclude_noun_genitive: "bool" = betterproto2.field(
        32, betterproto2.TYPE_BOOL
    )

    exclude_noun_dative: "bool" = betterproto2.field(
        33, betterproto2.TYPE_BOOL
    )

    exclude_noun_ablative: "bool" = betterproto2.field(
        34, betterproto2.TYPE_BOOL
    )

    exclude_noun_singular: "bool" = betterproto2.field(
        35, betterproto2.TYPE_BOOL
    )

    exclude_noun_plural: "bool" = betterproto2.field(
        36, betterproto2.TYPE_BOOL
    )

    exclude_pronouns: "bool" = betterproto2.field(37, betterproto2.TYPE_BOOL)

    exclude_pronoun_masculine: "bool" = betterproto2.field(
        38, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_feminine: "bool" = betterproto2.field(
        39, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_neuter: "bool" = betterproto2.field(
        40, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_nominative: "bool" = betterproto2.field(
        41, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_vocative: "bool" = betterproto2.field(
        42, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_accusative: "bool" = betterproto2.field(
        43, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_genitive: "bool" = betterproto2.field(
        44, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_dative: "bool" = betterproto2.field(
        45, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_ablative: "bool" = betterproto2.field(
        46, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_singular: "bool" = betterproto2.field(
        47, betterproto2.TYPE_BOOL
    )

    exclude_pronoun_plural: "bool" = betterproto2.field(
        48, betterproto2.TYPE_BOOL
    )

    exclude_regulars: "bool" = betterproto2.field(49, betterproto2.TYPE_BOOL)

    exclude_verbs: "bool" = betterproto2.field(50, betterproto2.TYPE_BOOL)

    exclude_deponents: "bool" = betterproto2.field(51, betterproto2.TYPE_BOOL)

    exclude_semi_deponents: "bool" = betterproto2.field(
        52, betterproto2.TYPE_BOOL
    )

    exclude_verb_first_conjugation: "bool" = betterproto2.field(
        53, betterproto2.TYPE_BOOL
    )

    exclude_verb_second_conjugation: "bool" = betterproto2.field(
        54, betterproto2.TYPE_BOOL
    )

    exclude_verb_third_conjugation: "bool" = betterproto2.field(
        55, betterproto2.TYPE_BOOL
    )

    exclude_verb_fourth_conjugation: "bool" = betterproto2.field(
        56, betterproto2.TYPE_BOOL
    )

    exclude_verb_mixed_conjugation: "bool" = betterproto2.field(
        57, betterproto2.TYPE_BOOL
    )

    exclude_verb_irregular_conjugation: "bool" = betterproto2.field(
        58, betterproto2.TYPE_BOOL
    )

    exclude_verb_present_active_indicative: "bool" = betterproto2.field(
        59, betterproto2.TYPE_BOOL
    )

    exclude_verb_imperfect_active_indicative: "bool" = betterproto2.field(
        60, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_active_indicative: "bool" = betterproto2.field(
        61, betterproto2.TYPE_BOOL
    )

    exclude_verb_perfect_active_indicative: "bool" = betterproto2.field(
        62, betterproto2.TYPE_BOOL
    )

    exclude_verb_pluperfect_active_indicative: "bool" = betterproto2.field(
        63, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_perfect_active_indicative: "bool" = betterproto2.field(
        64, betterproto2.TYPE_BOOL
    )

    exclude_verb_present_passive_indicative: "bool" = betterproto2.field(
        65, betterproto2.TYPE_BOOL
    )

    exclude_verb_imperfect_passive_indicative: "bool" = betterproto2.field(
        66, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_passive_indicative: "bool" = betterproto2.field(
        67, betterproto2.TYPE_BOOL
    )

    exclude_verb_perfect_passive_indicative: "bool" = betterproto2.field(
        68, betterproto2.TYPE_BOOL
    )

    exclude_verb_pluperfect_passive_indicative: "bool" = betterproto2.field(
        69, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_perfect_passive_indicative: "bool" = (
        betterproto2.field(70, betterproto2.TYPE_BOOL)
    )

    exclude_verb_present_active_subjunctive: "bool" = betterproto2.field(
        71, betterproto2.TYPE_BOOL
    )

    exclude_verb_imperfect_active_subjunctive: "bool" = betterproto2.field(
        72, betterproto2.TYPE_BOOL
    )

    exclude_verb_perfect_active_subjunctive: "bool" = betterproto2.field(
        73, betterproto2.TYPE_BOOL
    )

    exclude_verb_pluperfect_active_subjunctive: "bool" = betterproto2.field(
        74, betterproto2.TYPE_BOOL
    )

    exclude_verb_present_active_imperative: "bool" = betterproto2.field(
        75, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_active_imperative: "bool" = betterproto2.field(
        76, betterproto2.TYPE_BOOL
    )

    exclude_verb_present_passive_imperative: "bool" = betterproto2.field(
        77, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_passive_imperative: "bool" = betterproto2.field(
        78, betterproto2.TYPE_BOOL
    )

    exclude_verb_present_active_infinitive: "bool" = betterproto2.field(
        79, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_active_infinitive: "bool" = betterproto2.field(
        80, betterproto2.TYPE_BOOL
    )

    exclude_verb_perfect_active_infinitive: "bool" = betterproto2.field(
        81, betterproto2.TYPE_BOOL
    )

    exclude_verb_present_passive_infinitive: "bool" = betterproto2.field(
        82, betterproto2.TYPE_BOOL
    )

    exclude_verb_future_passive_infinitive: "bool" = betterproto2.field(
        83, betterproto2.TYPE_BOOL
    )

    exclude_verb_perfect_passive_infinitive: "bool" = betterproto2.field(
        84, betterproto2.TYPE_BOOL
    )

    exclude_verb_singular: "bool" = betterproto2.field(
        85, betterproto2.TYPE_BOOL
    )

    exclude_verb_plural: "bool" = betterproto2.field(
        86, betterproto2.TYPE_BOOL
    )

    exclude_verb_first_person: "bool" = betterproto2.field(
        87, betterproto2.TYPE_BOOL
    )

    exclude_verb_second_person: "bool" = betterproto2.field(
        88, betterproto2.TYPE_BOOL
    )

    exclude_verb_third_person: "bool" = betterproto2.field(
        89, betterproto2.TYPE_BOOL
    )

    exclude_participles: "bool" = betterproto2.field(
        90, betterproto2.TYPE_BOOL
    )

    exclude_participle_present_active: "bool" = betterproto2.field(
        91, betterproto2.TYPE_BOOL
    )

    exclude_participle_perfect_passive: "bool" = betterproto2.field(
        92, betterproto2.TYPE_BOOL
    )

    exclude_participle_future_active: "bool" = betterproto2.field(
        93, betterproto2.TYPE_BOOL
    )

    exclude_gerundives: "bool" = betterproto2.field(94, betterproto2.TYPE_BOOL)

    exclude_participle_masculine: "bool" = betterproto2.field(
        95, betterproto2.TYPE_BOOL
    )

    exclude_participle_feminine: "bool" = betterproto2.field(
        96, betterproto2.TYPE_BOOL
    )

    exclude_participle_neuter: "bool" = betterproto2.field(
        97, betterproto2.TYPE_BOOL
    )

    exclude_participle_nominative: "bool" = betterproto2.field(
        98, betterproto2.TYPE_BOOL
    )

    exclude_participle_vocative: "bool" = betterproto2.field(
        99, betterproto2.TYPE_BOOL
    )

    exclude_participle_accusative: "bool" = betterproto2.field(
        100, betterproto2.TYPE_BOOL
    )

    exclude_participle_genitive: "bool" = betterproto2.field(
        101, betterproto2.TYPE_BOOL
    )

    exclude_participle_dative: "bool" = betterproto2.field(
        102, betterproto2.TYPE_BOOL
    )

    exclude_participle_ablative: "bool" = betterproto2.field(
        103, betterproto2.TYPE_BOOL
    )

    exclude_participle_singular: "bool" = betterproto2.field(
        104, betterproto2.TYPE_BOOL
    )

    exclude_participle_plural: "bool" = betterproto2.field(
        105, betterproto2.TYPE_BOOL
    )

    exclude_gerunds: "bool" = betterproto2.field(106, betterproto2.TYPE_BOOL)

    exclude_supines: "bool" = betterproto2.field(107, betterproto2.TYPE_BOOL)

    english_subjunctives: "bool" = betterproto2.field(
        108, betterproto2.TYPE_BOOL
    )

    english_verbal_nouns: "bool" = betterproto2.field(
        109, betterproto2.TYPE_BOOL
    )

    include_typein_engtolat: "bool" = betterproto2.field(
        110, betterproto2.TYPE_BOOL
    )

    include_typein_lattoeng: "bool" = betterproto2.field(
        111, betterproto2.TYPE_BOOL
    )

    include_parse: "bool" = betterproto2.field(112, betterproto2.TYPE_BOOL)

    include_inflect: "bool" = betterproto2.field(113, betterproto2.TYPE_BOOL)

    include_principal_parts: "bool" = betterproto2.field(
        114, betterproto2.TYPE_BOOL
    )

    include_multiplechoice_engtolat: "bool" = betterproto2.field(
        115, betterproto2.TYPE_BOOL
    )

    include_multiplechoice_lattoeng: "bool" = betterproto2.field(
        116, betterproto2.TYPE_BOOL
    )

    number_multiplechoice_options: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        117, betterproto2.TYPE_INT32
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "SessionConfig", SessionConfig
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TypeInEngToLatQuestion(betterproto2.Message):
    answers: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )

    main_answer: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "TypeInEngToLatQuestion", TypeInEngToLatQuestion
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TypeInLatToEngQuestion(betterproto2.Message):
    answers: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )

    main_answer: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    prompt: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "TypeInLatToEngQuestion", TypeInLatToEngQuestion
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class VerifyConfigRequest(betterproto2.Message):
    number_of_questions: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )

    session_config: "SessionConfig | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "VerifyConfigRequest", VerifyConfigRequest
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class VerifyConfigResponse(betterproto2.Message):
    pass


default_message_pool.register_message(
    "vocab_tuister.v1", "VerifyConfigResponse", VerifyConfigResponse
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class VerifyVocabRequest(betterproto2.Message):
    vocab_text: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "vocab_tuister.v1", "VerifyVocabRequest", VerifyVocabRequest
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class VerifyVocabResponse(betterproto2.Message):
    pass


default_message_pool.register_message(
    "vocab_tuister.v1", "VerifyVocabResponse", VerifyVocabResponse
)


class VocabTesterServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def verify_vocab(
        self, message: "VerifyVocabRequest"
    ) -> "VerifyVocabResponse":

        return self._channel.unary_unary(
            "/vocab_tuister.v1.VocabTesterService/VerifyVocab",
            VerifyVocabRequest.SerializeToString,
            VerifyVocabResponse.FromString,
        )(message)

    def verify_config(
        self, message: "VerifyConfigRequest"
    ) -> "VerifyConfigResponse":

        return self._channel.unary_unary(
            "/vocab_tuister.v1.VocabTesterService/VerifyConfig",
            VerifyConfigRequest.SerializeToString,
            VerifyConfigResponse.FromString,
        )(message)

    def create_session(
        self, message: "CreateSessionRequest"
    ) -> "Iterator[CreateSessionResponse]":

        yield from self._channel.unary_stream(
            "/vocab_tuister.v1.VocabTesterService/CreateSession",
            CreateSessionRequest.SerializeToString,
            CreateSessionResponse.FromString,
        )(message)


class VocabTesterServiceBase(betterproto2_grpclib.ServiceBase):
    async def verify_vocab(
        self, message: "VerifyVocabRequest"
    ) -> "VerifyVocabResponse":

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def verify_config(
        self, message: "VerifyConfigRequest"
    ) -> "VerifyConfigResponse":

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def create_session(
        self, message: "CreateSessionRequest"
    ) -> "AsyncIterator[CreateSessionResponse]":

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield CreateSessionResponse()

    async def __rpc_verify_vocab(
        self,
        stream: "grpclib.server.Stream[VerifyVocabRequest, VerifyVocabResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.verify_vocab(request)
        await stream.send_message(response)

    async def __rpc_verify_config(
        self,
        stream: "grpclib.server.Stream[VerifyConfigRequest, VerifyConfigResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.verify_config(request)
        await stream.send_message(response)

    async def __rpc_create_session(
        self,
        stream: "grpclib.server.Stream[CreateSessionRequest, CreateSessionResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.create_session, stream, request
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/vocab_tuister.v1.VocabTesterService/VerifyVocab": grpclib.const.Handler(
                self.__rpc_verify_vocab,
                grpclib.const.Cardinality.UNARY_UNARY,
                VerifyVocabRequest,
                VerifyVocabResponse,
            ),
            "/vocab_tuister.v1.VocabTesterService/VerifyConfig": grpclib.const.Handler(
                self.__rpc_verify_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                VerifyConfigRequest,
                VerifyConfigResponse,
            ),
            "/vocab_tuister.v1.VocabTesterService/CreateSession": grpclib.const.Handler(
                self.__rpc_create_session,
                grpclib.const.Cardinality.UNARY_STREAM,
                CreateSessionRequest,
                CreateSessionResponse,
            ),
        }
