# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vocab_tuister/v1/vocablist.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'vocab_tuister/v1/vocablist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n vocab_tuister/v1/vocablist.proto\x12\x10vocab_tuister.v1\"%\n\tVocabList\x12\x18\n\x07\x65ntries\x18\x01 \x03(\tR\x07\x65ntriesB=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vocab_tuister.v1.vocablist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pb'
  _globals['_VOCABLIST']._serialized_start=54
  _globals['_VOCABLIST']._serialized_end=91
# @@protoc_insertion_point(module_scope)
