# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vocab_tuister/v1/vocab_service.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'vocab_tuister/v1/vocab_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vocab_tuister.v1 import question_pb2 as vocab__tuister_dot_v1_dot_question__pb2
from vocab_tuister.v1 import sessionconfig_pb2 as vocab__tuister_dot_v1_dot_sessionconfig__pb2
from vocab_tuister.v1 import vocablist_pb2 as vocab__tuister_dot_v1_dot_vocablist__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$vocab_tuister/v1/vocab_service.proto\x12\x10vocab_tuister.v1\x1a\x1fvocab_tuister/v1/question.proto\x1a$vocab_tuister/v1/sessionconfig.proto\x1a vocab_tuister/v1/vocablist.proto\"3\n\x12VerifyVocabRequest\x12\x1d\n\nvocab_text\x18\x01 \x01(\tR\tvocabText\"J\n\x13VerifyVocabResponse\x12\x0e\n\x02ok\x18\x01 \x01(\x08R\x02ok\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage\"~\n\x13VerifyConfigRequest\x12.\n\x13number_of_questions\x18\x01 \x01(\x05R\x11numberOfQuestions\x12\x37\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1f.vocab_tuister.v1.SessionConfigR\x06\x63onfig\"K\n\x14VerifyConfigResponse\x12\x0e\n\x02ok\x18\x01 \x01(\x08R\x02ok\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage\"\xb2\x01\n\x14\x43reateSessionRequest\x12\x31\n\x05vocab\x18\x01 \x01(\x0b\x32\x1b.vocab_tuister.v1.VocabListR\x05vocab\x12.\n\x13number_of_questions\x18\x02 \x01(\x05R\x11numberOfQuestions\x12\x37\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x1f.vocab_tuister.v1.SessionConfigR\x06\x63onfig\"Q\n\x15\x43reateSessionResponse\x12\x38\n\tquestions\x18\x01 \x03(\x0b\x32\x1a.vocab_tuister.v1.QuestionR\tquestions2\xb1\x02\n\x12VocabTesterService\x12Z\n\x0bVerifyVocab\x12$.vocab_tuister.v1.VerifyVocabRequest\x1a%.vocab_tuister.v1.VerifyVocabResponse\x12]\n\x0cVerifyConfig\x12%.vocab_tuister.v1.VerifyConfigRequest\x1a&.vocab_tuister.v1.VerifyConfigResponse\x12`\n\rCreateSession\x12&.vocab_tuister.v1.CreateSessionRequest\x1a\'.vocab_tuister.v1.CreateSessionResponseB=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vocab_tuister.v1.vocab_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pb'
  _globals['_VERIFYVOCABREQUEST']._serialized_start=163
  _globals['_VERIFYVOCABREQUEST']._serialized_end=214
  _globals['_VERIFYVOCABRESPONSE']._serialized_start=216
  _globals['_VERIFYVOCABRESPONSE']._serialized_end=290
  _globals['_VERIFYCONFIGREQUEST']._serialized_start=292
  _globals['_VERIFYCONFIGREQUEST']._serialized_end=418
  _globals['_VERIFYCONFIGRESPONSE']._serialized_start=420
  _globals['_VERIFYCONFIGRESPONSE']._serialized_end=495
  _globals['_CREATESESSIONREQUEST']._serialized_start=498
  _globals['_CREATESESSIONREQUEST']._serialized_end=676
  _globals['_CREATESESSIONRESPONSE']._serialized_start=678
  _globals['_CREATESESSIONRESPONSE']._serialized_end=759
  _globals['_VOCABTESTERSERVICE']._serialized_start=762
  _globals['_VOCABTESTERSERVICE']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
