# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vocab_tuister.v1 import vocab_service_pb2 as vocab__tuister_dot_v1_dot_vocab__service__pb2


class VocabTesterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyVocab = channel.unary_unary(
                '/vocab_tuister.v1.VocabTesterService/VerifyVocab',
                request_serializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyVocabRequest.SerializeToString,
                response_deserializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyVocabResponse.FromString,
                _registered_method=True)
        self.VerifyConfig = channel.unary_unary(
                '/vocab_tuister.v1.VocabTesterService/VerifyConfig',
                request_serializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyConfigRequest.SerializeToString,
                response_deserializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyConfigResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/vocab_tuister.v1.VocabTesterService/CreateSession',
                request_serializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.CreateSessionResponse.FromString,
                _registered_method=True)


class VocabTesterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerifyVocab(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VocabTesterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyVocab': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyVocab,
                    request_deserializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyVocabRequest.FromString,
                    response_serializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyVocabResponse.SerializeToString,
            ),
            'VerifyConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyConfig,
                    request_deserializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyConfigRequest.FromString,
                    response_serializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyConfigResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.CreateSessionRequest.FromString,
                    response_serializer=vocab__tuister_dot_v1_dot_vocab__service__pb2.CreateSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vocab_tuister.v1.VocabTesterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vocab_tuister.v1.VocabTesterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VocabTesterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifyVocab(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocab_tuister.v1.VocabTesterService/VerifyVocab',
            vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyVocabRequest.SerializeToString,
            vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyVocabResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocab_tuister.v1.VocabTesterService/VerifyConfig',
            vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyConfigRequest.SerializeToString,
            vocab__tuister_dot_v1_dot_vocab__service__pb2.VerifyConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocab_tuister.v1.VocabTesterService/CreateSession',
            vocab__tuister_dot_v1_dot_vocab__service__pb2.CreateSessionRequest.SerializeToString,
            vocab__tuister_dot_v1_dot_vocab__service__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
