// Code generated by "stringer -type=createListStatus -linecomment -output=create_list_status_gen.go"; DO NOT EDIT.

package list

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InbuiltList-0]
	_ = x[LocalList-1]
	_ = x[CustomList-2]
}

const _createListStatus_name = "Inbuilt listLocal listCreate list"

var _createListStatus_index = [...]uint8{0, 12, 22, 33}

func (i createListStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_createListStatus_index)-1 {
		return "createListStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _createListStatus_name[_createListStatus_index[idx]:_createListStatus_index[idx+1]]
}
