// Code generated by "stringer -type=Case,Number,Gender,Tense,Voice,Mood,Person,Degree,PartOfSpeech -linecomment -output=endingcomponents_string.go"; DO NOT EDIT.

package endingcomponents

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownCase-0]
	_ = x[Nominative-1]
	_ = x[Vocative-2]
	_ = x[Accusative-3]
	_ = x[Genitive-4]
	_ = x[Dative-5]
	_ = x[Ablative-6]
}

const _Case_name = "nominativevocativeaccusativegenitivedativeablative"

var _Case_index = [...]uint8{0, 0, 10, 18, 28, 36, 42, 50}

func (i Case) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Case_index)-1 {
		return "Case(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Case_name[_Case_index[idx]:_Case_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownNumber-0]
	_ = x[Singular-1]
	_ = x[Plural-2]
}

const _Number_name = "singularplural"

var _Number_index = [...]uint8{0, 0, 8, 14}

func (i Number) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Number_index)-1 {
		return "Number(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Number_name[_Number_index[idx]:_Number_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownGender-0]
	_ = x[Masculine-1]
	_ = x[Feminine-2]
	_ = x[Neuter-3]
}

const _Gender_name = "masculinefeminineneuter"

var _Gender_index = [...]uint8{0, 0, 9, 17, 23}

func (i Gender) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Gender_index)-1 {
		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gender_name[_Gender_index[idx]:_Gender_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownTense-0]
	_ = x[Present-1]
	_ = x[Imperfect-2]
	_ = x[Future-3]
	_ = x[Perfect-4]
	_ = x[Pluperfect-5]
	_ = x[FuturePerfect-6]
}

const _Tense_name = "presentimperfectfutureperfectpluperfectfuture perfect"

var _Tense_index = [...]uint8{0, 0, 7, 16, 22, 29, 39, 53}

func (i Tense) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Tense_index)-1 {
		return "Tense(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tense_name[_Tense_index[idx]:_Tense_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownVoice-0]
	_ = x[Active-1]
	_ = x[Passive-2]
	_ = x[Deponent-3]
	_ = x[SemiDeponent-4]
}

const _Voice_name = "activepassivedeponentsemi-deponent"

var _Voice_index = [...]uint8{0, 0, 6, 13, 21, 34}

func (i Voice) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Voice_index)-1 {
		return "Voice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Voice_name[_Voice_index[idx]:_Voice_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownMood-0]
	_ = x[Indicative-1]
	_ = x[Subjunctive-2]
	_ = x[Imperative-3]
	_ = x[InfinitiveMood-4]
	_ = x[ParticipleMood-5]
	_ = x[Gerund-6]
	_ = x[Supine-7]
}

const _Mood_name = "indicativesubjunctiveimperativeinfinitiveparticiplegerundsupine"

var _Mood_index = [...]uint8{0, 0, 10, 21, 31, 41, 51, 57, 63}

func (i Mood) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mood_index)-1 {
		return "Mood(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mood_name[_Mood_index[idx]:_Mood_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownPerson-0]
	_ = x[FirstPerson-1]
	_ = x[SecondPerson-2]
	_ = x[ThirdPerson-3]
}

const _Person_name = "1st person2nd person3rd person"

var _Person_index = [...]uint8{0, 0, 10, 20, 30}

func (i Person) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Person_index)-1 {
		return "Person(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Person_name[_Person_index[idx]:_Person_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownDegree-0]
	_ = x[Positive-1]
	_ = x[Comparative-2]
	_ = x[Superlative-3]
}

const _Degree_name = "positivecomparativesuperlative"

var _Degree_index = [...]uint8{0, 0, 8, 19, 30}

func (i Degree) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Degree_index)-1 {
		return "Degree(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Degree_name[_Degree_index[idx]:_Degree_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownPartOfSpeech-0]
	_ = x[Noun-1]
	_ = x[Pronoun-2]
	_ = x[Adjective-3]
	_ = x[Verb-4]
	_ = x[VerbalNoun-5]
	_ = x[ParticiplePOS-6]
	_ = x[InfinitivePOS-7]
	_ = x[Adverb-8]
	_ = x[RegularWord-9]
}

const _PartOfSpeech_name = "nounpronounadjectiveverbverbal nounparticipleinfinitiveadverbregular word"

var _PartOfSpeech_index = [...]uint8{0, 0, 4, 11, 20, 24, 35, 45, 55, 61, 73}

func (i PartOfSpeech) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PartOfSpeech_index)-1 {
		return "PartOfSpeech(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PartOfSpeech_name[_PartOfSpeech_index[idx]:_PartOfSpeech_index[idx+1]]
}
