"""A package that generates questions about Latin vocabulary, from a
VocabList object generated by lego.
"""  # ruff:ignore[missing-blank-line-after-summary]

from __future__ import annotations

from . import asker, exceptions, question_classes, rules, type_aliases

__all__ = ["asker", "exceptions", "question_classes", "rules", "type_aliases"]
