"""Contains type aliases used by rogo."""

from typing import ReadOnly, TypedDict

from src.core.accido.endings import _Word

type Vocab = list[_Word]

Settings = TypedDict(
    "Settings",
    {
        "exclude-adjectives": ReadOnly[bool],
        "exclude-adjective-212-declension": ReadOnly[bool],
        "exclude-adjective-third-declension": ReadOnly[bool],
        "exclude-adjective-masculine": ReadOnly[bool],
        "exclude-adjective-feminine": ReadOnly[bool],
        "exclude-adjective-neuter": ReadOnly[bool],
        "exclude-adjective-nominative": ReadOnly[bool],
        "exclude-adjective-vocative": ReadOnly[bool],
        "exclude-adjective-accusative": ReadOnly[bool],
        "exclude-adjective-genitive": ReadOnly[bool],
        "exclude-adjective-dative": ReadOnly[bool],
        "exclude-adjective-ablative": ReadOnly[bool],
        "exclude-adjective-singular": ReadOnly[bool],
        "exclude-adjective-plural": ReadOnly[bool],
        "exclude-adjective-positive": ReadOnly[bool],
        "exclude-adjective-comparative": ReadOnly[bool],
        "exclude-adjective-superlative": ReadOnly[bool],

        "exclude-adverbs": ReadOnly[bool],
        "exclude-adverb-positive": ReadOnly[bool],
        "exclude-adverb-comparative": ReadOnly[bool],
        "exclude-adverb-superlative": ReadOnly[bool],

        "exclude-nouns": ReadOnly[bool],
        "exclude-noun-first-declension": ReadOnly[bool],
        "exclude-noun-second-declension": ReadOnly[bool],
        "exclude-noun-third-declension": ReadOnly[bool],
        "exclude-noun-fourth-declension": ReadOnly[bool],
        "exclude-noun-fifth-declension": ReadOnly[bool],
        "exclude-noun-irregular-declension": ReadOnly[bool],
        "exclude-noun-nominative": ReadOnly[bool],
        "exclude-noun-vocative": ReadOnly[bool],
        "exclude-noun-accusative": ReadOnly[bool],
        "exclude-noun-genitive": ReadOnly[bool],
        "exclude-noun-dative": ReadOnly[bool],
        "exclude-noun-ablative": ReadOnly[bool],
        "exclude-noun-singular": ReadOnly[bool],
        "exclude-noun-plural": ReadOnly[bool],

        "exclude-pronouns": ReadOnly[bool],
        "exclude-pronoun-masculine": ReadOnly[bool],
        "exclude-pronoun-feminine": ReadOnly[bool],
        "exclude-pronoun-neuter": ReadOnly[bool],
        "exclude-pronoun-nominative": ReadOnly[bool],
        "exclude-pronoun-vocative": ReadOnly[bool],
        "exclude-pronoun-accusative": ReadOnly[bool],
        "exclude-pronoun-genitive": ReadOnly[bool],
        "exclude-pronoun-dative": ReadOnly[bool],
        "exclude-pronoun-ablative": ReadOnly[bool],
        "exclude-pronoun-singular": ReadOnly[bool],
        "exclude-pronoun-plural": ReadOnly[bool],

        "exclude-regulars": ReadOnly[bool],

        "exclude-verbs": ReadOnly[bool],
        "exclude-deponents": ReadOnly[bool],
        "exclude-verb-first-conjugation": ReadOnly[bool],
        "exclude-verb-second-conjugation": ReadOnly[bool],
        "exclude-verb-third-conjugation": ReadOnly[bool],
        "exclude-verb-fourth-conjugation": ReadOnly[bool],
        "exclude-verb-mixed-conjugation": ReadOnly[bool],
        "exclude-verb-irregular-conjugation": ReadOnly[bool],
        "exclude-verb-present-active-indicative": ReadOnly[bool],
        "exclude-verb-imperfect-active-indicative": ReadOnly[bool],
        "exclude-verb-future-active-indicative": ReadOnly[bool],
        "exclude-verb-perfect-active-indicative": ReadOnly[bool],
        "exclude-verb-pluperfect-active-indicative": ReadOnly[bool],
        "exclude-verb-future-perfect-active-indicative": ReadOnly[bool],
        "exclude-verb-present-passive-indicative": ReadOnly[bool],
        "exclude-verb-imperfect-passive-indicative": ReadOnly[bool],
        "exclude-verb-future-passive-indicative": ReadOnly[bool],
        "exclude-verb-perfect-passive-indicative": ReadOnly[bool],
        "exclude-verb-pluperfect-passive-indicative": ReadOnly[bool],
        "exclude-verb-future-perfect-passive-indicative": ReadOnly[bool],
        "exclude-verb-present-active-subjunctive": ReadOnly[bool],
        "exclude-verb-imperfect-active-subjunctive": ReadOnly[bool],
        "exclude-verb-perfect-active-subjunctive": ReadOnly[bool],
        "exclude-verb-pluperfect-active-subjunctive": ReadOnly[bool],
        "exclude-verb-present-active-imperative": ReadOnly[bool],
        "exclude-verb-future-active-imperative": ReadOnly[bool],
        "exclude-verb-present-passive-imperative": ReadOnly[bool],
        "exclude-verb-future-passive-imperative": ReadOnly[bool],
        "exclude-verb-present-active-infinitive": ReadOnly[bool],
        "exclude-verb-future-active-infinitive": ReadOnly[bool],
        "exclude-verb-perfect-active-infinitive": ReadOnly[bool],
        "exclude-verb-present-passive-infinitive": ReadOnly[bool],
        "exclude-verb-future-passive-infinitive": ReadOnly[bool],
        "exclude-verb-perfect-passive-infinitive": ReadOnly[bool],
        "exclude-verb-singular": ReadOnly[bool],
        "exclude-verb-plural": ReadOnly[bool],
        "exclude-verb-1st-person": ReadOnly[bool],
        "exclude-verb-2nd-person": ReadOnly[bool],
        "exclude-verb-3rd-person": ReadOnly[bool],

        "exclude-participles": ReadOnly[bool],
        "exclude-participle-present-active": ReadOnly[bool],
        "exclude-participle-perfect-passive": ReadOnly[bool],
        "exclude-participle-future-active": ReadOnly[bool],
        "exclude-gerundives": ReadOnly[bool],
        "exclude-participle-masculine": ReadOnly[bool],
        "exclude-participle-feminine": ReadOnly[bool],
        "exclude-participle-neuter": ReadOnly[bool],
        "exclude-participle-nominative": ReadOnly[bool],
        "exclude-participle-vocative": ReadOnly[bool],
        "exclude-participle-accusative": ReadOnly[bool],
        "exclude-participle-genitive": ReadOnly[bool],
        "exclude-participle-dative": ReadOnly[bool],
        "exclude-participle-ablative": ReadOnly[bool],
        "exclude-participle-singular": ReadOnly[bool],
        "exclude-participle-plural": ReadOnly[bool],

        "exclude-gerunds": ReadOnly[bool],
        "exclude-supines": ReadOnly[bool],

        "english-subjunctives": ReadOnly[bool],
        "english-verbal-nouns": ReadOnly[bool],

        "include-typein-engtolat": ReadOnly[bool],
        "include-typein-lattoeng": ReadOnly[bool],
        "include-parse": ReadOnly[bool],
        "include-inflect": ReadOnly[bool],
        "include-principal-parts": ReadOnly[bool],
        "include-multiplechoice-engtolat": ReadOnly[bool],
        "include-multiplechoice-lattoeng": ReadOnly[bool],
        "number-multiplechoice-options": ReadOnly[int],
    },
)  # fmt: skip


SettingsRules = TypedDict(
    "SettingsRules",
    {
        "exclude-adjective-masculine": ReadOnly[str],
        "exclude-adjective-feminine": ReadOnly[str],
        "exclude-adjective-neuter": ReadOnly[str],
        "exclude-adjective-nominative": ReadOnly[str],
        "exclude-adjective-vocative": ReadOnly[str],
        "exclude-adjective-accusative": ReadOnly[str],
        "exclude-adjective-genitive": ReadOnly[str],
        "exclude-adjective-dative": ReadOnly[str],
        "exclude-adjective-ablative": ReadOnly[str],
        "exclude-adjective-singular": ReadOnly[str],
        "exclude-adjective-plural": ReadOnly[str],
        "exclude-adjective-positive": ReadOnly[str],
        "exclude-adjective-comparative": ReadOnly[str],
        "exclude-adjective-superlative": ReadOnly[str],

        "exclude-adverbs": ReadOnly[str],
        "exclude-adverb-positive": ReadOnly[str],
        "exclude-adverb-comparative": ReadOnly[str],
        "exclude-adverb-superlative": ReadOnly[str],

        "exclude-noun-nominative": ReadOnly[str],
        "exclude-noun-vocative": ReadOnly[str],
        "exclude-noun-accusative": ReadOnly[str],
        "exclude-noun-genitive": ReadOnly[str],
        "exclude-noun-dative": ReadOnly[str],
        "exclude-noun-ablative": ReadOnly[str],
        "exclude-noun-singular": ReadOnly[str],
        "exclude-noun-plural": ReadOnly[str],

        "exclude-pronoun-masculine": ReadOnly[str],
        "exclude-pronoun-feminine": ReadOnly[str],
        "exclude-pronoun-neuter": ReadOnly[str],
        "exclude-pronoun-nominative": ReadOnly[str],
        "exclude-pronoun-vocative": ReadOnly[str],
        "exclude-pronoun-accusative": ReadOnly[str],
        "exclude-pronoun-genitive": ReadOnly[str],
        "exclude-pronoun-dative": ReadOnly[str],
        "exclude-pronoun-ablative": ReadOnly[str],
        "exclude-pronoun-singular": ReadOnly[str],
        "exclude-pronoun-plural": ReadOnly[str],

        "exclude-verb-present-active-indicative": ReadOnly[str],
        "exclude-verb-imperfect-active-indicative": ReadOnly[str],
        "exclude-verb-future-active-indicative": ReadOnly[str],
        "exclude-verb-perfect-active-indicative": ReadOnly[str],
        "exclude-verb-pluperfect-active-indicative": ReadOnly[str],
        "exclude-verb-future-perfect-active-indicative": ReadOnly[str],
        "exclude-verb-present-passive-indicative": ReadOnly[str],
        "exclude-verb-imperfect-passive-indicative": ReadOnly[str],
        "exclude-verb-future-passive-indicative": ReadOnly[str],
        "exclude-verb-perfect-passive-indicative": ReadOnly[str],
        "exclude-verb-pluperfect-passive-indicative": ReadOnly[str],
        "exclude-verb-future-perfect-passive-indicative": ReadOnly[str],
        "exclude-verb-present-active-subjunctive": ReadOnly[str],
        "exclude-verb-imperfect-active-subjunctive": ReadOnly[str],
        "exclude-verb-perfect-active-subjunctive": ReadOnly[str],
        "exclude-verb-pluperfect-active-subjunctive": ReadOnly[str],
        "exclude-verb-present-active-imperative": ReadOnly[str],
        "exclude-verb-future-active-imperative": ReadOnly[str],
        "exclude-verb-present-passive-imperative": ReadOnly[str],
        "exclude-verb-future-passive-imperative": ReadOnly[str],
        "exclude-verb-present-active-infinitive": ReadOnly[str],
        "exclude-verb-future-active-infinitive": ReadOnly[str],
        "exclude-verb-perfect-active-infinitive": ReadOnly[str],
        "exclude-verb-present-passive-infinitive": ReadOnly[str],
        "exclude-verb-future-passive-infinitive": ReadOnly[str],
        "exclude-verb-perfect-passive-infinitive": ReadOnly[str],
        "exclude-verb-singular": ReadOnly[str],
        "exclude-verb-plural": ReadOnly[str],
        "exclude-verb-1st-person": ReadOnly[str],
        "exclude-verb-2nd-person": ReadOnly[str],
        "exclude-verb-3rd-person": ReadOnly[str],

        "exclude-participles": ReadOnly[str],
        "exclude-participle-present-active": ReadOnly[str],
        "exclude-participle-perfect-passive": ReadOnly[str],
        "exclude-participle-future-active": ReadOnly[str],
        "exclude-gerundives": ReadOnly[str],
        "exclude-participle-masculine": ReadOnly[str],
        "exclude-participle-feminine": ReadOnly[str],
        "exclude-participle-neuter": ReadOnly[str],
        "exclude-participle-nominative": ReadOnly[str],
        "exclude-participle-vocative": ReadOnly[str],
        "exclude-participle-accusative": ReadOnly[str],
        "exclude-participle-genitive": ReadOnly[str],
        "exclude-participle-dative": ReadOnly[str],
        "exclude-participle-ablative": ReadOnly[str],
        "exclude-participle-singular": ReadOnly[str],
        "exclude-participle-plural": ReadOnly[str],

        "exclude-gerunds": ReadOnly[str],
        "exclude-supines": ReadOnly[str],
    },
)  # fmt: skip
