__all__ = ["getargspec", "raise_with_traceback", "raise_from_none"]
from _typeshed import Incomplete

def getargspec(method: Incomplete) -> Incomplete: ...
def raise_with_traceback(exc: Incomplete, tb: Incomplete) -> None: ...
def raise_from_none(exc: Incomplete) -> None: ...
