// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vocab_tuister/v1/endingcomponents.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Case int32

const (
	Case_CASE_UNSPECIFIED Case = 0
	Case_CASE_NOMINATIVE  Case = 1
	Case_CASE_VOCATIVE    Case = 2
	Case_CASE_ACCUSATIVE  Case = 3
	Case_CASE_GENITIVE    Case = 4
	Case_CASE_DATIVE      Case = 5
	Case_CASE_ABLATIVE    Case = 6
)

// Enum value maps for Case.
var (
	Case_name = map[int32]string{
		0: "CASE_UNSPECIFIED",
		1: "CASE_NOMINATIVE",
		2: "CASE_VOCATIVE",
		3: "CASE_ACCUSATIVE",
		4: "CASE_GENITIVE",
		5: "CASE_DATIVE",
		6: "CASE_ABLATIVE",
	}
	Case_value = map[string]int32{
		"CASE_UNSPECIFIED": 0,
		"CASE_NOMINATIVE":  1,
		"CASE_VOCATIVE":    2,
		"CASE_ACCUSATIVE":  3,
		"CASE_GENITIVE":    4,
		"CASE_DATIVE":      5,
		"CASE_ABLATIVE":    6,
	}
)

func (x Case) Enum() *Case {
	p := new(Case)
	*p = x
	return p
}

func (x Case) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Case) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[0].Descriptor()
}

func (Case) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[0]
}

func (x Case) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Case.Descriptor instead.
func (Case) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{0}
}

type Number int32

const (
	Number_NUMBER_UNSPECIFIED Number = 0
	Number_NUMBER_SINGULAR    Number = 1
	Number_NUMBER_PLURAL      Number = 2
)

// Enum value maps for Number.
var (
	Number_name = map[int32]string{
		0: "NUMBER_UNSPECIFIED",
		1: "NUMBER_SINGULAR",
		2: "NUMBER_PLURAL",
	}
	Number_value = map[string]int32{
		"NUMBER_UNSPECIFIED": 0,
		"NUMBER_SINGULAR":    1,
		"NUMBER_PLURAL":      2,
	}
)

func (x Number) Enum() *Number {
	p := new(Number)
	*p = x
	return p
}

func (x Number) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Number) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[1].Descriptor()
}

func (Number) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[1]
}

func (x Number) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Number.Descriptor instead.
func (Number) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{1}
}

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MASCULINE   Gender = 1
	Gender_GENDER_FEMININE    Gender = 2
	Gender_GENDER_NEUTER      Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MASCULINE",
		2: "GENDER_FEMININE",
		3: "GENDER_NEUTER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MASCULINE":   1,
		"GENDER_FEMININE":    2,
		"GENDER_NEUTER":      3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[2].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[2]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{2}
}

type Tense int32

const (
	Tense_TENSE_UNSPECIFIED    Tense = 0
	Tense_TENSE_PRESENT        Tense = 1
	Tense_TENSE_IMPERFECT      Tense = 2
	Tense_TENSE_FUTURE         Tense = 3
	Tense_TENSE_PERFECT        Tense = 4
	Tense_TENSE_PLUPERFECT     Tense = 5
	Tense_TENSE_FUTURE_PERFECT Tense = 6
)

// Enum value maps for Tense.
var (
	Tense_name = map[int32]string{
		0: "TENSE_UNSPECIFIED",
		1: "TENSE_PRESENT",
		2: "TENSE_IMPERFECT",
		3: "TENSE_FUTURE",
		4: "TENSE_PERFECT",
		5: "TENSE_PLUPERFECT",
		6: "TENSE_FUTURE_PERFECT",
	}
	Tense_value = map[string]int32{
		"TENSE_UNSPECIFIED":    0,
		"TENSE_PRESENT":        1,
		"TENSE_IMPERFECT":      2,
		"TENSE_FUTURE":         3,
		"TENSE_PERFECT":        4,
		"TENSE_PLUPERFECT":     5,
		"TENSE_FUTURE_PERFECT": 6,
	}
)

func (x Tense) Enum() *Tense {
	p := new(Tense)
	*p = x
	return p
}

func (x Tense) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tense) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[3].Descriptor()
}

func (Tense) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[3]
}

func (x Tense) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tense.Descriptor instead.
func (Tense) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{3}
}

type Voice int32

const (
	Voice_VOICE_UNSPECIFIED   Voice = 0
	Voice_VOICE_ACTIVE        Voice = 1
	Voice_VOICE_PASSIVE       Voice = 2
	Voice_VOICE_DEPONENT      Voice = 3
	Voice_VOICE_SEMI_DEPONENT Voice = 4
)

// Enum value maps for Voice.
var (
	Voice_name = map[int32]string{
		0: "VOICE_UNSPECIFIED",
		1: "VOICE_ACTIVE",
		2: "VOICE_PASSIVE",
		3: "VOICE_DEPONENT",
		4: "VOICE_SEMI_DEPONENT",
	}
	Voice_value = map[string]int32{
		"VOICE_UNSPECIFIED":   0,
		"VOICE_ACTIVE":        1,
		"VOICE_PASSIVE":       2,
		"VOICE_DEPONENT":      3,
		"VOICE_SEMI_DEPONENT": 4,
	}
)

func (x Voice) Enum() *Voice {
	p := new(Voice)
	*p = x
	return p
}

func (x Voice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Voice) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[4].Descriptor()
}

func (Voice) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[4]
}

func (x Voice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Voice.Descriptor instead.
func (Voice) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{4}
}

type Mood int32

const (
	Mood_MOOD_UNSPECIFIED Mood = 0
	Mood_MOOD_INDICATIVE  Mood = 1
	Mood_MOOD_SUBJUNCTIVE Mood = 2
	Mood_MOOD_IMPERATIVE  Mood = 3
	Mood_MOOD_INFINITIVE  Mood = 4
	Mood_MOOD_PARTICIPLE  Mood = 5
	Mood_MOOD_GERUND      Mood = 6
	Mood_MOOD_SUPINE      Mood = 7
)

// Enum value maps for Mood.
var (
	Mood_name = map[int32]string{
		0: "MOOD_UNSPECIFIED",
		1: "MOOD_INDICATIVE",
		2: "MOOD_SUBJUNCTIVE",
		3: "MOOD_IMPERATIVE",
		4: "MOOD_INFINITIVE",
		5: "MOOD_PARTICIPLE",
		6: "MOOD_GERUND",
		7: "MOOD_SUPINE",
	}
	Mood_value = map[string]int32{
		"MOOD_UNSPECIFIED": 0,
		"MOOD_INDICATIVE":  1,
		"MOOD_SUBJUNCTIVE": 2,
		"MOOD_IMPERATIVE":  3,
		"MOOD_INFINITIVE":  4,
		"MOOD_PARTICIPLE":  5,
		"MOOD_GERUND":      6,
		"MOOD_SUPINE":      7,
	}
)

func (x Mood) Enum() *Mood {
	p := new(Mood)
	*p = x
	return p
}

func (x Mood) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mood) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[5].Descriptor()
}

func (Mood) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[5]
}

func (x Mood) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mood.Descriptor instead.
func (Mood) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{5}
}

type Person int32

const (
	Person_PERSON_UNSPECIFIED Person = 0
	Person_PERSON_FIRST       Person = 1
	Person_PERSON_SECOND      Person = 2
	Person_PERSON_THIRD       Person = 3
)

// Enum value maps for Person.
var (
	Person_name = map[int32]string{
		0: "PERSON_UNSPECIFIED",
		1: "PERSON_FIRST",
		2: "PERSON_SECOND",
		3: "PERSON_THIRD",
	}
	Person_value = map[string]int32{
		"PERSON_UNSPECIFIED": 0,
		"PERSON_FIRST":       1,
		"PERSON_SECOND":      2,
		"PERSON_THIRD":       3,
	}
)

func (x Person) Enum() *Person {
	p := new(Person)
	*p = x
	return p
}

func (x Person) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[6].Descriptor()
}

func (Person) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[6]
}

func (x Person) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person.Descriptor instead.
func (Person) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{6}
}

type Degree int32

const (
	Degree_DEGREE_UNSPECIFIED Degree = 0
	Degree_DEGREE_POSITIVE    Degree = 1
	Degree_DEGREE_COMPARATIVE Degree = 2
	Degree_DEGREE_SUPERLATIVE Degree = 3
)

// Enum value maps for Degree.
var (
	Degree_name = map[int32]string{
		0: "DEGREE_UNSPECIFIED",
		1: "DEGREE_POSITIVE",
		2: "DEGREE_COMPARATIVE",
		3: "DEGREE_SUPERLATIVE",
	}
	Degree_value = map[string]int32{
		"DEGREE_UNSPECIFIED": 0,
		"DEGREE_POSITIVE":    1,
		"DEGREE_COMPARATIVE": 2,
		"DEGREE_SUPERLATIVE": 3,
	}
)

func (x Degree) Enum() *Degree {
	p := new(Degree)
	*p = x
	return p
}

func (x Degree) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Degree) Descriptor() protoreflect.EnumDescriptor {
	return file_vocab_tuister_v1_endingcomponents_proto_enumTypes[7].Descriptor()
}

func (Degree) Type() protoreflect.EnumType {
	return &file_vocab_tuister_v1_endingcomponents_proto_enumTypes[7]
}

func (x Degree) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Degree.Descriptor instead.
func (Degree) EnumDescriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{7}
}

type EndingComponents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Case          Case                   `protobuf:"varint,1,opt,name=case,proto3,enum=vocab_tuister.v1.Case" json:"case,omitempty"`
	Number        Number                 `protobuf:"varint,2,opt,name=number,proto3,enum=vocab_tuister.v1.Number" json:"number,omitempty"`
	Gender        Gender                 `protobuf:"varint,3,opt,name=gender,proto3,enum=vocab_tuister.v1.Gender" json:"gender,omitempty"`
	Tense         Tense                  `protobuf:"varint,4,opt,name=tense,proto3,enum=vocab_tuister.v1.Tense" json:"tense,omitempty"`
	Voice         Voice                  `protobuf:"varint,5,opt,name=voice,proto3,enum=vocab_tuister.v1.Voice" json:"voice,omitempty"`
	Mood          Mood                   `protobuf:"varint,6,opt,name=mood,proto3,enum=vocab_tuister.v1.Mood" json:"mood,omitempty"`
	Person        Person                 `protobuf:"varint,7,opt,name=person,proto3,enum=vocab_tuister.v1.Person" json:"person,omitempty"`
	Degree        Degree                 `protobuf:"varint,8,opt,name=degree,proto3,enum=vocab_tuister.v1.Degree" json:"degree,omitempty"`
	String_       string                 `protobuf:"bytes,9,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndingComponents) Reset() {
	*x = EndingComponents{}
	mi := &file_vocab_tuister_v1_endingcomponents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndingComponents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndingComponents) ProtoMessage() {}

func (x *EndingComponents) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_endingcomponents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndingComponents.ProtoReflect.Descriptor instead.
func (*EndingComponents) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP(), []int{0}
}

func (x *EndingComponents) GetCase() Case {
	if x != nil {
		return x.Case
	}
	return Case_CASE_UNSPECIFIED
}

func (x *EndingComponents) GetNumber() Number {
	if x != nil {
		return x.Number
	}
	return Number_NUMBER_UNSPECIFIED
}

func (x *EndingComponents) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *EndingComponents) GetTense() Tense {
	if x != nil {
		return x.Tense
	}
	return Tense_TENSE_UNSPECIFIED
}

func (x *EndingComponents) GetVoice() Voice {
	if x != nil {
		return x.Voice
	}
	return Voice_VOICE_UNSPECIFIED
}

func (x *EndingComponents) GetMood() Mood {
	if x != nil {
		return x.Mood
	}
	return Mood_MOOD_UNSPECIFIED
}

func (x *EndingComponents) GetPerson() Person {
	if x != nil {
		return x.Person
	}
	return Person_PERSON_UNSPECIFIED
}

func (x *EndingComponents) GetDegree() Degree {
	if x != nil {
		return x.Degree
	}
	return Degree_DEGREE_UNSPECIFIED
}

func (x *EndingComponents) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

var File_vocab_tuister_v1_endingcomponents_proto protoreflect.FileDescriptor

const file_vocab_tuister_v1_endingcomponents_proto_rawDesc = "" +
	"\n" +
	"'vocab_tuister/v1/endingcomponents.proto\x12\x10vocab_tuister.v1\"\xa8\x03\n" +
	"\x10EndingComponents\x12*\n" +
	"\x04case\x18\x01 \x01(\x0e2\x16.vocab_tuister.v1.CaseR\x04case\x120\n" +
	"\x06number\x18\x02 \x01(\x0e2\x18.vocab_tuister.v1.NumberR\x06number\x120\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x18.vocab_tuister.v1.GenderR\x06gender\x12-\n" +
	"\x05tense\x18\x04 \x01(\x0e2\x17.vocab_tuister.v1.TenseR\x05tense\x12-\n" +
	"\x05voice\x18\x05 \x01(\x0e2\x17.vocab_tuister.v1.VoiceR\x05voice\x12*\n" +
	"\x04mood\x18\x06 \x01(\x0e2\x16.vocab_tuister.v1.MoodR\x04mood\x120\n" +
	"\x06person\x18\a \x01(\x0e2\x18.vocab_tuister.v1.PersonR\x06person\x120\n" +
	"\x06degree\x18\b \x01(\x0e2\x18.vocab_tuister.v1.DegreeR\x06degree\x12\x16\n" +
	"\x06string\x18\t \x01(\tR\x06string*\x90\x01\n" +
	"\x04Case\x12\x14\n" +
	"\x10CASE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCASE_NOMINATIVE\x10\x01\x12\x11\n" +
	"\rCASE_VOCATIVE\x10\x02\x12\x13\n" +
	"\x0fCASE_ACCUSATIVE\x10\x03\x12\x11\n" +
	"\rCASE_GENITIVE\x10\x04\x12\x0f\n" +
	"\vCASE_DATIVE\x10\x05\x12\x11\n" +
	"\rCASE_ABLATIVE\x10\x06*H\n" +
	"\x06Number\x12\x16\n" +
	"\x12NUMBER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNUMBER_SINGULAR\x10\x01\x12\x11\n" +
	"\rNUMBER_PLURAL\x10\x02*^\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10GENDER_MASCULINE\x10\x01\x12\x13\n" +
	"\x0fGENDER_FEMININE\x10\x02\x12\x11\n" +
	"\rGENDER_NEUTER\x10\x03*\x9b\x01\n" +
	"\x05Tense\x12\x15\n" +
	"\x11TENSE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTENSE_PRESENT\x10\x01\x12\x13\n" +
	"\x0fTENSE_IMPERFECT\x10\x02\x12\x10\n" +
	"\fTENSE_FUTURE\x10\x03\x12\x11\n" +
	"\rTENSE_PERFECT\x10\x04\x12\x14\n" +
	"\x10TENSE_PLUPERFECT\x10\x05\x12\x18\n" +
	"\x14TENSE_FUTURE_PERFECT\x10\x06*p\n" +
	"\x05Voice\x12\x15\n" +
	"\x11VOICE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVOICE_ACTIVE\x10\x01\x12\x11\n" +
	"\rVOICE_PASSIVE\x10\x02\x12\x12\n" +
	"\x0eVOICE_DEPONENT\x10\x03\x12\x17\n" +
	"\x13VOICE_SEMI_DEPONENT\x10\x04*\xa8\x01\n" +
	"\x04Mood\x12\x14\n" +
	"\x10MOOD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMOOD_INDICATIVE\x10\x01\x12\x14\n" +
	"\x10MOOD_SUBJUNCTIVE\x10\x02\x12\x13\n" +
	"\x0fMOOD_IMPERATIVE\x10\x03\x12\x13\n" +
	"\x0fMOOD_INFINITIVE\x10\x04\x12\x13\n" +
	"\x0fMOOD_PARTICIPLE\x10\x05\x12\x0f\n" +
	"\vMOOD_GERUND\x10\x06\x12\x0f\n" +
	"\vMOOD_SUPINE\x10\a*W\n" +
	"\x06Person\x12\x16\n" +
	"\x12PERSON_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPERSON_FIRST\x10\x01\x12\x11\n" +
	"\rPERSON_SECOND\x10\x02\x12\x10\n" +
	"\fPERSON_THIRD\x10\x03*e\n" +
	"\x06Degree\x12\x16\n" +
	"\x12DEGREE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDEGREE_POSITIVE\x10\x01\x12\x16\n" +
	"\x12DEGREE_COMPARATIVE\x10\x02\x12\x16\n" +
	"\x12DEGREE_SUPERLATIVE\x10\x03B=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3"

var (
	file_vocab_tuister_v1_endingcomponents_proto_rawDescOnce sync.Once
	file_vocab_tuister_v1_endingcomponents_proto_rawDescData []byte
)

func file_vocab_tuister_v1_endingcomponents_proto_rawDescGZIP() []byte {
	file_vocab_tuister_v1_endingcomponents_proto_rawDescOnce.Do(func() {
		file_vocab_tuister_v1_endingcomponents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_endingcomponents_proto_rawDesc), len(file_vocab_tuister_v1_endingcomponents_proto_rawDesc)))
	})
	return file_vocab_tuister_v1_endingcomponents_proto_rawDescData
}

var file_vocab_tuister_v1_endingcomponents_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_vocab_tuister_v1_endingcomponents_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vocab_tuister_v1_endingcomponents_proto_goTypes = []any{
	(Case)(0),                // 0: vocab_tuister.v1.Case
	(Number)(0),              // 1: vocab_tuister.v1.Number
	(Gender)(0),              // 2: vocab_tuister.v1.Gender
	(Tense)(0),               // 3: vocab_tuister.v1.Tense
	(Voice)(0),               // 4: vocab_tuister.v1.Voice
	(Mood)(0),                // 5: vocab_tuister.v1.Mood
	(Person)(0),              // 6: vocab_tuister.v1.Person
	(Degree)(0),              // 7: vocab_tuister.v1.Degree
	(*EndingComponents)(nil), // 8: vocab_tuister.v1.EndingComponents
}
var file_vocab_tuister_v1_endingcomponents_proto_depIdxs = []int32{
	0, // 0: vocab_tuister.v1.EndingComponents.case:type_name -> vocab_tuister.v1.Case
	1, // 1: vocab_tuister.v1.EndingComponents.number:type_name -> vocab_tuister.v1.Number
	2, // 2: vocab_tuister.v1.EndingComponents.gender:type_name -> vocab_tuister.v1.Gender
	3, // 3: vocab_tuister.v1.EndingComponents.tense:type_name -> vocab_tuister.v1.Tense
	4, // 4: vocab_tuister.v1.EndingComponents.voice:type_name -> vocab_tuister.v1.Voice
	5, // 5: vocab_tuister.v1.EndingComponents.mood:type_name -> vocab_tuister.v1.Mood
	6, // 6: vocab_tuister.v1.EndingComponents.person:type_name -> vocab_tuister.v1.Person
	7, // 7: vocab_tuister.v1.EndingComponents.degree:type_name -> vocab_tuister.v1.Degree
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_vocab_tuister_v1_endingcomponents_proto_init() }
func file_vocab_tuister_v1_endingcomponents_proto_init() {
	if File_vocab_tuister_v1_endingcomponents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_endingcomponents_proto_rawDesc), len(file_vocab_tuister_v1_endingcomponents_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vocab_tuister_v1_endingcomponents_proto_goTypes,
		DependencyIndexes: file_vocab_tuister_v1_endingcomponents_proto_depIdxs,
		EnumInfos:         file_vocab_tuister_v1_endingcomponents_proto_enumTypes,
		MessageInfos:      file_vocab_tuister_v1_endingcomponents_proto_msgTypes,
	}.Build()
	File_vocab_tuister_v1_endingcomponents_proto = out.File
	file_vocab_tuister_v1_endingcomponents_proto_goTypes = nil
	file_vocab_tuister_v1_endingcomponents_proto_depIdxs = nil
}
