// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vocab_tuister/v1/question.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultipleChoiceEngToLatQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Choices       []string               `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleChoiceEngToLatQuestion) Reset() {
	*x = MultipleChoiceEngToLatQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleChoiceEngToLatQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleChoiceEngToLatQuestion) ProtoMessage() {}

func (x *MultipleChoiceEngToLatQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleChoiceEngToLatQuestion.ProtoReflect.Descriptor instead.
func (*MultipleChoiceEngToLatQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{0}
}

func (x *MultipleChoiceEngToLatQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *MultipleChoiceEngToLatQuestion) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *MultipleChoiceEngToLatQuestion) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

type MultipleChoiceLatToEngQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Choices       []string               `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleChoiceLatToEngQuestion) Reset() {
	*x = MultipleChoiceLatToEngQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleChoiceLatToEngQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleChoiceLatToEngQuestion) ProtoMessage() {}

func (x *MultipleChoiceLatToEngQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleChoiceLatToEngQuestion.ProtoReflect.Descriptor instead.
func (*MultipleChoiceLatToEngQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{1}
}

func (x *MultipleChoiceLatToEngQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *MultipleChoiceLatToEngQuestion) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *MultipleChoiceLatToEngQuestion) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

type ParseWordCompToLatQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []string               `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	Components    *EndingComponents      `protobuf:"bytes,2,opt,name=components,proto3" json:"components,omitempty"`
	MainAnswer    string                 `protobuf:"bytes,3,opt,name=main_answer,json=mainAnswer,proto3" json:"main_answer,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseWordCompToLatQuestion) Reset() {
	*x = ParseWordCompToLatQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseWordCompToLatQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseWordCompToLatQuestion) ProtoMessage() {}

func (x *ParseWordCompToLatQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseWordCompToLatQuestion.ProtoReflect.Descriptor instead.
func (*ParseWordCompToLatQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{2}
}

func (x *ParseWordCompToLatQuestion) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *ParseWordCompToLatQuestion) GetComponents() *EndingComponents {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ParseWordCompToLatQuestion) GetMainAnswer() string {
	if x != nil {
		return x.MainAnswer
	}
	return ""
}

func (x *ParseWordCompToLatQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type ParseWordLatToCompQuestion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Answers         []*EndingComponents    `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	DictionaryEntry string                 `protobuf:"bytes,2,opt,name=dictionary_entry,json=dictionaryEntry,proto3" json:"dictionary_entry,omitempty"`
	MainAnswer      *EndingComponents      `protobuf:"bytes,3,opt,name=main_answer,json=mainAnswer,proto3" json:"main_answer,omitempty"`
	Prompt          string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParseWordLatToCompQuestion) Reset() {
	*x = ParseWordLatToCompQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseWordLatToCompQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseWordLatToCompQuestion) ProtoMessage() {}

func (x *ParseWordLatToCompQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseWordLatToCompQuestion.ProtoReflect.Descriptor instead.
func (*ParseWordLatToCompQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{3}
}

func (x *ParseWordLatToCompQuestion) GetAnswers() []*EndingComponents {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *ParseWordLatToCompQuestion) GetDictionaryEntry() string {
	if x != nil {
		return x.DictionaryEntry
	}
	return ""
}

func (x *ParseWordLatToCompQuestion) GetMainAnswer() *EndingComponents {
	if x != nil {
		return x.MainAnswer
	}
	return nil
}

func (x *ParseWordLatToCompQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type PrincipalPartsQuestion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrincipalParts []string               `protobuf:"bytes,1,rep,name=principal_parts,json=principalParts,proto3" json:"principal_parts,omitempty"`
	Prompt         string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrincipalPartsQuestion) Reset() {
	*x = PrincipalPartsQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalPartsQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalPartsQuestion) ProtoMessage() {}

func (x *PrincipalPartsQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalPartsQuestion.ProtoReflect.Descriptor instead.
func (*PrincipalPartsQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{4}
}

func (x *PrincipalPartsQuestion) GetPrincipalParts() []string {
	if x != nil {
		return x.PrincipalParts
	}
	return nil
}

func (x *PrincipalPartsQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type TypeInEngToLatQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []string               `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	MainAnswer    string                 `protobuf:"bytes,2,opt,name=main_answer,json=mainAnswer,proto3" json:"main_answer,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeInEngToLatQuestion) Reset() {
	*x = TypeInEngToLatQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeInEngToLatQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeInEngToLatQuestion) ProtoMessage() {}

func (x *TypeInEngToLatQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeInEngToLatQuestion.ProtoReflect.Descriptor instead.
func (*TypeInEngToLatQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{5}
}

func (x *TypeInEngToLatQuestion) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *TypeInEngToLatQuestion) GetMainAnswer() string {
	if x != nil {
		return x.MainAnswer
	}
	return ""
}

func (x *TypeInEngToLatQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type TypeInLatToEngQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []string               `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	MainAnswer    string                 `protobuf:"bytes,2,opt,name=main_answer,json=mainAnswer,proto3" json:"main_answer,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeInLatToEngQuestion) Reset() {
	*x = TypeInLatToEngQuestion{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeInLatToEngQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeInLatToEngQuestion) ProtoMessage() {}

func (x *TypeInLatToEngQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeInLatToEngQuestion.ProtoReflect.Descriptor instead.
func (*TypeInLatToEngQuestion) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{6}
}

func (x *TypeInLatToEngQuestion) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *TypeInLatToEngQuestion) GetMainAnswer() string {
	if x != nil {
		return x.MainAnswer
	}
	return ""
}

func (x *TypeInLatToEngQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type Question struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Question_McEngToLat
	//	*Question_McLatToEng
	//	*Question_ParseCompToLat
	//	*Question_ParseLatToComp
	//	*Question_PrincipalParts
	//	*Question_TypeInEngToLat
	//	*Question_TypeInLatToEng
	Kind          isQuestion_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_question_proto_rawDescGZIP(), []int{7}
}

func (x *Question) GetKind() isQuestion_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Question) GetMcEngToLat() *MultipleChoiceEngToLatQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_McEngToLat); ok {
			return x.McEngToLat
		}
	}
	return nil
}

func (x *Question) GetMcLatToEng() *MultipleChoiceLatToEngQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_McLatToEng); ok {
			return x.McLatToEng
		}
	}
	return nil
}

func (x *Question) GetParseCompToLat() *ParseWordCompToLatQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_ParseCompToLat); ok {
			return x.ParseCompToLat
		}
	}
	return nil
}

func (x *Question) GetParseLatToComp() *ParseWordLatToCompQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_ParseLatToComp); ok {
			return x.ParseLatToComp
		}
	}
	return nil
}

func (x *Question) GetPrincipalParts() *PrincipalPartsQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_PrincipalParts); ok {
			return x.PrincipalParts
		}
	}
	return nil
}

func (x *Question) GetTypeInEngToLat() *TypeInEngToLatQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_TypeInEngToLat); ok {
			return x.TypeInEngToLat
		}
	}
	return nil
}

func (x *Question) GetTypeInLatToEng() *TypeInLatToEngQuestion {
	if x != nil {
		if x, ok := x.Kind.(*Question_TypeInLatToEng); ok {
			return x.TypeInLatToEng
		}
	}
	return nil
}

type isQuestion_Kind interface {
	isQuestion_Kind()
}

type Question_McEngToLat struct {
	McEngToLat *MultipleChoiceEngToLatQuestion `protobuf:"bytes,1,opt,name=mc_eng_to_lat,json=mcEngToLat,proto3,oneof"`
}

type Question_McLatToEng struct {
	McLatToEng *MultipleChoiceLatToEngQuestion `protobuf:"bytes,2,opt,name=mc_lat_to_eng,json=mcLatToEng,proto3,oneof"`
}

type Question_ParseCompToLat struct {
	ParseCompToLat *ParseWordCompToLatQuestion `protobuf:"bytes,3,opt,name=parse_comp_to_lat,json=parseCompToLat,proto3,oneof"`
}

type Question_ParseLatToComp struct {
	ParseLatToComp *ParseWordLatToCompQuestion `protobuf:"bytes,4,opt,name=parse_lat_to_comp,json=parseLatToComp,proto3,oneof"`
}

type Question_PrincipalParts struct {
	PrincipalParts *PrincipalPartsQuestion `protobuf:"bytes,5,opt,name=principal_parts,json=principalParts,proto3,oneof"`
}

type Question_TypeInEngToLat struct {
	TypeInEngToLat *TypeInEngToLatQuestion `protobuf:"bytes,6,opt,name=type_in_eng_to_lat,json=typeInEngToLat,proto3,oneof"`
}

type Question_TypeInLatToEng struct {
	TypeInLatToEng *TypeInLatToEngQuestion `protobuf:"bytes,7,opt,name=type_in_lat_to_eng,json=typeInLatToEng,proto3,oneof"`
}

func (*Question_McEngToLat) isQuestion_Kind() {}

func (*Question_McLatToEng) isQuestion_Kind() {}

func (*Question_ParseCompToLat) isQuestion_Kind() {}

func (*Question_ParseLatToComp) isQuestion_Kind() {}

func (*Question_PrincipalParts) isQuestion_Kind() {}

func (*Question_TypeInEngToLat) isQuestion_Kind() {}

func (*Question_TypeInLatToEng) isQuestion_Kind() {}

var File_vocab_tuister_v1_question_proto protoreflect.FileDescriptor

const file_vocab_tuister_v1_question_proto_rawDesc = "" +
	"\n" +
	"\x1fvocab_tuister/v1/question.proto\x12\x10vocab_tuister.v1\x1a'vocab_tuister/v1/endingcomponents.proto\"j\n" +
	"\x1eMultipleChoiceEngToLatQuestion\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x18\n" +
	"\achoices\x18\x03 \x03(\tR\achoices\"j\n" +
	"\x1eMultipleChoiceLatToEngQuestion\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x18\n" +
	"\achoices\x18\x03 \x03(\tR\achoices\"\xb3\x01\n" +
	"\x1aParseWordCompToLatQuestion\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\tR\aanswers\x12B\n" +
	"\n" +
	"components\x18\x02 \x01(\v2\".vocab_tuister.v1.EndingComponentsR\n" +
	"components\x12\x1f\n" +
	"\vmain_answer\x18\x03 \x01(\tR\n" +
	"mainAnswer\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"\xe2\x01\n" +
	"\x1aParseWordLatToCompQuestion\x12<\n" +
	"\aanswers\x18\x01 \x03(\v2\".vocab_tuister.v1.EndingComponentsR\aanswers\x12)\n" +
	"\x10dictionary_entry\x18\x02 \x01(\tR\x0fdictionaryEntry\x12C\n" +
	"\vmain_answer\x18\x03 \x01(\v2\".vocab_tuister.v1.EndingComponentsR\n" +
	"mainAnswer\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"Y\n" +
	"\x16PrincipalPartsQuestion\x12'\n" +
	"\x0fprincipal_parts\x18\x01 \x03(\tR\x0eprincipalParts\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"k\n" +
	"\x16TypeInEngToLatQuestion\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\tR\aanswers\x12\x1f\n" +
	"\vmain_answer\x18\x02 \x01(\tR\n" +
	"mainAnswer\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"k\n" +
	"\x16TypeInLatToEngQuestion\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\tR\aanswers\x12\x1f\n" +
	"\vmain_answer\x18\x02 \x01(\tR\n" +
	"mainAnswer\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"\xfb\x04\n" +
	"\bQuestion\x12U\n" +
	"\rmc_eng_to_lat\x18\x01 \x01(\v20.vocab_tuister.v1.MultipleChoiceEngToLatQuestionH\x00R\n" +
	"mcEngToLat\x12U\n" +
	"\rmc_lat_to_eng\x18\x02 \x01(\v20.vocab_tuister.v1.MultipleChoiceLatToEngQuestionH\x00R\n" +
	"mcLatToEng\x12Y\n" +
	"\x11parse_comp_to_lat\x18\x03 \x01(\v2,.vocab_tuister.v1.ParseWordCompToLatQuestionH\x00R\x0eparseCompToLat\x12Y\n" +
	"\x11parse_lat_to_comp\x18\x04 \x01(\v2,.vocab_tuister.v1.ParseWordLatToCompQuestionH\x00R\x0eparseLatToComp\x12S\n" +
	"\x0fprincipal_parts\x18\x05 \x01(\v2(.vocab_tuister.v1.PrincipalPartsQuestionH\x00R\x0eprincipalParts\x12V\n" +
	"\x12type_in_eng_to_lat\x18\x06 \x01(\v2(.vocab_tuister.v1.TypeInEngToLatQuestionH\x00R\x0etypeInEngToLat\x12V\n" +
	"\x12type_in_lat_to_eng\x18\a \x01(\v2(.vocab_tuister.v1.TypeInLatToEngQuestionH\x00R\x0etypeInLatToEngB\x06\n" +
	"\x04kindB=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3"

var (
	file_vocab_tuister_v1_question_proto_rawDescOnce sync.Once
	file_vocab_tuister_v1_question_proto_rawDescData []byte
)

func file_vocab_tuister_v1_question_proto_rawDescGZIP() []byte {
	file_vocab_tuister_v1_question_proto_rawDescOnce.Do(func() {
		file_vocab_tuister_v1_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_question_proto_rawDesc), len(file_vocab_tuister_v1_question_proto_rawDesc)))
	})
	return file_vocab_tuister_v1_question_proto_rawDescData
}

var file_vocab_tuister_v1_question_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vocab_tuister_v1_question_proto_goTypes = []any{
	(*MultipleChoiceEngToLatQuestion)(nil), // 0: vocab_tuister.v1.MultipleChoiceEngToLatQuestion
	(*MultipleChoiceLatToEngQuestion)(nil), // 1: vocab_tuister.v1.MultipleChoiceLatToEngQuestion
	(*ParseWordCompToLatQuestion)(nil),     // 2: vocab_tuister.v1.ParseWordCompToLatQuestion
	(*ParseWordLatToCompQuestion)(nil),     // 3: vocab_tuister.v1.ParseWordLatToCompQuestion
	(*PrincipalPartsQuestion)(nil),         // 4: vocab_tuister.v1.PrincipalPartsQuestion
	(*TypeInEngToLatQuestion)(nil),         // 5: vocab_tuister.v1.TypeInEngToLatQuestion
	(*TypeInLatToEngQuestion)(nil),         // 6: vocab_tuister.v1.TypeInLatToEngQuestion
	(*Question)(nil),                       // 7: vocab_tuister.v1.Question
	(*EndingComponents)(nil),               // 8: vocab_tuister.v1.EndingComponents
}
var file_vocab_tuister_v1_question_proto_depIdxs = []int32{
	8,  // 0: vocab_tuister.v1.ParseWordCompToLatQuestion.components:type_name -> vocab_tuister.v1.EndingComponents
	8,  // 1: vocab_tuister.v1.ParseWordLatToCompQuestion.answers:type_name -> vocab_tuister.v1.EndingComponents
	8,  // 2: vocab_tuister.v1.ParseWordLatToCompQuestion.main_answer:type_name -> vocab_tuister.v1.EndingComponents
	0,  // 3: vocab_tuister.v1.Question.mc_eng_to_lat:type_name -> vocab_tuister.v1.MultipleChoiceEngToLatQuestion
	1,  // 4: vocab_tuister.v1.Question.mc_lat_to_eng:type_name -> vocab_tuister.v1.MultipleChoiceLatToEngQuestion
	2,  // 5: vocab_tuister.v1.Question.parse_comp_to_lat:type_name -> vocab_tuister.v1.ParseWordCompToLatQuestion
	3,  // 6: vocab_tuister.v1.Question.parse_lat_to_comp:type_name -> vocab_tuister.v1.ParseWordLatToCompQuestion
	4,  // 7: vocab_tuister.v1.Question.principal_parts:type_name -> vocab_tuister.v1.PrincipalPartsQuestion
	5,  // 8: vocab_tuister.v1.Question.type_in_eng_to_lat:type_name -> vocab_tuister.v1.TypeInEngToLatQuestion
	6,  // 9: vocab_tuister.v1.Question.type_in_lat_to_eng:type_name -> vocab_tuister.v1.TypeInLatToEngQuestion
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_vocab_tuister_v1_question_proto_init() }
func file_vocab_tuister_v1_question_proto_init() {
	if File_vocab_tuister_v1_question_proto != nil {
		return
	}
	file_vocab_tuister_v1_endingcomponents_proto_init()
	file_vocab_tuister_v1_question_proto_msgTypes[7].OneofWrappers = []any{
		(*Question_McEngToLat)(nil),
		(*Question_McLatToEng)(nil),
		(*Question_ParseCompToLat)(nil),
		(*Question_ParseLatToComp)(nil),
		(*Question_PrincipalParts)(nil),
		(*Question_TypeInEngToLat)(nil),
		(*Question_TypeInLatToEng)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_question_proto_rawDesc), len(file_vocab_tuister_v1_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vocab_tuister_v1_question_proto_goTypes,
		DependencyIndexes: file_vocab_tuister_v1_question_proto_depIdxs,
		MessageInfos:      file_vocab_tuister_v1_question_proto_msgTypes,
	}.Build()
	File_vocab_tuister_v1_question_proto = out.File
	file_vocab_tuister_v1_question_proto_goTypes = nil
	file_vocab_tuister_v1_question_proto_depIdxs = nil
}
