// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vocab_tuister/v1/sessionconfig.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionConfig struct {
	state                                     protoimpl.MessageState `protogen:"open.v1"`
	ExcludeAdjectives                         bool                   `protobuf:"varint,1,opt,name=exclude_adjectives,json=excludeAdjectives,proto3" json:"exclude_adjectives,omitempty"`                                                                                  // p2p: {"alias": "exclude-adjectives"}
	ExcludeAdjective_212Declension            bool                   `protobuf:"varint,2,opt,name=exclude_adjective_212_declension,json=excludeAdjective212Declension,proto3" json:"exclude_adjective_212_declension,omitempty"`                                          // p2p: {"alias": "exclude-adjective-212-declension"}
	ExcludeAdjectiveThirdDeclension           bool                   `protobuf:"varint,3,opt,name=exclude_adjective_third_declension,json=excludeAdjectiveThirdDeclension,proto3" json:"exclude_adjective_third_declension,omitempty"`                                    // p2p: {"alias": "exclude-adjective-third-declension"}
	ExcludeAdjectiveMasculine                 bool                   `protobuf:"varint,4,opt,name=exclude_adjective_masculine,json=excludeAdjectiveMasculine,proto3" json:"exclude_adjective_masculine,omitempty"`                                                        // p2p: {"alias": "exclude-adjective-masculine"}
	ExcludeAdjectiveFeminine                  bool                   `protobuf:"varint,5,opt,name=exclude_adjective_feminine,json=excludeAdjectiveFeminine,proto3" json:"exclude_adjective_feminine,omitempty"`                                                           // p2p: {"alias": "exclude-adjective-feminine"}
	ExcludeAdjectiveNeuter                    bool                   `protobuf:"varint,6,opt,name=exclude_adjective_neuter,json=excludeAdjectiveNeuter,proto3" json:"exclude_adjective_neuter,omitempty"`                                                                 // p2p: {"alias": "exclude-adjective-neuter"}
	ExcludeAdjectiveNominative                bool                   `protobuf:"varint,7,opt,name=exclude_adjective_nominative,json=excludeAdjectiveNominative,proto3" json:"exclude_adjective_nominative,omitempty"`                                                     // p2p: {"alias": "exclude-adjective-nominative"}
	ExcludeAdjectiveVocative                  bool                   `protobuf:"varint,8,opt,name=exclude_adjective_vocative,json=excludeAdjectiveVocative,proto3" json:"exclude_adjective_vocative,omitempty"`                                                           // p2p: {"alias": "exclude-adjective-vocative"}
	ExcludeAdjectiveAccusative                bool                   `protobuf:"varint,9,opt,name=exclude_adjective_accusative,json=excludeAdjectiveAccusative,proto3" json:"exclude_adjective_accusative,omitempty"`                                                     // p2p: {"alias": "exclude-adjective-accusative"}
	ExcludeAdjectiveGenitive                  bool                   `protobuf:"varint,10,opt,name=exclude_adjective_genitive,json=excludeAdjectiveGenitive,proto3" json:"exclude_adjective_genitive,omitempty"`                                                          // p2p: {"alias": "exclude-adjective-genitive"}
	ExcludeAdjectiveDative                    bool                   `protobuf:"varint,11,opt,name=exclude_adjective_dative,json=excludeAdjectiveDative,proto3" json:"exclude_adjective_dative,omitempty"`                                                                // p2p: {"alias": "exclude-adjective-dative"}
	ExcludeAdjectiveAblative                  bool                   `protobuf:"varint,12,opt,name=exclude_adjective_ablative,json=excludeAdjectiveAblative,proto3" json:"exclude_adjective_ablative,omitempty"`                                                          // p2p: {"alias": "exclude-adjective-ablative"}
	ExcludeAdjectiveSingular                  bool                   `protobuf:"varint,13,opt,name=exclude_adjective_singular,json=excludeAdjectiveSingular,proto3" json:"exclude_adjective_singular,omitempty"`                                                          // p2p: {"alias": "exclude-adjective-singular"}
	ExcludeAdjectivePlural                    bool                   `protobuf:"varint,14,opt,name=exclude_adjective_plural,json=excludeAdjectivePlural,proto3" json:"exclude_adjective_plural,omitempty"`                                                                // p2p: {"alias": "exclude-adjective-plural"}
	ExcludeAdjectivePositive                  bool                   `protobuf:"varint,15,opt,name=exclude_adjective_positive,json=excludeAdjectivePositive,proto3" json:"exclude_adjective_positive,omitempty"`                                                          // p2p: {"alias": "exclude-adjective-positive"}
	ExcludeAdjectiveComparative               bool                   `protobuf:"varint,16,opt,name=exclude_adjective_comparative,json=excludeAdjectiveComparative,proto3" json:"exclude_adjective_comparative,omitempty"`                                                 // p2p: {"alias": "exclude-adjective-comparative"}
	ExcludeAdjectiveSuperlative               bool                   `protobuf:"varint,17,opt,name=exclude_adjective_superlative,json=excludeAdjectiveSuperlative,proto3" json:"exclude_adjective_superlative,omitempty"`                                                 // p2p: {"alias": "exclude-adjective-superlative"}
	ExcludeAdverbs                            bool                   `protobuf:"varint,18,opt,name=exclude_adverbs,json=excludeAdverbs,proto3" json:"exclude_adverbs,omitempty"`                                                                                          // p2p: {"alias": "exclude-adverbs"}
	ExcludeAdverbPositive                     bool                   `protobuf:"varint,19,opt,name=exclude_adverb_positive,json=excludeAdverbPositive,proto3" json:"exclude_adverb_positive,omitempty"`                                                                   // p2p: {"alias": "exclude-adverb-positive"}
	ExcludeAdverbComparative                  bool                   `protobuf:"varint,20,opt,name=exclude_adverb_comparative,json=excludeAdverbComparative,proto3" json:"exclude_adverb_comparative,omitempty"`                                                          // p2p: {"alias": "exclude-adverb-comparative"}
	ExcludeAdverbSuperlative                  bool                   `protobuf:"varint,21,opt,name=exclude_adverb_superlative,json=excludeAdverbSuperlative,proto3" json:"exclude_adverb_superlative,omitempty"`                                                          // p2p: {"alias": "exclude-adverb-superlative"}
	ExcludeNouns                              bool                   `protobuf:"varint,22,opt,name=exclude_nouns,json=excludeNouns,proto3" json:"exclude_nouns,omitempty"`                                                                                                // p2p: {"alias": "exclude-nouns"}
	ExcludeNounFirstDeclension                bool                   `protobuf:"varint,23,opt,name=exclude_noun_first_declension,json=excludeNounFirstDeclension,proto3" json:"exclude_noun_first_declension,omitempty"`                                                  // p2p: {"alias": "exclude-noun-first-declension"}
	ExcludeNounSecondDeclension               bool                   `protobuf:"varint,24,opt,name=exclude_noun_second_declension,json=excludeNounSecondDeclension,proto3" json:"exclude_noun_second_declension,omitempty"`                                               // p2p: {"alias": "exclude-noun-second-declension"}
	ExcludeNounThirdDeclension                bool                   `protobuf:"varint,25,opt,name=exclude_noun_third_declension,json=excludeNounThirdDeclension,proto3" json:"exclude_noun_third_declension,omitempty"`                                                  // p2p: {"alias": "exclude-noun-third-declension"}
	ExcludeNounFourthDeclension               bool                   `protobuf:"varint,26,opt,name=exclude_noun_fourth_declension,json=excludeNounFourthDeclension,proto3" json:"exclude_noun_fourth_declension,omitempty"`                                               // p2p: {"alias": "exclude-noun-fourth-declension"}
	ExcludeNounFifthDeclension                bool                   `protobuf:"varint,27,opt,name=exclude_noun_fifth_declension,json=excludeNounFifthDeclension,proto3" json:"exclude_noun_fifth_declension,omitempty"`                                                  // p2p: {"alias": "exclude-noun-fifth-declension"}
	ExcludeNounIrregularDeclension            bool                   `protobuf:"varint,28,opt,name=exclude_noun_irregular_declension,json=excludeNounIrregularDeclension,proto3" json:"exclude_noun_irregular_declension,omitempty"`                                      // p2p: {"alias": "exclude-noun-irregular-declension"}
	ExcludeNounNominative                     bool                   `protobuf:"varint,29,opt,name=exclude_noun_nominative,json=excludeNounNominative,proto3" json:"exclude_noun_nominative,omitempty"`                                                                   // p2p: {"alias": "exclude-noun-nominative"}
	ExcludeNounVocative                       bool                   `protobuf:"varint,30,opt,name=exclude_noun_vocative,json=excludeNounVocative,proto3" json:"exclude_noun_vocative,omitempty"`                                                                         // p2p: {"alias": "exclude-noun-vocative"}
	ExcludeNounAccusative                     bool                   `protobuf:"varint,31,opt,name=exclude_noun_accusative,json=excludeNounAccusative,proto3" json:"exclude_noun_accusative,omitempty"`                                                                   // p2p: {"alias": "exclude-noun-accusative"}
	ExcludeNounGenitive                       bool                   `protobuf:"varint,32,opt,name=exclude_noun_genitive,json=excludeNounGenitive,proto3" json:"exclude_noun_genitive,omitempty"`                                                                         // p2p: {"alias": "exclude-noun-genitive"}
	ExcludeNounDative                         bool                   `protobuf:"varint,33,opt,name=exclude_noun_dative,json=excludeNounDative,proto3" json:"exclude_noun_dative,omitempty"`                                                                               // p2p: {"alias": "exclude-noun-dative"}
	ExcludeNounAblative                       bool                   `protobuf:"varint,34,opt,name=exclude_noun_ablative,json=excludeNounAblative,proto3" json:"exclude_noun_ablative,omitempty"`                                                                         // p2p: {"alias": "exclude-noun-ablative"}
	ExcludeNounSingular                       bool                   `protobuf:"varint,35,opt,name=exclude_noun_singular,json=excludeNounSingular,proto3" json:"exclude_noun_singular,omitempty"`                                                                         // p2p: {"alias": "exclude-noun-singular"}
	ExcludeNounPlural                         bool                   `protobuf:"varint,36,opt,name=exclude_noun_plural,json=excludeNounPlural,proto3" json:"exclude_noun_plural,omitempty"`                                                                               // p2p: {"alias": "exclude-noun-plural"}
	ExcludePronouns                           bool                   `protobuf:"varint,37,opt,name=exclude_pronouns,json=excludePronouns,proto3" json:"exclude_pronouns,omitempty"`                                                                                       // p2p: {"alias": "exclude-pronouns"}
	ExcludePronounMasculine                   bool                   `protobuf:"varint,38,opt,name=exclude_pronoun_masculine,json=excludePronounMasculine,proto3" json:"exclude_pronoun_masculine,omitempty"`                                                             // p2p: {"alias": "exclude-pronoun-masculine"}
	ExcludePronounFeminine                    bool                   `protobuf:"varint,39,opt,name=exclude_pronoun_feminine,json=excludePronounFeminine,proto3" json:"exclude_pronoun_feminine,omitempty"`                                                                // p2p: {"alias": "exclude-pronoun-feminine"}
	ExcludePronounNeuter                      bool                   `protobuf:"varint,40,opt,name=exclude_pronoun_neuter,json=excludePronounNeuter,proto3" json:"exclude_pronoun_neuter,omitempty"`                                                                      // p2p: {"alias": "exclude-pronoun-neuter"}
	ExcludePronounNominative                  bool                   `protobuf:"varint,41,opt,name=exclude_pronoun_nominative,json=excludePronounNominative,proto3" json:"exclude_pronoun_nominative,omitempty"`                                                          // p2p: {"alias": "exclude-pronoun-nominative"}
	ExcludePronounVocative                    bool                   `protobuf:"varint,42,opt,name=exclude_pronoun_vocative,json=excludePronounVocative,proto3" json:"exclude_pronoun_vocative,omitempty"`                                                                // p2p: {"alias": "exclude-pronoun-vocative"}
	ExcludePronounAccusative                  bool                   `protobuf:"varint,43,opt,name=exclude_pronoun_accusative,json=excludePronounAccusative,proto3" json:"exclude_pronoun_accusative,omitempty"`                                                          // p2p: {"alias": "exclude-pronoun-accusative"}
	ExcludePronounGenitive                    bool                   `protobuf:"varint,44,opt,name=exclude_pronoun_genitive,json=excludePronounGenitive,proto3" json:"exclude_pronoun_genitive,omitempty"`                                                                // p2p: {"alias": "exclude-pronoun-genitive"}
	ExcludePronounDative                      bool                   `protobuf:"varint,45,opt,name=exclude_pronoun_dative,json=excludePronounDative,proto3" json:"exclude_pronoun_dative,omitempty"`                                                                      // p2p: {"alias": "exclude-pronoun-dative"}
	ExcludePronounAblative                    bool                   `protobuf:"varint,46,opt,name=exclude_pronoun_ablative,json=excludePronounAblative,proto3" json:"exclude_pronoun_ablative,omitempty"`                                                                // p2p: {"alias": "exclude-pronoun-ablative"}
	ExcludePronounSingular                    bool                   `protobuf:"varint,47,opt,name=exclude_pronoun_singular,json=excludePronounSingular,proto3" json:"exclude_pronoun_singular,omitempty"`                                                                // p2p: {"alias": "exclude-pronoun-singular"}
	ExcludePronounPlural                      bool                   `protobuf:"varint,48,opt,name=exclude_pronoun_plural,json=excludePronounPlural,proto3" json:"exclude_pronoun_plural,omitempty"`                                                                      // p2p: {"alias": "exclude-pronoun-plural"}
	ExcludeRegulars                           bool                   `protobuf:"varint,49,opt,name=exclude_regulars,json=excludeRegulars,proto3" json:"exclude_regulars,omitempty"`                                                                                       // p2p: {"alias": "exclude-regulars"}
	ExcludeVerbs                              bool                   `protobuf:"varint,50,opt,name=exclude_verbs,json=excludeVerbs,proto3" json:"exclude_verbs,omitempty"`                                                                                                // p2p: {"alias": "exclude-verbs"}
	ExcludeDeponents                          bool                   `protobuf:"varint,51,opt,name=exclude_deponents,json=excludeDeponents,proto3" json:"exclude_deponents,omitempty"`                                                                                    // p2p: {"alias": "exclude-deponents"}
	ExcludeSemiDeponents                      bool                   `protobuf:"varint,52,opt,name=exclude_semi_deponents,json=excludeSemiDeponents,proto3" json:"exclude_semi_deponents,omitempty"`                                                                      // p2p: {"alias": "exclude-semi-deponents"}
	ExcludeVerbFirstConjugation               bool                   `protobuf:"varint,53,opt,name=exclude_verb_first_conjugation,json=excludeVerbFirstConjugation,proto3" json:"exclude_verb_first_conjugation,omitempty"`                                               // p2p: {"alias": "exclude-verb-first-conjugation"}
	ExcludeVerbSecondConjugation              bool                   `protobuf:"varint,54,opt,name=exclude_verb_second_conjugation,json=excludeVerbSecondConjugation,proto3" json:"exclude_verb_second_conjugation,omitempty"`                                            // p2p: {"alias": "exclude-verb-second-conjugation"}
	ExcludeVerbThirdConjugation               bool                   `protobuf:"varint,55,opt,name=exclude_verb_third_conjugation,json=excludeVerbThirdConjugation,proto3" json:"exclude_verb_third_conjugation,omitempty"`                                               // p2p: {"alias": "exclude-verb-third-conjugation"}
	ExcludeVerbFourthConjugation              bool                   `protobuf:"varint,56,opt,name=exclude_verb_fourth_conjugation,json=excludeVerbFourthConjugation,proto3" json:"exclude_verb_fourth_conjugation,omitempty"`                                            // p2p: {"alias": "exclude-verb-fourth-conjugation"}
	ExcludeVerbMixedConjugation               bool                   `protobuf:"varint,57,opt,name=exclude_verb_mixed_conjugation,json=excludeVerbMixedConjugation,proto3" json:"exclude_verb_mixed_conjugation,omitempty"`                                               // p2p: {"alias": "exclude-verb-mixed-conjugation"}
	ExcludeVerbIrregularConjugation           bool                   `protobuf:"varint,58,opt,name=exclude_verb_irregular_conjugation,json=excludeVerbIrregularConjugation,proto3" json:"exclude_verb_irregular_conjugation,omitempty"`                                   // p2p: {"alias": "exclude-verb-irregular-conjugation"}
	ExcludeVerbPresentActiveIndicative        bool                   `protobuf:"varint,59,opt,name=exclude_verb_present_active_indicative,json=excludeVerbPresentActiveIndicative,proto3" json:"exclude_verb_present_active_indicative,omitempty"`                        // p2p: {"alias": "exclude-verb-present-active-indicative"}
	ExcludeVerbImperfectActiveIndicative      bool                   `protobuf:"varint,60,opt,name=exclude_verb_imperfect_active_indicative,json=excludeVerbImperfectActiveIndicative,proto3" json:"exclude_verb_imperfect_active_indicative,omitempty"`                  // p2p: {"alias": "exclude-verb-imperfect-active-indicative"}
	ExcludeVerbFutureActiveIndicative         bool                   `protobuf:"varint,61,opt,name=exclude_verb_future_active_indicative,json=excludeVerbFutureActiveIndicative,proto3" json:"exclude_verb_future_active_indicative,omitempty"`                           // p2p: {"alias": "exclude-verb-future-active-indicative"}
	ExcludeVerbPerfectActiveIndicative        bool                   `protobuf:"varint,62,opt,name=exclude_verb_perfect_active_indicative,json=excludeVerbPerfectActiveIndicative,proto3" json:"exclude_verb_perfect_active_indicative,omitempty"`                        // p2p: {"alias": "exclude-verb-perfect-active-indicative"}
	ExcludeVerbPluperfectActiveIndicative     bool                   `protobuf:"varint,63,opt,name=exclude_verb_pluperfect_active_indicative,json=excludeVerbPluperfectActiveIndicative,proto3" json:"exclude_verb_pluperfect_active_indicative,omitempty"`               // p2p: {"alias": "exclude-verb-pluperfect-active-indicative"}
	ExcludeVerbFuturePerfectActiveIndicative  bool                   `protobuf:"varint,64,opt,name=exclude_verb_future_perfect_active_indicative,json=excludeVerbFuturePerfectActiveIndicative,proto3" json:"exclude_verb_future_perfect_active_indicative,omitempty"`    // p2p: {"alias": "exclude-verb-future-perfect-active-indicative"}
	ExcludeVerbPresentPassiveIndicative       bool                   `protobuf:"varint,65,opt,name=exclude_verb_present_passive_indicative,json=excludeVerbPresentPassiveIndicative,proto3" json:"exclude_verb_present_passive_indicative,omitempty"`                     // p2p: {"alias": "exclude-verb-present-passive-indicative"}
	ExcludeVerbImperfectPassiveIndicative     bool                   `protobuf:"varint,66,opt,name=exclude_verb_imperfect_passive_indicative,json=excludeVerbImperfectPassiveIndicative,proto3" json:"exclude_verb_imperfect_passive_indicative,omitempty"`               // p2p: {"alias": "exclude-verb-imperfect-passive-indicative"}
	ExcludeVerbFuturePassiveIndicative        bool                   `protobuf:"varint,67,opt,name=exclude_verb_future_passive_indicative,json=excludeVerbFuturePassiveIndicative,proto3" json:"exclude_verb_future_passive_indicative,omitempty"`                        // p2p: {"alias": "exclude-verb-future-passive-indicative"}
	ExcludeVerbPerfectPassiveIndicative       bool                   `protobuf:"varint,68,opt,name=exclude_verb_perfect_passive_indicative,json=excludeVerbPerfectPassiveIndicative,proto3" json:"exclude_verb_perfect_passive_indicative,omitempty"`                     // p2p: {"alias": "exclude-verb-perfect-passive-indicative"}
	ExcludeVerbPluperfectPassiveIndicative    bool                   `protobuf:"varint,69,opt,name=exclude_verb_pluperfect_passive_indicative,json=excludeVerbPluperfectPassiveIndicative,proto3" json:"exclude_verb_pluperfect_passive_indicative,omitempty"`            // p2p: {"alias": "exclude-verb-pluperfect-passive-indicative"}
	ExcludeVerbFuturePerfectPassiveIndicative bool                   `protobuf:"varint,70,opt,name=exclude_verb_future_perfect_passive_indicative,json=excludeVerbFuturePerfectPassiveIndicative,proto3" json:"exclude_verb_future_perfect_passive_indicative,omitempty"` // p2p: {"alias": "exclude-verb-future-perfect-passive-indicative"}
	ExcludeVerbPresentActiveSubjunctive       bool                   `protobuf:"varint,71,opt,name=exclude_verb_present_active_subjunctive,json=excludeVerbPresentActiveSubjunctive,proto3" json:"exclude_verb_present_active_subjunctive,omitempty"`                     // p2p: {"alias": "exclude-verb-present-active-subjunctive"}
	ExcludeVerbImperfectActiveSubjunctive     bool                   `protobuf:"varint,72,opt,name=exclude_verb_imperfect_active_subjunctive,json=excludeVerbImperfectActiveSubjunctive,proto3" json:"exclude_verb_imperfect_active_subjunctive,omitempty"`               // p2p: {"alias": "exclude-verb-imperfect-active-subjunctive"}
	ExcludeVerbPerfectActiveSubjunctive       bool                   `protobuf:"varint,73,opt,name=exclude_verb_perfect_active_subjunctive,json=excludeVerbPerfectActiveSubjunctive,proto3" json:"exclude_verb_perfect_active_subjunctive,omitempty"`                     // p2p: {"alias": "exclude-verb-perfect-active-subjunctive"}
	ExcludeVerbPluperfectActiveSubjunctive    bool                   `protobuf:"varint,74,opt,name=exclude_verb_pluperfect_active_subjunctive,json=excludeVerbPluperfectActiveSubjunctive,proto3" json:"exclude_verb_pluperfect_active_subjunctive,omitempty"`            // p2p: {"alias": "exclude-verb-pluperfect-active-subjunctive"}
	ExcludeVerbPresentActiveImperative        bool                   `protobuf:"varint,75,opt,name=exclude_verb_present_active_imperative,json=excludeVerbPresentActiveImperative,proto3" json:"exclude_verb_present_active_imperative,omitempty"`                        // p2p: {"alias": "exclude-verb-present-active-imperative"}
	ExcludeVerbFutureActiveImperative         bool                   `protobuf:"varint,76,opt,name=exclude_verb_future_active_imperative,json=excludeVerbFutureActiveImperative,proto3" json:"exclude_verb_future_active_imperative,omitempty"`                           // p2p: {"alias": "exclude-verb-future-active-imperative"}
	ExcludeVerbPresentPassiveImperative       bool                   `protobuf:"varint,77,opt,name=exclude_verb_present_passive_imperative,json=excludeVerbPresentPassiveImperative,proto3" json:"exclude_verb_present_passive_imperative,omitempty"`                     // p2p: {"alias": "exclude-verb-present-passive-imperative"}
	ExcludeVerbFuturePassiveImperative        bool                   `protobuf:"varint,78,opt,name=exclude_verb_future_passive_imperative,json=excludeVerbFuturePassiveImperative,proto3" json:"exclude_verb_future_passive_imperative,omitempty"`                        // p2p: {"alias": "exclude-verb-future-passive-imperative"}
	ExcludeVerbPresentActiveInfinitive        bool                   `protobuf:"varint,79,opt,name=exclude_verb_present_active_infinitive,json=excludeVerbPresentActiveInfinitive,proto3" json:"exclude_verb_present_active_infinitive,omitempty"`                        // p2p: {"alias": "exclude-verb-present-active-infinitive"}
	ExcludeVerbFutureActiveInfinitive         bool                   `protobuf:"varint,80,opt,name=exclude_verb_future_active_infinitive,json=excludeVerbFutureActiveInfinitive,proto3" json:"exclude_verb_future_active_infinitive,omitempty"`                           // p2p: {"alias": "exclude-verb-future-active-infinitive"}
	ExcludeVerbPerfectActiveInfinitive        bool                   `protobuf:"varint,81,opt,name=exclude_verb_perfect_active_infinitive,json=excludeVerbPerfectActiveInfinitive,proto3" json:"exclude_verb_perfect_active_infinitive,omitempty"`                        // p2p: {"alias": "exclude-verb-perfect-active-infinitive"}
	ExcludeVerbPresentPassiveInfinitive       bool                   `protobuf:"varint,82,opt,name=exclude_verb_present_passive_infinitive,json=excludeVerbPresentPassiveInfinitive,proto3" json:"exclude_verb_present_passive_infinitive,omitempty"`                     // p2p: {"alias": "exclude-verb-present-passive-infinitive"}
	ExcludeVerbFuturePassiveInfinitive        bool                   `protobuf:"varint,83,opt,name=exclude_verb_future_passive_infinitive,json=excludeVerbFuturePassiveInfinitive,proto3" json:"exclude_verb_future_passive_infinitive,omitempty"`                        // p2p: {"alias": "exclude-verb-future-passive-infinitive"}
	ExcludeVerbPerfectPassiveInfinitive       bool                   `protobuf:"varint,84,opt,name=exclude_verb_perfect_passive_infinitive,json=excludeVerbPerfectPassiveInfinitive,proto3" json:"exclude_verb_perfect_passive_infinitive,omitempty"`                     // p2p: {"alias": "exclude-verb-perfect-passive-infinitive"}
	ExcludeVerbSingular                       bool                   `protobuf:"varint,85,opt,name=exclude_verb_singular,json=excludeVerbSingular,proto3" json:"exclude_verb_singular,omitempty"`                                                                         // p2p: {"alias": "exclude-verb-singular"}
	ExcludeVerbPlural                         bool                   `protobuf:"varint,86,opt,name=exclude_verb_plural,json=excludeVerbPlural,proto3" json:"exclude_verb_plural,omitempty"`                                                                               // p2p: {"alias": "exclude-verb-plural"}
	ExcludeVerb_1StPerson                     bool                   `protobuf:"varint,87,opt,name=exclude_verb_1st_person,json=excludeVerb1stPerson,proto3" json:"exclude_verb_1st_person,omitempty"`                                                                    // p2p: {"alias": "exclude-verb-1st-person"}
	ExcludeVerb_2NdPerson                     bool                   `protobuf:"varint,88,opt,name=exclude_verb_2nd_person,json=excludeVerb2ndPerson,proto3" json:"exclude_verb_2nd_person,omitempty"`                                                                    // p2p: {"alias": "exclude-verb-2nd-person"}
	ExcludeVerb_3RdPerson                     bool                   `protobuf:"varint,89,opt,name=exclude_verb_3rd_person,json=excludeVerb3rdPerson,proto3" json:"exclude_verb_3rd_person,omitempty"`                                                                    // p2p: {"alias": "exclude-verb-3rd-person"}
	ExcludeParticiples                        bool                   `protobuf:"varint,90,opt,name=exclude_participles,json=excludeParticiples,proto3" json:"exclude_participles,omitempty"`                                                                              // p2p: {"alias": "exclude-participles"}
	ExcludeParticiplePresentActive            bool                   `protobuf:"varint,91,opt,name=exclude_participle_present_active,json=excludeParticiplePresentActive,proto3" json:"exclude_participle_present_active,omitempty"`                                      // p2p: {"alias": "exclude-participle-present-active"}
	ExcludeParticiplePerfectPassive           bool                   `protobuf:"varint,92,opt,name=exclude_participle_perfect_passive,json=excludeParticiplePerfectPassive,proto3" json:"exclude_participle_perfect_passive,omitempty"`                                   // p2p: {"alias": "exclude-participle-perfect-passive"}
	ExcludeParticipleFutureActive             bool                   `protobuf:"varint,93,opt,name=exclude_participle_future_active,json=excludeParticipleFutureActive,proto3" json:"exclude_participle_future_active,omitempty"`                                         // p2p: {"alias": "exclude-participle-future-active"}
	ExcludeGerundives                         bool                   `protobuf:"varint,94,opt,name=exclude_gerundives,json=excludeGerundives,proto3" json:"exclude_gerundives,omitempty"`                                                                                 // p2p: {"alias": "exclude-gerundives"}
	ExcludeParticipleMasculine                bool                   `protobuf:"varint,95,opt,name=exclude_participle_masculine,json=excludeParticipleMasculine,proto3" json:"exclude_participle_masculine,omitempty"`                                                    // p2p: {"alias": "exclude-participle-masculine"}
	ExcludeParticipleFeminine                 bool                   `protobuf:"varint,96,opt,name=exclude_participle_feminine,json=excludeParticipleFeminine,proto3" json:"exclude_participle_feminine,omitempty"`                                                       // p2p: {"alias": "exclude-participle-feminine"}
	ExcludeParticipleNeuter                   bool                   `protobuf:"varint,97,opt,name=exclude_participle_neuter,json=excludeParticipleNeuter,proto3" json:"exclude_participle_neuter,omitempty"`                                                             // p2p: {"alias": "exclude-participle-neuter"}
	ExcludeParticipleNominative               bool                   `protobuf:"varint,98,opt,name=exclude_participle_nominative,json=excludeParticipleNominative,proto3" json:"exclude_participle_nominative,omitempty"`                                                 // p2p: {"alias": "exclude-participle-nominative"}
	ExcludeParticipleVocative                 bool                   `protobuf:"varint,99,opt,name=exclude_participle_vocative,json=excludeParticipleVocative,proto3" json:"exclude_participle_vocative,omitempty"`                                                       // p2p: {"alias": "exclude-participle-vocative"}
	ExcludeParticipleAccusative               bool                   `protobuf:"varint,100,opt,name=exclude_participle_accusative,json=excludeParticipleAccusative,proto3" json:"exclude_participle_accusative,omitempty"`                                                // p2p: {"alias": "exclude-participle-accusative"}
	ExcludeParticipleGenitive                 bool                   `protobuf:"varint,101,opt,name=exclude_participle_genitive,json=excludeParticipleGenitive,proto3" json:"exclude_participle_genitive,omitempty"`                                                      // p2p: {"alias": "exclude-participle-genitive"}
	ExcludeParticipleDative                   bool                   `protobuf:"varint,102,opt,name=exclude_participle_dative,json=excludeParticipleDative,proto3" json:"exclude_participle_dative,omitempty"`                                                            // p2p: {"alias": "exclude-participle-dative"}
	ExcludeParticipleAblative                 bool                   `protobuf:"varint,103,opt,name=exclude_participle_ablative,json=excludeParticipleAblative,proto3" json:"exclude_participle_ablative,omitempty"`                                                      // p2p: {"alias": "exclude-participle-ablative"}
	ExcludeParticipleSingular                 bool                   `protobuf:"varint,104,opt,name=exclude_participle_singular,json=excludeParticipleSingular,proto3" json:"exclude_participle_singular,omitempty"`                                                      // p2p: {"alias": "exclude-participle-singular"}
	ExcludeParticiplePlural                   bool                   `protobuf:"varint,105,opt,name=exclude_participle_plural,json=excludeParticiplePlural,proto3" json:"exclude_participle_plural,omitempty"`                                                            // p2p: {"alias": "exclude-participle-plural"}
	ExcludeGerunds                            bool                   `protobuf:"varint,106,opt,name=exclude_gerunds,json=excludeGerunds,proto3" json:"exclude_gerunds,omitempty"`                                                                                         // p2p: {"alias": "exclude-gerunds"}
	ExcludeSupines                            bool                   `protobuf:"varint,107,opt,name=exclude_supines,json=excludeSupines,proto3" json:"exclude_supines,omitempty"`                                                                                         // p2p: {"alias": "exclude-supines"}
	EnglishSubjunctives                       bool                   `protobuf:"varint,108,opt,name=english_subjunctives,json=englishSubjunctives,proto3" json:"english_subjunctives,omitempty"`                                                                          // p2p: {"alias": "english-subjunctives"}
	EnglishVerbalNouns                        bool                   `protobuf:"varint,109,opt,name=english_verbal_nouns,json=englishVerbalNouns,proto3" json:"english_verbal_nouns,omitempty"`                                                                           // p2p: {"alias": "english-verbal-nouns"}
	IncludeTypeinEngtolat                     bool                   `protobuf:"varint,110,opt,name=include_typein_engtolat,json=includeTypeinEngtolat,proto3" json:"include_typein_engtolat,omitempty"`                                                                  // p2p: {"alias": "include-typein-engtolat"}
	IncludeTypeinLattoeng                     bool                   `protobuf:"varint,111,opt,name=include_typein_lattoeng,json=includeTypeinLattoeng,proto3" json:"include_typein_lattoeng,omitempty"`                                                                  // p2p: {"alias": "include-typein-lattoeng"}
	IncludeParse                              bool                   `protobuf:"varint,112,opt,name=include_parse,json=includeParse,proto3" json:"include_parse,omitempty"`                                                                                               // p2p: {"alias": "include-parse"}
	IncludeInflect                            bool                   `protobuf:"varint,113,opt,name=include_inflect,json=includeInflect,proto3" json:"include_inflect,omitempty"`                                                                                         // p2p: {"alias": "include-inflect"}
	IncludePrincipalParts                     bool                   `protobuf:"varint,114,opt,name=include_principal_parts,json=includePrincipalParts,proto3" json:"include_principal_parts,omitempty"`                                                                  // p2p: {"alias": "include-principal-parts"}
	IncludeMultiplechoiceEngtolat             bool                   `protobuf:"varint,115,opt,name=include_multiplechoice_engtolat,json=includeMultiplechoiceEngtolat,proto3" json:"include_multiplechoice_engtolat,omitempty"`                                          // p2p: {"alias": "include-multiplechoice-engtolat"}
	IncludeMultiplechoiceLattoeng             bool                   `protobuf:"varint,116,opt,name=include_multiplechoice_lattoeng,json=includeMultiplechoiceLattoeng,proto3" json:"include_multiplechoice_lattoeng,omitempty"`                                          // p2p: {"alias": "include-multiplechoice-lattoeng"}
	NumberMultiplechoiceOptions               int32                  `protobuf:"varint,117,opt,name=number_multiplechoice_options,json=numberMultiplechoiceOptions,proto3" json:"number_multiplechoice_options,omitempty"`                                                // p2p: {"alias": "number-multiplechoice-options"}
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_vocab_tuister_v1_sessionconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_sessionconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_sessionconfig_proto_rawDescGZIP(), []int{0}
}

func (x *SessionConfig) GetExcludeAdjectives() bool {
	if x != nil {
		return x.ExcludeAdjectives
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjective_212Declension() bool {
	if x != nil {
		return x.ExcludeAdjective_212Declension
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveThirdDeclension() bool {
	if x != nil {
		return x.ExcludeAdjectiveThirdDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveMasculine() bool {
	if x != nil {
		return x.ExcludeAdjectiveMasculine
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveFeminine() bool {
	if x != nil {
		return x.ExcludeAdjectiveFeminine
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveNeuter() bool {
	if x != nil {
		return x.ExcludeAdjectiveNeuter
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveNominative() bool {
	if x != nil {
		return x.ExcludeAdjectiveNominative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveVocative() bool {
	if x != nil {
		return x.ExcludeAdjectiveVocative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveAccusative() bool {
	if x != nil {
		return x.ExcludeAdjectiveAccusative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveGenitive() bool {
	if x != nil {
		return x.ExcludeAdjectiveGenitive
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveDative() bool {
	if x != nil {
		return x.ExcludeAdjectiveDative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveAblative() bool {
	if x != nil {
		return x.ExcludeAdjectiveAblative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveSingular() bool {
	if x != nil {
		return x.ExcludeAdjectiveSingular
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectivePlural() bool {
	if x != nil {
		return x.ExcludeAdjectivePlural
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectivePositive() bool {
	if x != nil {
		return x.ExcludeAdjectivePositive
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveComparative() bool {
	if x != nil {
		return x.ExcludeAdjectiveComparative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdjectiveSuperlative() bool {
	if x != nil {
		return x.ExcludeAdjectiveSuperlative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdverbs() bool {
	if x != nil {
		return x.ExcludeAdverbs
	}
	return false
}

func (x *SessionConfig) GetExcludeAdverbPositive() bool {
	if x != nil {
		return x.ExcludeAdverbPositive
	}
	return false
}

func (x *SessionConfig) GetExcludeAdverbComparative() bool {
	if x != nil {
		return x.ExcludeAdverbComparative
	}
	return false
}

func (x *SessionConfig) GetExcludeAdverbSuperlative() bool {
	if x != nil {
		return x.ExcludeAdverbSuperlative
	}
	return false
}

func (x *SessionConfig) GetExcludeNouns() bool {
	if x != nil {
		return x.ExcludeNouns
	}
	return false
}

func (x *SessionConfig) GetExcludeNounFirstDeclension() bool {
	if x != nil {
		return x.ExcludeNounFirstDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeNounSecondDeclension() bool {
	if x != nil {
		return x.ExcludeNounSecondDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeNounThirdDeclension() bool {
	if x != nil {
		return x.ExcludeNounThirdDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeNounFourthDeclension() bool {
	if x != nil {
		return x.ExcludeNounFourthDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeNounFifthDeclension() bool {
	if x != nil {
		return x.ExcludeNounFifthDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeNounIrregularDeclension() bool {
	if x != nil {
		return x.ExcludeNounIrregularDeclension
	}
	return false
}

func (x *SessionConfig) GetExcludeNounNominative() bool {
	if x != nil {
		return x.ExcludeNounNominative
	}
	return false
}

func (x *SessionConfig) GetExcludeNounVocative() bool {
	if x != nil {
		return x.ExcludeNounVocative
	}
	return false
}

func (x *SessionConfig) GetExcludeNounAccusative() bool {
	if x != nil {
		return x.ExcludeNounAccusative
	}
	return false
}

func (x *SessionConfig) GetExcludeNounGenitive() bool {
	if x != nil {
		return x.ExcludeNounGenitive
	}
	return false
}

func (x *SessionConfig) GetExcludeNounDative() bool {
	if x != nil {
		return x.ExcludeNounDative
	}
	return false
}

func (x *SessionConfig) GetExcludeNounAblative() bool {
	if x != nil {
		return x.ExcludeNounAblative
	}
	return false
}

func (x *SessionConfig) GetExcludeNounSingular() bool {
	if x != nil {
		return x.ExcludeNounSingular
	}
	return false
}

func (x *SessionConfig) GetExcludeNounPlural() bool {
	if x != nil {
		return x.ExcludeNounPlural
	}
	return false
}

func (x *SessionConfig) GetExcludePronouns() bool {
	if x != nil {
		return x.ExcludePronouns
	}
	return false
}

func (x *SessionConfig) GetExcludePronounMasculine() bool {
	if x != nil {
		return x.ExcludePronounMasculine
	}
	return false
}

func (x *SessionConfig) GetExcludePronounFeminine() bool {
	if x != nil {
		return x.ExcludePronounFeminine
	}
	return false
}

func (x *SessionConfig) GetExcludePronounNeuter() bool {
	if x != nil {
		return x.ExcludePronounNeuter
	}
	return false
}

func (x *SessionConfig) GetExcludePronounNominative() bool {
	if x != nil {
		return x.ExcludePronounNominative
	}
	return false
}

func (x *SessionConfig) GetExcludePronounVocative() bool {
	if x != nil {
		return x.ExcludePronounVocative
	}
	return false
}

func (x *SessionConfig) GetExcludePronounAccusative() bool {
	if x != nil {
		return x.ExcludePronounAccusative
	}
	return false
}

func (x *SessionConfig) GetExcludePronounGenitive() bool {
	if x != nil {
		return x.ExcludePronounGenitive
	}
	return false
}

func (x *SessionConfig) GetExcludePronounDative() bool {
	if x != nil {
		return x.ExcludePronounDative
	}
	return false
}

func (x *SessionConfig) GetExcludePronounAblative() bool {
	if x != nil {
		return x.ExcludePronounAblative
	}
	return false
}

func (x *SessionConfig) GetExcludePronounSingular() bool {
	if x != nil {
		return x.ExcludePronounSingular
	}
	return false
}

func (x *SessionConfig) GetExcludePronounPlural() bool {
	if x != nil {
		return x.ExcludePronounPlural
	}
	return false
}

func (x *SessionConfig) GetExcludeRegulars() bool {
	if x != nil {
		return x.ExcludeRegulars
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbs() bool {
	if x != nil {
		return x.ExcludeVerbs
	}
	return false
}

func (x *SessionConfig) GetExcludeDeponents() bool {
	if x != nil {
		return x.ExcludeDeponents
	}
	return false
}

func (x *SessionConfig) GetExcludeSemiDeponents() bool {
	if x != nil {
		return x.ExcludeSemiDeponents
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFirstConjugation() bool {
	if x != nil {
		return x.ExcludeVerbFirstConjugation
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbSecondConjugation() bool {
	if x != nil {
		return x.ExcludeVerbSecondConjugation
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbThirdConjugation() bool {
	if x != nil {
		return x.ExcludeVerbThirdConjugation
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFourthConjugation() bool {
	if x != nil {
		return x.ExcludeVerbFourthConjugation
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbMixedConjugation() bool {
	if x != nil {
		return x.ExcludeVerbMixedConjugation
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbIrregularConjugation() bool {
	if x != nil {
		return x.ExcludeVerbIrregularConjugation
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentActiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbPresentActiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbImperfectActiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbImperfectActiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFutureActiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbFutureActiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPerfectActiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbPerfectActiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPluperfectActiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbPluperfectActiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFuturePerfectActiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbFuturePerfectActiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentPassiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbPresentPassiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbImperfectPassiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbImperfectPassiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFuturePassiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbFuturePassiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPerfectPassiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbPerfectPassiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPluperfectPassiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbPluperfectPassiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFuturePerfectPassiveIndicative() bool {
	if x != nil {
		return x.ExcludeVerbFuturePerfectPassiveIndicative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentActiveSubjunctive() bool {
	if x != nil {
		return x.ExcludeVerbPresentActiveSubjunctive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbImperfectActiveSubjunctive() bool {
	if x != nil {
		return x.ExcludeVerbImperfectActiveSubjunctive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPerfectActiveSubjunctive() bool {
	if x != nil {
		return x.ExcludeVerbPerfectActiveSubjunctive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPluperfectActiveSubjunctive() bool {
	if x != nil {
		return x.ExcludeVerbPluperfectActiveSubjunctive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentActiveImperative() bool {
	if x != nil {
		return x.ExcludeVerbPresentActiveImperative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFutureActiveImperative() bool {
	if x != nil {
		return x.ExcludeVerbFutureActiveImperative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentPassiveImperative() bool {
	if x != nil {
		return x.ExcludeVerbPresentPassiveImperative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFuturePassiveImperative() bool {
	if x != nil {
		return x.ExcludeVerbFuturePassiveImperative
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentActiveInfinitive() bool {
	if x != nil {
		return x.ExcludeVerbPresentActiveInfinitive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFutureActiveInfinitive() bool {
	if x != nil {
		return x.ExcludeVerbFutureActiveInfinitive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPerfectActiveInfinitive() bool {
	if x != nil {
		return x.ExcludeVerbPerfectActiveInfinitive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPresentPassiveInfinitive() bool {
	if x != nil {
		return x.ExcludeVerbPresentPassiveInfinitive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbFuturePassiveInfinitive() bool {
	if x != nil {
		return x.ExcludeVerbFuturePassiveInfinitive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPerfectPassiveInfinitive() bool {
	if x != nil {
		return x.ExcludeVerbPerfectPassiveInfinitive
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbSingular() bool {
	if x != nil {
		return x.ExcludeVerbSingular
	}
	return false
}

func (x *SessionConfig) GetExcludeVerbPlural() bool {
	if x != nil {
		return x.ExcludeVerbPlural
	}
	return false
}

func (x *SessionConfig) GetExcludeVerb_1StPerson() bool {
	if x != nil {
		return x.ExcludeVerb_1StPerson
	}
	return false
}

func (x *SessionConfig) GetExcludeVerb_2NdPerson() bool {
	if x != nil {
		return x.ExcludeVerb_2NdPerson
	}
	return false
}

func (x *SessionConfig) GetExcludeVerb_3RdPerson() bool {
	if x != nil {
		return x.ExcludeVerb_3RdPerson
	}
	return false
}

func (x *SessionConfig) GetExcludeParticiples() bool {
	if x != nil {
		return x.ExcludeParticiples
	}
	return false
}

func (x *SessionConfig) GetExcludeParticiplePresentActive() bool {
	if x != nil {
		return x.ExcludeParticiplePresentActive
	}
	return false
}

func (x *SessionConfig) GetExcludeParticiplePerfectPassive() bool {
	if x != nil {
		return x.ExcludeParticiplePerfectPassive
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleFutureActive() bool {
	if x != nil {
		return x.ExcludeParticipleFutureActive
	}
	return false
}

func (x *SessionConfig) GetExcludeGerundives() bool {
	if x != nil {
		return x.ExcludeGerundives
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleMasculine() bool {
	if x != nil {
		return x.ExcludeParticipleMasculine
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleFeminine() bool {
	if x != nil {
		return x.ExcludeParticipleFeminine
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleNeuter() bool {
	if x != nil {
		return x.ExcludeParticipleNeuter
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleNominative() bool {
	if x != nil {
		return x.ExcludeParticipleNominative
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleVocative() bool {
	if x != nil {
		return x.ExcludeParticipleVocative
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleAccusative() bool {
	if x != nil {
		return x.ExcludeParticipleAccusative
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleGenitive() bool {
	if x != nil {
		return x.ExcludeParticipleGenitive
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleDative() bool {
	if x != nil {
		return x.ExcludeParticipleDative
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleAblative() bool {
	if x != nil {
		return x.ExcludeParticipleAblative
	}
	return false
}

func (x *SessionConfig) GetExcludeParticipleSingular() bool {
	if x != nil {
		return x.ExcludeParticipleSingular
	}
	return false
}

func (x *SessionConfig) GetExcludeParticiplePlural() bool {
	if x != nil {
		return x.ExcludeParticiplePlural
	}
	return false
}

func (x *SessionConfig) GetExcludeGerunds() bool {
	if x != nil {
		return x.ExcludeGerunds
	}
	return false
}

func (x *SessionConfig) GetExcludeSupines() bool {
	if x != nil {
		return x.ExcludeSupines
	}
	return false
}

func (x *SessionConfig) GetEnglishSubjunctives() bool {
	if x != nil {
		return x.EnglishSubjunctives
	}
	return false
}

func (x *SessionConfig) GetEnglishVerbalNouns() bool {
	if x != nil {
		return x.EnglishVerbalNouns
	}
	return false
}

func (x *SessionConfig) GetIncludeTypeinEngtolat() bool {
	if x != nil {
		return x.IncludeTypeinEngtolat
	}
	return false
}

func (x *SessionConfig) GetIncludeTypeinLattoeng() bool {
	if x != nil {
		return x.IncludeTypeinLattoeng
	}
	return false
}

func (x *SessionConfig) GetIncludeParse() bool {
	if x != nil {
		return x.IncludeParse
	}
	return false
}

func (x *SessionConfig) GetIncludeInflect() bool {
	if x != nil {
		return x.IncludeInflect
	}
	return false
}

func (x *SessionConfig) GetIncludePrincipalParts() bool {
	if x != nil {
		return x.IncludePrincipalParts
	}
	return false
}

func (x *SessionConfig) GetIncludeMultiplechoiceEngtolat() bool {
	if x != nil {
		return x.IncludeMultiplechoiceEngtolat
	}
	return false
}

func (x *SessionConfig) GetIncludeMultiplechoiceLattoeng() bool {
	if x != nil {
		return x.IncludeMultiplechoiceLattoeng
	}
	return false
}

func (x *SessionConfig) GetNumberMultiplechoiceOptions() int32 {
	if x != nil {
		return x.NumberMultiplechoiceOptions
	}
	return 0
}

var File_vocab_tuister_v1_sessionconfig_proto protoreflect.FileDescriptor

const file_vocab_tuister_v1_sessionconfig_proto_rawDesc = "" +
	"\n" +
	"$vocab_tuister/v1/sessionconfig.proto\x12\x10vocab_tuister.v1\"\xe1;\n" +
	"\rSessionConfig\x12-\n" +
	"\x12exclude_adjectives\x18\x01 \x01(\bR\x11excludeAdjectives\x12G\n" +
	" exclude_adjective_212_declension\x18\x02 \x01(\bR\x1dexcludeAdjective212Declension\x12K\n" +
	"\"exclude_adjective_third_declension\x18\x03 \x01(\bR\x1fexcludeAdjectiveThirdDeclension\x12>\n" +
	"\x1bexclude_adjective_masculine\x18\x04 \x01(\bR\x19excludeAdjectiveMasculine\x12<\n" +
	"\x1aexclude_adjective_feminine\x18\x05 \x01(\bR\x18excludeAdjectiveFeminine\x128\n" +
	"\x18exclude_adjective_neuter\x18\x06 \x01(\bR\x16excludeAdjectiveNeuter\x12@\n" +
	"\x1cexclude_adjective_nominative\x18\a \x01(\bR\x1aexcludeAdjectiveNominative\x12<\n" +
	"\x1aexclude_adjective_vocative\x18\b \x01(\bR\x18excludeAdjectiveVocative\x12@\n" +
	"\x1cexclude_adjective_accusative\x18\t \x01(\bR\x1aexcludeAdjectiveAccusative\x12<\n" +
	"\x1aexclude_adjective_genitive\x18\n" +
	" \x01(\bR\x18excludeAdjectiveGenitive\x128\n" +
	"\x18exclude_adjective_dative\x18\v \x01(\bR\x16excludeAdjectiveDative\x12<\n" +
	"\x1aexclude_adjective_ablative\x18\f \x01(\bR\x18excludeAdjectiveAblative\x12<\n" +
	"\x1aexclude_adjective_singular\x18\r \x01(\bR\x18excludeAdjectiveSingular\x128\n" +
	"\x18exclude_adjective_plural\x18\x0e \x01(\bR\x16excludeAdjectivePlural\x12<\n" +
	"\x1aexclude_adjective_positive\x18\x0f \x01(\bR\x18excludeAdjectivePositive\x12B\n" +
	"\x1dexclude_adjective_comparative\x18\x10 \x01(\bR\x1bexcludeAdjectiveComparative\x12B\n" +
	"\x1dexclude_adjective_superlative\x18\x11 \x01(\bR\x1bexcludeAdjectiveSuperlative\x12'\n" +
	"\x0fexclude_adverbs\x18\x12 \x01(\bR\x0eexcludeAdverbs\x126\n" +
	"\x17exclude_adverb_positive\x18\x13 \x01(\bR\x15excludeAdverbPositive\x12<\n" +
	"\x1aexclude_adverb_comparative\x18\x14 \x01(\bR\x18excludeAdverbComparative\x12<\n" +
	"\x1aexclude_adverb_superlative\x18\x15 \x01(\bR\x18excludeAdverbSuperlative\x12#\n" +
	"\rexclude_nouns\x18\x16 \x01(\bR\fexcludeNouns\x12A\n" +
	"\x1dexclude_noun_first_declension\x18\x17 \x01(\bR\x1aexcludeNounFirstDeclension\x12C\n" +
	"\x1eexclude_noun_second_declension\x18\x18 \x01(\bR\x1bexcludeNounSecondDeclension\x12A\n" +
	"\x1dexclude_noun_third_declension\x18\x19 \x01(\bR\x1aexcludeNounThirdDeclension\x12C\n" +
	"\x1eexclude_noun_fourth_declension\x18\x1a \x01(\bR\x1bexcludeNounFourthDeclension\x12A\n" +
	"\x1dexclude_noun_fifth_declension\x18\x1b \x01(\bR\x1aexcludeNounFifthDeclension\x12I\n" +
	"!exclude_noun_irregular_declension\x18\x1c \x01(\bR\x1eexcludeNounIrregularDeclension\x126\n" +
	"\x17exclude_noun_nominative\x18\x1d \x01(\bR\x15excludeNounNominative\x122\n" +
	"\x15exclude_noun_vocative\x18\x1e \x01(\bR\x13excludeNounVocative\x126\n" +
	"\x17exclude_noun_accusative\x18\x1f \x01(\bR\x15excludeNounAccusative\x122\n" +
	"\x15exclude_noun_genitive\x18  \x01(\bR\x13excludeNounGenitive\x12.\n" +
	"\x13exclude_noun_dative\x18! \x01(\bR\x11excludeNounDative\x122\n" +
	"\x15exclude_noun_ablative\x18\" \x01(\bR\x13excludeNounAblative\x122\n" +
	"\x15exclude_noun_singular\x18# \x01(\bR\x13excludeNounSingular\x12.\n" +
	"\x13exclude_noun_plural\x18$ \x01(\bR\x11excludeNounPlural\x12)\n" +
	"\x10exclude_pronouns\x18% \x01(\bR\x0fexcludePronouns\x12:\n" +
	"\x19exclude_pronoun_masculine\x18& \x01(\bR\x17excludePronounMasculine\x128\n" +
	"\x18exclude_pronoun_feminine\x18' \x01(\bR\x16excludePronounFeminine\x124\n" +
	"\x16exclude_pronoun_neuter\x18( \x01(\bR\x14excludePronounNeuter\x12<\n" +
	"\x1aexclude_pronoun_nominative\x18) \x01(\bR\x18excludePronounNominative\x128\n" +
	"\x18exclude_pronoun_vocative\x18* \x01(\bR\x16excludePronounVocative\x12<\n" +
	"\x1aexclude_pronoun_accusative\x18+ \x01(\bR\x18excludePronounAccusative\x128\n" +
	"\x18exclude_pronoun_genitive\x18, \x01(\bR\x16excludePronounGenitive\x124\n" +
	"\x16exclude_pronoun_dative\x18- \x01(\bR\x14excludePronounDative\x128\n" +
	"\x18exclude_pronoun_ablative\x18. \x01(\bR\x16excludePronounAblative\x128\n" +
	"\x18exclude_pronoun_singular\x18/ \x01(\bR\x16excludePronounSingular\x124\n" +
	"\x16exclude_pronoun_plural\x180 \x01(\bR\x14excludePronounPlural\x12)\n" +
	"\x10exclude_regulars\x181 \x01(\bR\x0fexcludeRegulars\x12#\n" +
	"\rexclude_verbs\x182 \x01(\bR\fexcludeVerbs\x12+\n" +
	"\x11exclude_deponents\x183 \x01(\bR\x10excludeDeponents\x124\n" +
	"\x16exclude_semi_deponents\x184 \x01(\bR\x14excludeSemiDeponents\x12C\n" +
	"\x1eexclude_verb_first_conjugation\x185 \x01(\bR\x1bexcludeVerbFirstConjugation\x12E\n" +
	"\x1fexclude_verb_second_conjugation\x186 \x01(\bR\x1cexcludeVerbSecondConjugation\x12C\n" +
	"\x1eexclude_verb_third_conjugation\x187 \x01(\bR\x1bexcludeVerbThirdConjugation\x12E\n" +
	"\x1fexclude_verb_fourth_conjugation\x188 \x01(\bR\x1cexcludeVerbFourthConjugation\x12C\n" +
	"\x1eexclude_verb_mixed_conjugation\x189 \x01(\bR\x1bexcludeVerbMixedConjugation\x12K\n" +
	"\"exclude_verb_irregular_conjugation\x18: \x01(\bR\x1fexcludeVerbIrregularConjugation\x12R\n" +
	"&exclude_verb_present_active_indicative\x18; \x01(\bR\"excludeVerbPresentActiveIndicative\x12V\n" +
	"(exclude_verb_imperfect_active_indicative\x18< \x01(\bR$excludeVerbImperfectActiveIndicative\x12P\n" +
	"%exclude_verb_future_active_indicative\x18= \x01(\bR!excludeVerbFutureActiveIndicative\x12R\n" +
	"&exclude_verb_perfect_active_indicative\x18> \x01(\bR\"excludeVerbPerfectActiveIndicative\x12X\n" +
	")exclude_verb_pluperfect_active_indicative\x18? \x01(\bR%excludeVerbPluperfectActiveIndicative\x12_\n" +
	"-exclude_verb_future_perfect_active_indicative\x18@ \x01(\bR(excludeVerbFuturePerfectActiveIndicative\x12T\n" +
	"'exclude_verb_present_passive_indicative\x18A \x01(\bR#excludeVerbPresentPassiveIndicative\x12X\n" +
	")exclude_verb_imperfect_passive_indicative\x18B \x01(\bR%excludeVerbImperfectPassiveIndicative\x12R\n" +
	"&exclude_verb_future_passive_indicative\x18C \x01(\bR\"excludeVerbFuturePassiveIndicative\x12T\n" +
	"'exclude_verb_perfect_passive_indicative\x18D \x01(\bR#excludeVerbPerfectPassiveIndicative\x12Z\n" +
	"*exclude_verb_pluperfect_passive_indicative\x18E \x01(\bR&excludeVerbPluperfectPassiveIndicative\x12a\n" +
	".exclude_verb_future_perfect_passive_indicative\x18F \x01(\bR)excludeVerbFuturePerfectPassiveIndicative\x12T\n" +
	"'exclude_verb_present_active_subjunctive\x18G \x01(\bR#excludeVerbPresentActiveSubjunctive\x12X\n" +
	")exclude_verb_imperfect_active_subjunctive\x18H \x01(\bR%excludeVerbImperfectActiveSubjunctive\x12T\n" +
	"'exclude_verb_perfect_active_subjunctive\x18I \x01(\bR#excludeVerbPerfectActiveSubjunctive\x12Z\n" +
	"*exclude_verb_pluperfect_active_subjunctive\x18J \x01(\bR&excludeVerbPluperfectActiveSubjunctive\x12R\n" +
	"&exclude_verb_present_active_imperative\x18K \x01(\bR\"excludeVerbPresentActiveImperative\x12P\n" +
	"%exclude_verb_future_active_imperative\x18L \x01(\bR!excludeVerbFutureActiveImperative\x12T\n" +
	"'exclude_verb_present_passive_imperative\x18M \x01(\bR#excludeVerbPresentPassiveImperative\x12R\n" +
	"&exclude_verb_future_passive_imperative\x18N \x01(\bR\"excludeVerbFuturePassiveImperative\x12R\n" +
	"&exclude_verb_present_active_infinitive\x18O \x01(\bR\"excludeVerbPresentActiveInfinitive\x12P\n" +
	"%exclude_verb_future_active_infinitive\x18P \x01(\bR!excludeVerbFutureActiveInfinitive\x12R\n" +
	"&exclude_verb_perfect_active_infinitive\x18Q \x01(\bR\"excludeVerbPerfectActiveInfinitive\x12T\n" +
	"'exclude_verb_present_passive_infinitive\x18R \x01(\bR#excludeVerbPresentPassiveInfinitive\x12R\n" +
	"&exclude_verb_future_passive_infinitive\x18S \x01(\bR\"excludeVerbFuturePassiveInfinitive\x12T\n" +
	"'exclude_verb_perfect_passive_infinitive\x18T \x01(\bR#excludeVerbPerfectPassiveInfinitive\x122\n" +
	"\x15exclude_verb_singular\x18U \x01(\bR\x13excludeVerbSingular\x12.\n" +
	"\x13exclude_verb_plural\x18V \x01(\bR\x11excludeVerbPlural\x125\n" +
	"\x17exclude_verb_1st_person\x18W \x01(\bR\x14excludeVerb1stPerson\x125\n" +
	"\x17exclude_verb_2nd_person\x18X \x01(\bR\x14excludeVerb2ndPerson\x125\n" +
	"\x17exclude_verb_3rd_person\x18Y \x01(\bR\x14excludeVerb3rdPerson\x12/\n" +
	"\x13exclude_participles\x18Z \x01(\bR\x12excludeParticiples\x12I\n" +
	"!exclude_participle_present_active\x18[ \x01(\bR\x1eexcludeParticiplePresentActive\x12K\n" +
	"\"exclude_participle_perfect_passive\x18\\ \x01(\bR\x1fexcludeParticiplePerfectPassive\x12G\n" +
	" exclude_participle_future_active\x18] \x01(\bR\x1dexcludeParticipleFutureActive\x12-\n" +
	"\x12exclude_gerundives\x18^ \x01(\bR\x11excludeGerundives\x12@\n" +
	"\x1cexclude_participle_masculine\x18_ \x01(\bR\x1aexcludeParticipleMasculine\x12>\n" +
	"\x1bexclude_participle_feminine\x18` \x01(\bR\x19excludeParticipleFeminine\x12:\n" +
	"\x19exclude_participle_neuter\x18a \x01(\bR\x17excludeParticipleNeuter\x12B\n" +
	"\x1dexclude_participle_nominative\x18b \x01(\bR\x1bexcludeParticipleNominative\x12>\n" +
	"\x1bexclude_participle_vocative\x18c \x01(\bR\x19excludeParticipleVocative\x12B\n" +
	"\x1dexclude_participle_accusative\x18d \x01(\bR\x1bexcludeParticipleAccusative\x12>\n" +
	"\x1bexclude_participle_genitive\x18e \x01(\bR\x19excludeParticipleGenitive\x12:\n" +
	"\x19exclude_participle_dative\x18f \x01(\bR\x17excludeParticipleDative\x12>\n" +
	"\x1bexclude_participle_ablative\x18g \x01(\bR\x19excludeParticipleAblative\x12>\n" +
	"\x1bexclude_participle_singular\x18h \x01(\bR\x19excludeParticipleSingular\x12:\n" +
	"\x19exclude_participle_plural\x18i \x01(\bR\x17excludeParticiplePlural\x12'\n" +
	"\x0fexclude_gerunds\x18j \x01(\bR\x0eexcludeGerunds\x12'\n" +
	"\x0fexclude_supines\x18k \x01(\bR\x0eexcludeSupines\x121\n" +
	"\x14english_subjunctives\x18l \x01(\bR\x13englishSubjunctives\x120\n" +
	"\x14english_verbal_nouns\x18m \x01(\bR\x12englishVerbalNouns\x126\n" +
	"\x17include_typein_engtolat\x18n \x01(\bR\x15includeTypeinEngtolat\x126\n" +
	"\x17include_typein_lattoeng\x18o \x01(\bR\x15includeTypeinLattoeng\x12#\n" +
	"\rinclude_parse\x18p \x01(\bR\fincludeParse\x12'\n" +
	"\x0finclude_inflect\x18q \x01(\bR\x0eincludeInflect\x126\n" +
	"\x17include_principal_parts\x18r \x01(\bR\x15includePrincipalParts\x12F\n" +
	"\x1finclude_multiplechoice_engtolat\x18s \x01(\bR\x1dincludeMultiplechoiceEngtolat\x12F\n" +
	"\x1finclude_multiplechoice_lattoeng\x18t \x01(\bR\x1dincludeMultiplechoiceLattoeng\x12B\n" +
	"\x1dnumber_multiplechoice_options\x18u \x01(\x05R\x1bnumberMultiplechoiceOptionsB=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3"

var (
	file_vocab_tuister_v1_sessionconfig_proto_rawDescOnce sync.Once
	file_vocab_tuister_v1_sessionconfig_proto_rawDescData []byte
)

func file_vocab_tuister_v1_sessionconfig_proto_rawDescGZIP() []byte {
	file_vocab_tuister_v1_sessionconfig_proto_rawDescOnce.Do(func() {
		file_vocab_tuister_v1_sessionconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_sessionconfig_proto_rawDesc), len(file_vocab_tuister_v1_sessionconfig_proto_rawDesc)))
	})
	return file_vocab_tuister_v1_sessionconfig_proto_rawDescData
}

var file_vocab_tuister_v1_sessionconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vocab_tuister_v1_sessionconfig_proto_goTypes = []any{
	(*SessionConfig)(nil), // 0: vocab_tuister.v1.SessionConfig
}
var file_vocab_tuister_v1_sessionconfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vocab_tuister_v1_sessionconfig_proto_init() }
func file_vocab_tuister_v1_sessionconfig_proto_init() {
	if File_vocab_tuister_v1_sessionconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_sessionconfig_proto_rawDesc), len(file_vocab_tuister_v1_sessionconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vocab_tuister_v1_sessionconfig_proto_goTypes,
		DependencyIndexes: file_vocab_tuister_v1_sessionconfig_proto_depIdxs,
		MessageInfos:      file_vocab_tuister_v1_sessionconfig_proto_msgTypes,
	}.Build()
	File_vocab_tuister_v1_sessionconfig_proto = out.File
	file_vocab_tuister_v1_sessionconfig_proto_goTypes = nil
	file_vocab_tuister_v1_sessionconfig_proto_depIdxs = nil
}
