// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: vocab_tuister/v1/vocab_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VocabTesterService_VerifyVocab_FullMethodName   = "/vocab_tuister.v1.VocabTesterService/VerifyVocab"
	VocabTesterService_VerifyConfig_FullMethodName  = "/vocab_tuister.v1.VocabTesterService/VerifyConfig"
	VocabTesterService_CreateSession_FullMethodName = "/vocab_tuister.v1.VocabTesterService/CreateSession"
)

// VocabTesterServiceClient is the client API for VocabTesterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VocabTesterServiceClient interface {
	VerifyVocab(ctx context.Context, in *VerifyVocabRequest, opts ...grpc.CallOption) (*VerifyVocabResponse, error)
	VerifyConfig(ctx context.Context, in *VerifyConfigRequest, opts ...grpc.CallOption) (*VerifyConfigResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateSessionResponse], error)
}

type vocabTesterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVocabTesterServiceClient(cc grpc.ClientConnInterface) VocabTesterServiceClient {
	return &vocabTesterServiceClient{cc}
}

func (c *vocabTesterServiceClient) VerifyVocab(ctx context.Context, in *VerifyVocabRequest, opts ...grpc.CallOption) (*VerifyVocabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyVocabResponse)
	err := c.cc.Invoke(ctx, VocabTesterService_VerifyVocab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabTesterServiceClient) VerifyConfig(ctx context.Context, in *VerifyConfigRequest, opts ...grpc.CallOption) (*VerifyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyConfigResponse)
	err := c.cc.Invoke(ctx, VocabTesterService_VerifyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabTesterServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateSessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VocabTesterService_ServiceDesc.Streams[0], VocabTesterService_CreateSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateSessionRequest, CreateSessionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VocabTesterService_CreateSessionClient = grpc.ServerStreamingClient[CreateSessionResponse]

// VocabTesterServiceServer is the server API for VocabTesterService service.
// All implementations must embed UnimplementedVocabTesterServiceServer
// for forward compatibility.
type VocabTesterServiceServer interface {
	VerifyVocab(context.Context, *VerifyVocabRequest) (*VerifyVocabResponse, error)
	VerifyConfig(context.Context, *VerifyConfigRequest) (*VerifyConfigResponse, error)
	CreateSession(*CreateSessionRequest, grpc.ServerStreamingServer[CreateSessionResponse]) error
	mustEmbedUnimplementedVocabTesterServiceServer()
}

// UnimplementedVocabTesterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVocabTesterServiceServer struct{}

func (UnimplementedVocabTesterServiceServer) VerifyVocab(context.Context, *VerifyVocabRequest) (*VerifyVocabResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyVocab not implemented")
}
func (UnimplementedVocabTesterServiceServer) VerifyConfig(context.Context, *VerifyConfigRequest) (*VerifyConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyConfig not implemented")
}
func (UnimplementedVocabTesterServiceServer) CreateSession(*CreateSessionRequest, grpc.ServerStreamingServer[CreateSessionResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedVocabTesterServiceServer) mustEmbedUnimplementedVocabTesterServiceServer() {}
func (UnimplementedVocabTesterServiceServer) testEmbeddedByValue()                            {}

// UnsafeVocabTesterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VocabTesterServiceServer will
// result in compilation errors.
type UnsafeVocabTesterServiceServer interface {
	mustEmbedUnimplementedVocabTesterServiceServer()
}

func RegisterVocabTesterServiceServer(s grpc.ServiceRegistrar, srv VocabTesterServiceServer) {
	// If the following call panics, it indicates UnimplementedVocabTesterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VocabTesterService_ServiceDesc, srv)
}

func _VocabTesterService_VerifyVocab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyVocabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabTesterServiceServer).VerifyVocab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabTesterService_VerifyVocab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabTesterServiceServer).VerifyVocab(ctx, req.(*VerifyVocabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VocabTesterService_VerifyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabTesterServiceServer).VerifyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabTesterService_VerifyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabTesterServiceServer).VerifyConfig(ctx, req.(*VerifyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VocabTesterService_CreateSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateSessionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VocabTesterServiceServer).CreateSession(m, &grpc.GenericServerStream[CreateSessionRequest, CreateSessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VocabTesterService_CreateSessionServer = grpc.ServerStreamingServer[CreateSessionResponse]

// VocabTesterService_ServiceDesc is the grpc.ServiceDesc for VocabTesterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VocabTesterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vocab_tuister.v1.VocabTesterService",
	HandlerType: (*VocabTesterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyVocab",
			Handler:    _VocabTesterService_VerifyVocab_Handler,
		},
		{
			MethodName: "VerifyConfig",
			Handler:    _VocabTesterService_VerifyConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateSession",
			Handler:       _VocabTesterService_CreateSession_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vocab_tuister/v1/vocab_service.proto",
}
