// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vocab_tuister/v1/vocablist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VocabList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []string               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VocabList) Reset() {
	*x = VocabList{}
	mi := &file_vocab_tuister_v1_vocablist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VocabList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VocabList) ProtoMessage() {}

func (x *VocabList) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocablist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VocabList.ProtoReflect.Descriptor instead.
func (*VocabList) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocablist_proto_rawDescGZIP(), []int{0}
}

func (x *VocabList) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_vocab_tuister_v1_vocablist_proto protoreflect.FileDescriptor

const file_vocab_tuister_v1_vocablist_proto_rawDesc = "" +
	"\n" +
	" vocab_tuister/v1/vocablist.proto\x12\x10vocab_tuister.v1\"%\n" +
	"\tVocabList\x12\x18\n" +
	"\aentries\x18\x01 \x03(\tR\aentriesB=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3"

var (
	file_vocab_tuister_v1_vocablist_proto_rawDescOnce sync.Once
	file_vocab_tuister_v1_vocablist_proto_rawDescData []byte
)

func file_vocab_tuister_v1_vocablist_proto_rawDescGZIP() []byte {
	file_vocab_tuister_v1_vocablist_proto_rawDescOnce.Do(func() {
		file_vocab_tuister_v1_vocablist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_vocablist_proto_rawDesc), len(file_vocab_tuister_v1_vocablist_proto_rawDesc)))
	})
	return file_vocab_tuister_v1_vocablist_proto_rawDescData
}

var file_vocab_tuister_v1_vocablist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vocab_tuister_v1_vocablist_proto_goTypes = []any{
	(*VocabList)(nil), // 0: vocab_tuister.v1.VocabList
}
var file_vocab_tuister_v1_vocablist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vocab_tuister_v1_vocablist_proto_init() }
func file_vocab_tuister_v1_vocablist_proto_init() {
	if File_vocab_tuister_v1_vocablist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_vocablist_proto_rawDesc), len(file_vocab_tuister_v1_vocablist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vocab_tuister_v1_vocablist_proto_goTypes,
		DependencyIndexes: file_vocab_tuister_v1_vocablist_proto_depIdxs,
		MessageInfos:      file_vocab_tuister_v1_vocablist_proto_msgTypes,
	}.Build()
	File_vocab_tuister_v1_vocablist_proto = out.File
	file_vocab_tuister_v1_vocablist_proto_goTypes = nil
	file_vocab_tuister_v1_vocablist_proto_depIdxs = nil
}
