// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vocab_tuister/v1/vocab_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyVocabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VocabText     string                 `protobuf:"bytes,1,opt,name=vocab_text,json=vocabText,proto3" json:"vocab_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyVocabRequest) Reset() {
	*x = VerifyVocabRequest{}
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyVocabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyVocabRequest) ProtoMessage() {}

func (x *VerifyVocabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyVocabRequest.ProtoReflect.Descriptor instead.
func (*VerifyVocabRequest) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyVocabRequest) GetVocabText() string {
	if x != nil {
		return x.VocabText
	}
	return ""
}

type VerifyVocabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyVocabResponse) Reset() {
	*x = VerifyVocabResponse{}
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyVocabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyVocabResponse) ProtoMessage() {}

func (x *VerifyVocabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyVocabResponse.ProtoReflect.Descriptor instead.
func (*VerifyVocabResponse) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP(), []int{1}
}

type VerifyConfigRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NumberOfQuestions int32                  `protobuf:"varint,1,opt,name=number_of_questions,json=numberOfQuestions,proto3" json:"number_of_questions,omitempty"`
	SessionConfig     *SessionConfig         `protobuf:"bytes,2,opt,name=session_config,json=sessionConfig,proto3" json:"session_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyConfigRequest) Reset() {
	*x = VerifyConfigRequest{}
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConfigRequest) ProtoMessage() {}

func (x *VerifyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConfigRequest.ProtoReflect.Descriptor instead.
func (*VerifyConfigRequest) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyConfigRequest) GetNumberOfQuestions() int32 {
	if x != nil {
		return x.NumberOfQuestions
	}
	return 0
}

func (x *VerifyConfigRequest) GetSessionConfig() *SessionConfig {
	if x != nil {
		return x.SessionConfig
	}
	return nil
}

type VerifyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyConfigResponse) Reset() {
	*x = VerifyConfigResponse{}
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConfigResponse) ProtoMessage() {}

func (x *VerifyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConfigResponse.ProtoReflect.Descriptor instead.
func (*VerifyConfigResponse) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP(), []int{3}
}

type CreateSessionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VocabList         string                 `protobuf:"bytes,1,opt,name=vocab_list,json=vocabList,proto3" json:"vocab_list,omitempty"`
	NumberOfQuestions int32                  `protobuf:"varint,2,opt,name=number_of_questions,json=numberOfQuestions,proto3" json:"number_of_questions,omitempty"`
	SessionConfig     *SessionConfig         `protobuf:"bytes,3,opt,name=session_config,json=sessionConfig,proto3" json:"session_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetVocabList() string {
	if x != nil {
		return x.VocabList
	}
	return ""
}

func (x *CreateSessionRequest) GetNumberOfQuestions() int32 {
	if x != nil {
		return x.NumberOfQuestions
	}
	return 0
}

func (x *CreateSessionRequest) GetSessionConfig() *SessionConfig {
	if x != nil {
		return x.SessionConfig
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_tuister_v1_vocab_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

var File_vocab_tuister_v1_vocab_service_proto protoreflect.FileDescriptor

const file_vocab_tuister_v1_vocab_service_proto_rawDesc = "" +
	"\n" +
	"$vocab_tuister/v1/vocab_service.proto\x12\x10vocab_tuister.v1\x1a\x1fvocab_tuister/v1/question.proto\x1a$vocab_tuister/v1/sessionconfig.proto\"3\n" +
	"\x12VerifyVocabRequest\x12\x1d\n" +
	"\n" +
	"vocab_text\x18\x01 \x01(\tR\tvocabText\"\x15\n" +
	"\x13VerifyVocabResponse\"\x8d\x01\n" +
	"\x13VerifyConfigRequest\x12.\n" +
	"\x13number_of_questions\x18\x01 \x01(\x05R\x11numberOfQuestions\x12F\n" +
	"\x0esession_config\x18\x02 \x01(\v2\x1f.vocab_tuister.v1.SessionConfigR\rsessionConfig\"\x16\n" +
	"\x14VerifyConfigResponse\"\xad\x01\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"vocab_list\x18\x01 \x01(\tR\tvocabList\x12.\n" +
	"\x13number_of_questions\x18\x02 \x01(\x05R\x11numberOfQuestions\x12F\n" +
	"\x0esession_config\x18\x03 \x01(\v2\x1f.vocab_tuister.v1.SessionConfigR\rsessionConfig\"O\n" +
	"\x15CreateSessionResponse\x126\n" +
	"\bquestion\x18\x01 \x01(\v2\x1a.vocab_tuister.v1.QuestionR\bquestion2\xb3\x02\n" +
	"\x12VocabTesterService\x12Z\n" +
	"\vVerifyVocab\x12$.vocab_tuister.v1.VerifyVocabRequest\x1a%.vocab_tuister.v1.VerifyVocabResponse\x12]\n" +
	"\fVerifyConfig\x12%.vocab_tuister.v1.VerifyConfigRequest\x1a&.vocab_tuister.v1.VerifyConfigResponse\x12b\n" +
	"\rCreateSession\x12&.vocab_tuister.v1.CreateSessionRequest\x1a'.vocab_tuister.v1.CreateSessionResponse0\x01B=Z;github.com/rduo1009/vocab-tuister/src/client/internal/pb;pbb\x06proto3"

var (
	file_vocab_tuister_v1_vocab_service_proto_rawDescOnce sync.Once
	file_vocab_tuister_v1_vocab_service_proto_rawDescData []byte
)

func file_vocab_tuister_v1_vocab_service_proto_rawDescGZIP() []byte {
	file_vocab_tuister_v1_vocab_service_proto_rawDescOnce.Do(func() {
		file_vocab_tuister_v1_vocab_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_vocab_service_proto_rawDesc), len(file_vocab_tuister_v1_vocab_service_proto_rawDesc)))
	})
	return file_vocab_tuister_v1_vocab_service_proto_rawDescData
}

var file_vocab_tuister_v1_vocab_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vocab_tuister_v1_vocab_service_proto_goTypes = []any{
	(*VerifyVocabRequest)(nil),    // 0: vocab_tuister.v1.VerifyVocabRequest
	(*VerifyVocabResponse)(nil),   // 1: vocab_tuister.v1.VerifyVocabResponse
	(*VerifyConfigRequest)(nil),   // 2: vocab_tuister.v1.VerifyConfigRequest
	(*VerifyConfigResponse)(nil),  // 3: vocab_tuister.v1.VerifyConfigResponse
	(*CreateSessionRequest)(nil),  // 4: vocab_tuister.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 5: vocab_tuister.v1.CreateSessionResponse
	(*SessionConfig)(nil),         // 6: vocab_tuister.v1.SessionConfig
	(*Question)(nil),              // 7: vocab_tuister.v1.Question
}
var file_vocab_tuister_v1_vocab_service_proto_depIdxs = []int32{
	6, // 0: vocab_tuister.v1.VerifyConfigRequest.session_config:type_name -> vocab_tuister.v1.SessionConfig
	6, // 1: vocab_tuister.v1.CreateSessionRequest.session_config:type_name -> vocab_tuister.v1.SessionConfig
	7, // 2: vocab_tuister.v1.CreateSessionResponse.question:type_name -> vocab_tuister.v1.Question
	0, // 3: vocab_tuister.v1.VocabTesterService.VerifyVocab:input_type -> vocab_tuister.v1.VerifyVocabRequest
	2, // 4: vocab_tuister.v1.VocabTesterService.VerifyConfig:input_type -> vocab_tuister.v1.VerifyConfigRequest
	4, // 5: vocab_tuister.v1.VocabTesterService.CreateSession:input_type -> vocab_tuister.v1.CreateSessionRequest
	1, // 6: vocab_tuister.v1.VocabTesterService.VerifyVocab:output_type -> vocab_tuister.v1.VerifyVocabResponse
	3, // 7: vocab_tuister.v1.VocabTesterService.VerifyConfig:output_type -> vocab_tuister.v1.VerifyConfigResponse
	5, // 8: vocab_tuister.v1.VocabTesterService.CreateSession:output_type -> vocab_tuister.v1.CreateSessionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vocab_tuister_v1_vocab_service_proto_init() }
func file_vocab_tuister_v1_vocab_service_proto_init() {
	if File_vocab_tuister_v1_vocab_service_proto != nil {
		return
	}
	file_vocab_tuister_v1_question_proto_init()
	file_vocab_tuister_v1_sessionconfig_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_tuister_v1_vocab_service_proto_rawDesc), len(file_vocab_tuister_v1_vocab_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vocab_tuister_v1_vocab_service_proto_goTypes,
		DependencyIndexes: file_vocab_tuister_v1_vocab_service_proto_depIdxs,
		MessageInfos:      file_vocab_tuister_v1_vocab_service_proto_msgTypes,
	}.Build()
	File_vocab_tuister_v1_vocab_service_proto = out.File
	file_vocab_tuister_v1_vocab_service_proto_goTypes = nil
	file_vocab_tuister_v1_vocab_service_proto_depIdxs = nil
}
