package sessionconfig

//go:generate uv run ../../../../scripts/create_sessionconfig_json.py
//go:generate gojsonstruct --typename SessionConfig --package-name sessionconfig --file-header "// Code generated by gojsonstruct; DO NOT EDIT." -o sessionconfig.go ../../../../scripts/json_output/SessionConfig_sample.json
