"""Contains edge case endings."""

from __future__ import annotations

from typing import TYPE_CHECKING, Final

from .misc import MultipleEndings

if TYPE_CHECKING:
    from .type_aliases import Endings

# -----------------------------------------------------------------------------
# VERBS

# Taken from https://en.wiktionary.org/w/index.php?title=Category:Latin_verbs_with_missing_supine_stem
# Removals: accido (two meanings), incumbo (probably mistake)
MISSING_PPP_VERBS: Final[set[str]] = {
    "abaeto", "abago", "abarceo", "abbaeto", "abbatizo", "abbito", "abequito", "aberceo", "abhorresco", "abito", "abiturio",
    "abnato", "abnumero", "abnuto", "abolesco", "aboriscor", "aborto", "abrenuntio", "absilio", "absisto", "absono", "absto",
    "abstulo", "accano", "accersio", "accessito", "accieo", "accipitro", "accubo", "aceo", "acesco", "acetasco",
    "acontizo", "adaestuo", "adambulo", "adaugesco", "adbello", "adbito", "adcubo", "addecet", "addenseo", "addisco", "addormio",
    "addormisco", "aderro", "adesurio", "adfleo", "adformido", "adfremo", "adfrio", "adfulgeo", "adgemo", "adgravesco", "adiaceo",
    "adincresco", "adjaceo", "adlubesco", "adluceo", "adludio", "adluo", "admeo", "admigro", "admugio", "adnicto", "adnubilo",
    "adnullo", "adnuto", "adnutrio", "adoleo", "adolesco", "adpertineo", "adploro", "adpostulo", "adprenso", "adremigo", "adrepo",
    "adservio", "adsibilo", "adsido", "adsisto", "adsono", "adsto", "adstrepo", "adstupeo", "adtolero", "adtollo", "adtorqueo",
    "adurgeo", "advecto", "advesperascit", "advivo", "aegreo", "aegresco", "aerusco", "affleo", "afformido", "affremo", "affrio",
    "affugio", "affulgeo", "aiio", "aio", "albeo", "albesco", "albicasco", "alesco", "algeo", "algesco", "allegorizo", "alluceo",
    "alludio", "alluo", "alto", "amaresco", "ambigo", "amtruo", "amylo", "annicto", "anno", "annubilo", "annuto", "annutrio",
    "antecello", "antecurro", "antepolleo", "antesto", "antevio", "antisto", "apage", "aperto", "apolactizo", "apotheco",
    "apozymo", "apparesco", "appertineo", "apploro", "apposco", "appostulo", "apprenso", "apricor", "arboresco", "ardesco",
    "areo", "aresco", "arguto", "arrepo", "assenesco", "asservio", "assibilo", "assido", "assisto", "assono", "astituo", "asto",
    "astrepo", "astrifico", "astupeo", "attolero", "attollo", "attorqueo", "attorreo", "aufugio", "augesco", "augifico",
    "auresco", "auroresco", "auroro", "aurugino", "autumnascit", "autumnescit", "autumno", "aveo", "baeto", "balbutio", "barbio",
    "batto", "battuo", "batuo", "baulo", "bebo", "bellor", "beto", "blatio", "bombio", "bovinor", "bubo", "bubulcito", "bullesco",
    "cacaturio", "calefacto", "calesco", "calleo", "calveo", "calvor", "cambio", "candeo", "candesco", "candico", "candifico",
    "caneo", "canesco", "carro", "casso", "catulio", "caumo", "caurio", "caverno", "cedo", "celebresco", "cenaturio", "ceveo",
    "cineresco", "cio", "circito", "circumcurro", "circumcurso", "circumdoleo", "circumerro", "circumfulgeo", "circumgesto",
    "circumiaceo", "circumluceo", "circumluo", "circumpendeo", "circumsido", "circumsilio", "circumsisto", "circumsto",
    "circumstupeo", "circumtergeo", "circumtono", "circumtorqueo", "circumtueor", "circumvado", "circumverto", "circumvestio",
    "circumvorto", "clango", "clareo", "claresco", "claudeo", "clocito", "clueo", "clueor", "cluo", "coacesco", "coexsisto",
    "cohaeresco", "cohorresco", "collineo", "colliquesco", "colluceo", "commadeo", "commaneo", "commarceo", "commemini",
    "commeto", "commiseresco", "commitigo", "compalpo", "comparco", "compasco", "compendo", "comperco", "compesco", "compluit",
    "comprecor", "computresco", "concaleo", "concalesco", "concallesco", "concido", "concupio", "condecet", "condenseo",
    "condisco", "condoleo", "condolesco", "condormio", "condormisco", "conferveo", "confervesco", "confluo", "conforio",
    "confremo", "confulgeo", "congemo", "congruo", "coniveo", "conluceo", "conniveo", "conpesco", "conputresco", "conquinisco",
    "conresurgo", "conrideo", "consanesco", "consarrio", "consenesco", "consilesco", "consimilo", "consipio", "consono",
    "constupeo", "consuadeo", "contabesco", "contenebresco", "conticeo", "conticesco", "conticisco", "continor", "contollo",
    "contrasto", "contremesco", "contremisco", "contremo", "contumulo", "convaleo", "convecto", "convergo", "converro",
    "convescor", "conviso", "convomo", "convorro", "cornesco", "correpo", "corresurgo", "corrideo", "cratio", "crebesco",
    "crebresco", "crispio", "crocio", "crotolo", "crudesco", "cucio", "cucubo", "cucurio", "cunio", "cupisco", "cursito",
    "decet", "decido", "decumbo", "dedecet", "dedisco", "dedoleo", "deeo", "defervesco", "defloreo", "defloresco", "defugio",
    "dego", "degulo", "dehisco", "delambo", "deliquesco", "deliro", "delitesco", "delitisco", "delumbo", "demadesco", "demolio",
    "denarro", "denormo", "denseo", "dependeo", "deposco", "depropero", "depudet", "derepo", "derigeo", "derigesco", "deruo",
    "desenesco", "deserpo", "desideo", "desido", "desipio", "desorbeo", "despecto", "despuo", "destico", "desuesco", "desurgo",
    "devigesco", "dicturio", "diffingo", "diffiteor", "diluceo", "dilucesco", "diluculat", "disconvenio", "discupio", "dishiasco",
    "dispecto", "dispereo", "disquiro", "dissero", "disserpo", "dissideo", "dissono", "dissulto", "distaedet", "disto", "ditesco",
    "divergo", "dormisco", "drenso", "drindio", "drivoro", "dulcesco", "duplo", "duresco", "edisco", "edormisco", "eduro",
    "effervesco", "effervo", "effloreo", "effloresco", "effluo", "effulgeo", "elanguesco", "elatro", "elego", "eluceo",
    "elucesco", "elugeo", "emacresco", "emarcesco", "ematuresco", "emeto", "emineo", "emolo", "eniteo", "enitesco", "enotesco",
    "equio", "ercisco", "erubesco", "erudero", "escado", "eschado", "evalesco", "evanesco", "evilesco", "exacerbesco",
    "exalbesco", "exaresco", "excado", "excandesco", "excido", "excommunico", "exhorreo", "exhorresco", "exilio", "existo",
    "exolesco", "expallesco", "expaveo", "expavesco", "expectoro", "expetesso", "expetisso", "exposco", "exserto", "exsilio",
    "exsolesco", "exsono", "exsplendesco", "extabesco", "extimesco", "extollo", "exurgeo", "fabrio", "faeteo", "fatisco", "felio",
    "fervesco", "feteo", "fetesco", "fetifico", "fistulesco", "flacceo", "flaccesco", "flagro", "flaveo", "flavesco", "floreo",
    "floresco", "foeteo", "folleo", "forio", "formico", "fraceo", "fracesco", "fraglo", "fragro", "frendesco", "frigefacto",
    "frigeo", "frigesco", "frigutio", "fritinnio", "frondeo", "frondesco", "frugesco", "frutesco", "fulgeo", "fulgesco", "fulgo",
    "furo", "furvesco", "gannio", "gingrio", "glabresco", "glabro", "glattio", "glaucio", "glisco", "glocio", "gloctoro",
    "glottoro", "gracillo", "graduo", "grandesco", "grandinat", "gravesco", "hebeo", "hebesco", "herbesco", "hercisco", "hiasco",
    "hilaresco", "hinnio", "hirrio", "hisco", "hittio", "horior", "horreo", "horresco", "horripilo", "humeo", "ignesco",
    "illuceo", "illucesco", "imbibo", "immadesco", "immaneo", "immineo", "immurmuro", "impedico", "impendeo", "inacesco",
    "inaestuo", "inalbeo", "inalbesco", "inambulo", "inardesco", "inaresco", "incalesco", "incalfacio", "incandesco", "incanesco",
    "incino", "inclaresco", "incolo", "increbesco", "increbresco", "incresco", "inculpo", "incurvesco", "indecoro", 
    "indigeo", "indolesco", "induresco", "ineptio", "infenso", "infervesco", "infindo", "infit", "infremo", "infrendo",
    "ingemesco", "ingemisco", "ingravesco", "ingruo", "inhaeresco", "inhorreo", "inhorresco", "inluceo", "inlucesco", "inmaneo",
    "inmineo", "innotesco", "inoboedio", "inquilino", "insenesco", "inserto", "insisto", "insolesco", "insono", "instabilio",
    "instimulo", "instupeo", "intabesco", "intepeo", "intepesco", "interaresco", "interbito", "intercido", "interequito",
    "interfluo", "interfugio", "interfulgeo", "interiaceo", "interjaceo", "interluceo", "intermaneo", "internecto", "interniteo",
    "interquiesco", "intersono", "intersto", "intervolito", "intollo", "intremo", "intribuo", "intumesco", "inurgeo", "invalesco",
    "invergo", "invesperascit", "inveterasco", "ito", "iuvenesco", "labasco", "lacteo", "lactesco", "lallo", "lampo", "lanceo",
    "lancio", "langueo", "languesco", "lapidesco", "lassesco", "lateo", "latesco", "lentesco", "lipio", "liqueo", "liquesco",
    "liquor", "liveo", "livido", "longisco", "loretho", "luceo", "lucesco", "lucisco", "luo", "lutesco", "maceo", "maceresco",
    "macesco", "macresco", "madeo", "madesco", "maereo", "maledictito", "mammo", "marceo", "marcesco", "matresco", "maturesco",
    "maumo", "medeor", "mellifico", "memini", "miccio", "mico", "mintrio", "minurrio", "miseresco", "miseret", "mitesco",
    "mitilo", "moereo", "molio", "mollesco", "moror", "muceo", "mucesco", "murrio", "mutio", "muttio", "nauculor", "nausco",
    "naviculor", "nigreo", "nigresco", "ningit", "ningo", "ninguit", "ninguo", "niteo", "nitesco", "nivesco", "no", "noctesco",
    "nominito", "notesco", "nubilo", "nupturio", "obaresco", "obatresco", "obaudio", "obbrutesco", "obducto", "obdulcesco",
    "obduresco", "obfulgeo", "obhorreo", "obiaceo", "objaceo", "oblanguesco", "oblitesco", "obmordeo", "obmutesco", "obnoxio",
    "oboleo", "obrigesco", "obsido", "obsono", "obsordesco", "obstipesco", "obstupesco", "obsurdesco", "obtenebresco", "obtexo",
    "obticeo", "obticesco", "obtingo", "obtorpeo", "obtorpesco", "obtueor", "occallesco", "occino", "offulgeo", "oleo", "olesco",
    "olo", "onco", "oporteo", "oportet", "oppedo", "optingo", "oscitor", "paedagogo", "palleo", "pallesco", "palpebro", "pangito",
    "papo", "pappo", "parturio", "passito", "pateo", "patesco", "patio", "patrisso", "patrizo", "pauperasco", "paveo", "pavesco",
    "pelluceo", "pendeo", "percalleo", "percrebesco", "percrebresco", "perdisco", "perdo", "perdormisco", "perducto", "pereffluo",
    "perferveo", "perfugio", "perhorreo", "perhorresco", "perlateo", "perlinio", "perluceo", "permereo", "perniteo", "peroleo",
    "perpetuito", "perscisco", "persedeo", "perserpo", "persilio", "persisto", "pertimeo", "pertimesco", "pertineo", "pertingo",
    "pertorqueo", "perurgeo", "perurgueo", "pervaleo", "pervigeo", "petesso", "petisso", "pilpito", "pinguesco", "pipilo",
    "pipio", "pipo", "pisito", "plecto", "plipio", "pluit", "plumesco", "pluo", "polleo", "populo", "porceo", "posco", "posteo",
    "praeambulo", "praeemineo", "praefloreo", "praefluo", "praefugio", "praefulgeo", "praegestio", "praeiaceo", "praejaceo",
    "praeluceo", "praemando", "praeniteo", "praeoleo", "praependeo", "praepolleo", "praesagio", "praeservio", "praesipio",
    "praesono", "praeterfluo", "praeterfugio", "praetimeo", "praevalesco", "procello", "procido", "profugio", "proluceo",
    "promineo", "propalo", "prurio", "psallo", "pubesco", "pulpo", "purgito", "purpurasco", "puteo", "putesco", "putreo",
    "putresco", "quirrito", "rabio", "racco", "radicesco", "ranceo", "rancesco", "ranco", "ravio", "rebullio", "recaleo",
    "recommoneo", "recrepo", "recumbo", "redintegrasco", "redoleo", "redormio", "reducto", "refello", "refert", "referveo",
    "refingo", "refloreo", "refrigesco", "refugio", "refulgeo", "relanguesco", "reluceo", "rememini", "reminisco", "reminiscor",
    "remollesco", "remugio", "reneo", "renideo", "reniteo", "rennuo", "renuo", "reporrigo", "reposco", "resipisco", "resisto",
    "resplendeo", "resto", "reticeo", "retono", "revindico", "reviresco", "revivesco", "revivisco", "revivo", "ricio", "ricto",
    "rigeo", "rigesco", "rubeo", "rubesco", "rufesco", "rugio", "ruo", "sacio", "sagio", "salveo", "sanesco", "sanguino", "sapio",
    "sardo", "satago", "scabo", "scateo", "scato", "scaturio", "scaturrio", "scopo", "scripturio", "seneo", "senesco", "sentisco",
    "seresco", "sevio", "siccesco", "sicilio", "sido", "sileo", "silesco", "singultio", "soccito", "sordeo", "sordesco",
    "sospito", "splendeo", "splendesco", "spumesco", "squaleo", "stabulo", "sternuo", "sterto", "stinguo", "stipendio",
    "strideo", "strido", "stritto", "studeo", "stupeo", "stupesco", "subdoceo", "subedo", "subfulgeo", "subiaceo", "subjaceo",
    "subluceo", "suboleo", "subrubeo", "subservio", "subsilio", "subsisto", "subsono", "subterfluo", "subterfugio", "subteriaceo",
    "subterjaceo", "subtimeo", "suburgeo", "subvolo", "subvolvo", "succido", "succino", "succubo", "sufferveo", "suffringo",
    "suffugio", "suffulgeo", "sugglutio", "sullaturio", "superbio", "supercresco", "supereffluo", "superemineo", "superextollo",
    "superfluo", "superfugio", "superfulgeo", "superiaceo", "superimmineo", "superjaceo", "superluceo", "superobruo",
    "supersapio", "supersto", "supertraho", "supervaleo", "supervivo", "supo", "suppedo", "supterfugio", "surio", "sustollo",
    "tabeo", "tabesco", "temno", "tenebresco", "tenebrico", "tenerasco", "tepeo", "tepesco", "tetrinnio", "tibicino", "timeo",
    "tinnipo", "tintino", "tongeo", "torculo", "torpeo", "torpesco", "traluceo", "transfluo", "transfulgeo", "transilio",
    "transluceo", "transpicio", "transtineo", "transvado", "transvenio", "tremesco", "tremisco", "trico", "trittilo", "trucilo",
    "tumeo", "tumesco", "tumido", "turgeo", "turgesco", "tussio", "udo", "umbresco", "umeo", "umesco", "unco", "urco", "urgeo",
    "urgueo", "urvo", "vacefio", "vado", "vagio", "vago", "valesco", "vanesco", "vanno", "vegeo", "vento", "verecundor", "vergo",
    "vervago", "vesanio", "vescor", "vesico", "vesperascit", "veterasco", "veteresco", "vibrisso", "vigeo", "vigesco", "vilesco",
    "vireo", "viresco", "viridesco", "vissio", "vitulor", "vivesco",
}  # fmt: skip


# TODO: Expand these
MIXED_CONJUGATION_VERBS: Final[set[str]] = {
    "abicio",
    "adicio",
    "aggredior",
    "capio",
    "concutio",
    "confugio",
    "conicio",
    "cupio",
    "deicio",
    "diripio",
    "disicio",
    "effugio",
    "eicio",
    "eripio",
    "facio",
    "fugio",
    "gradior",
    "iacio",
    "illicio",
    "ingredior",
    "inicio",
    "mori",
    "obicio",
    "patior",
    "percutio",
    "perfugio",
    "profugio",
    "proicio",
    "quatere",
    "rapio",
    "refugio",
    "reicio",
    "sapio",
    "subicio",
    "traicio",
    "occipio",
}


def check_mixed_conjugation_verb(present: str) -> bool:
    """Check if the given word is a mixed conjugation verb.

    Parameters
    ----------
    present : str
        The present form verb to check.

    Returns
    -------
    bool
        If the prefix matches a mixed conjugation verb.
    """
    return any(
        present.endswith(io_verb) for io_verb in MIXED_CONJUGATION_VERBS
    )


# TODO: Expand these
IRREGULAR_VERBS: Final[dict[str, Endings]] = {
    "sum": {  # no passives
        "Vpreactindsg1": "sum",
        "Vpreactindsg2": "es",
        "Vpreactindsg3": "est",
        "Vpreactindpl1": "sumus",
        "Vpreactindpl2": "estis",
        "Vpreactindpl3": "sunt",
        "Vimpactindsg1": "eram",
        "Vimpactindsg2": "eras",
        "Vimpactindsg3": "erat",
        "Vimpactindpl1": "eramus",
        "Vimpactindpl2": "eratis",
        "Vimpactindpl3": "erant",
        "Vfutactindsg1": "ero",
        "Vfutactindsg2": "eris",
        "Vfutactindsg3": "erit",
        "Vfutactindpl1": "erimus",
        "Vfutactindpl2": "eritis",
        "Vfutactindpl3": "erunt",
        "Vperactindsg1": "fui",
        "Vperactindsg2": "fuisti",
        "Vperactindsg3": "fuit",
        "Vperactindpl1": "fuimus",
        "Vperactindpl2": "fuistis",
        "Vperactindpl3": "fuerunt",
        "Vplpactindsg1": "fueram",
        "Vplpactindsg2": "fueras",
        "Vplpactindsg3": "fuerat",
        "Vplpactindpl1": "fueramus",
        "Vplpactindpl2": "fueratis",
        "Vplpactindpl3": "fuerant",
        "Vfpractindsg1": "fuero",
        "Vfpractindsg2": "fueris",
        "Vfpractindsg3": "fuerit",
        "Vfpractindpl1": "fuerimus",
        "Vfpractindpl2": "fueritis",
        "Vfpractindpl3": "fuerint",
        "Vpreactinf   ": "esse",
        "Vpreactipesg2": "es",
        "Vpreactipepl2": "este",
        "Vimpactsbjsg1": "essem",
        "Vimpactsbjsg2": "esses",
        "Vimpactsbjsg3": "esset",
        "Vimpactsbjpl1": "essemus",
        "Vimpactsbjpl2": "essetis",
        "Vimpactsbjpl3": "essent",
        "Vplpactsbjsg1": "fuissem",
        "Vplpactsbjsg2": "fuisses",
        "Vplpactsbjsg3": "fuisset",
        "Vplpactsbjpl1": "fuissemus",
        "Vplpactsbjpl2": "fuissetis",
        "Vplpactsbjpl3": "fuissent",
    },
    "possum": {  # no imperatives, passives
        "Vpreactindsg1": "possum",
        "Vpreactindsg2": "potes",
        "Vpreactindsg3": "potest",
        "Vpreactindpl1": "possumus",
        "Vpreactindpl2": "potestis",
        "Vpreactindpl3": "possunt",
        "Vimpactindsg1": "poteram",
        "Vimpactindsg2": "poteras",
        "Vimpactindsg3": "poterat",
        "Vimpactindpl1": "poteramus",
        "Vimpactindpl2": "poteratis",
        "Vimpactindpl3": "poterant",
        "Vfutactindsg1": "potero",
        "Vfutactindsg2": "poteris",
        "Vfutactindsg3": "poterit",
        "Vfutactindpl1": "poterimus",
        "Vfutactindpl2": "poteritis",
        "Vfutactindpl3": "poterunt",
        "Vperactindsg1": "potui",
        "Vperactindsg2": "potuisti",
        "Vperactindsg3": "potuit",
        "Vperactindpl1": "potuimus",
        "Vperactindpl2": "potuistis",
        "Vperactindpl3": "potuerunt",
        "Vplpactindsg1": "potueram",
        "Vplpactindsg2": "potueras",
        "Vplpactindsg3": "potuerat",
        "Vplpactindpl1": "potueramus",
        "Vplpactindpl2": "potueratis",
        "Vplpactindpl3": "potuerant",
        "Vfpractindsg1": "potuero",
        "Vfpractindsg2": "potueris",
        "Vfpractindsg3": "potuerit",
        "Vfpractindpl1": "potuerimus",
        "Vfpractindpl2": "potueritis",
        "Vfpractindpl3": "potuerint",
        "Vpreactinf   ": "posse",
        "Vimpactsbjsg1": "possem",
        "Vimpactsbjsg2": "posses",
        "Vimpactsbjsg3": "posset",
        "Vimpactsbjpl1": "possemus",
        "Vimpactsbjpl2": "possetis",
        "Vimpactsbjpl3": "possent",
        "Vplpactsbjsg1": "potuissem",
        "Vplpactsbjsg2": "potuisses",
        "Vplpactsbjsg3": "potuisset",
        "Vplpactsbjpl1": "potuissemus",
        "Vplpactsbjpl2": "potuissetis",
        "Vplpactsbjpl3": "potuissent",
    },
    "volo": {  # no imperatives, passives
        "Vpreactindsg1": "volo",
        "Vpreactindsg2": "vis",
        "Vpreactindsg3": "vult",
        "Vpreactindpl1": "volumus",
        "Vpreactindpl2": "vultis",
        "Vpreactindpl3": "volunt",
        "Vimpactindsg1": "volebam",
        "Vimpactindsg2": "volebas",
        "Vimpactindsg3": "volebat",
        "Vimpactindpl1": "volebamus",
        "Vimpactindpl2": "volebatis",
        "Vimpactindpl3": "volebant",
        "Vfutactindsg1": "volam",
        "Vfutactindsg2": "voles",
        "Vfutactindsg3": "volet",
        "Vfutactindpl1": "volemus",
        "Vfutactindpl2": "voletis",
        "Vfutactindpl3": "volent",
        "Vperactindsg1": "volui",
        "Vperactindsg2": "voluisti",
        "Vperactindsg3": "voluit",
        "Vperactindpl1": "voluimus",
        "Vperactindpl2": "voluistis",
        "Vperactindpl3": "voluerunt",
        "Vplpactindsg1": "volueram",
        "Vplpactindsg2": "volueras",
        "Vplpactindsg3": "voluerat",
        "Vplpactindpl1": "volueramus",
        "Vplpactindpl2": "volueratis",
        "Vplpactindpl3": "voluerant",
        "Vfpractindsg1": "voluero",
        "Vfpractindsg2": "volueris",
        "Vfpractindsg3": "voluerit",
        "Vfpractindpl1": "voluerimus",
        "Vfpractindpl2": "volueritis",
        "Vfpractindpl3": "voluerint",
        "Vpreactinf   ": "velle",
        "Vimpactsbjsg1": "vellem",
        "Vimpactsbjsg2": "velles",
        "Vimpactsbjsg3": "vellet",
        "Vimpactsbjpl1": "vellemus",
        "Vimpactsbjpl2": "velletis",
        "Vimpactsbjpl3": "vellent",
        "Vplpactsbjsg1": "voluissem",
        "Vplpactsbjsg2": "voluisses",
        "Vplpactsbjsg3": "voluisset",
        "Vplpactsbjpl1": "voluissemus",
        "Vplpactsbjpl2": "voluissetis",
        "Vplpactsbjpl3": "voluissent",
    },
    "nolo": {  # no imperatives, passives
        "Vpreactindsg1": "nolo",
        "Vpreactindsg2": "non vis",
        "Vpreactindsg3": "non vult",
        "Vpreactindpl1": "nolumus",
        "Vpreactindpl2": "non vultis",
        "Vpreactindpl3": "nolunt",
        "Vimpactindsg1": "nolebam",
        "Vimpactindsg2": "nolebas",
        "Vimpactindsg3": "nolebat",
        "Vimpactindpl1": "nolebamus",
        "Vimpactindpl2": "nolebatis",
        "Vimpactindpl3": "nolebant",
        "Vfutactindsg1": "nolam",
        "Vfutactindsg2": "noles",
        "Vfutactindsg3": "nolet",
        "Vfutactindpl1": "nolemus",
        "Vfutactindpl2": "noletis",
        "Vfutactindpl3": "nolent",
        "Vperactindsg1": "nolui",
        "Vperactindsg2": "noluisti",
        "Vperactindsg3": "noluit",
        "Vperactindpl1": "noluimus",
        "Vperactindpl2": "noluistis",
        "Vperactindpl3": "noluerunt",
        "Vplpactindsg1": "nolueram",
        "Vplpactindsg2": "nolueras",
        "Vplpactindsg3": "noluerat",
        "Vplpactindpl1": "nolueramus",
        "Vplpactindpl2": "nolueratis",
        "Vplpactindpl3": "noluerant",
        "Vfpractindsg1": "noluero",
        "Vfpractindsg2": "nolueris",
        "Vfpractindsg3": "noluerit",
        "Vfpractindpl1": "noluerimus",
        "Vfpractindpl2": "nolueritis",
        "Vfpractindpl3": "noluerint",
        "Vpreactinf   ": "nolle",
        "Vimpactsbjsg1": "nollem",
        "Vimpactsbjsg2": "nolles",
        "Vimpactsbjsg3": "nollet",
        "Vimpactsbjpl1": "nollemus",
        "Vimpactsbjpl2": "nolletis",
        "Vimpactsbjpl3": "nollent",
        "Vplpactsbjsg1": "noluissem",
        "Vplpactsbjsg2": "noluisses",
        "Vplpactsbjsg3": "noluisset",
        "Vplpactsbjpl1": "noluissemus",
        "Vplpactsbjpl2": "noluissetis",
        "Vplpactsbjpl3": "noluissent",
    },
    "fero": {
        "Vpreactindsg1": "fero",
        "Vpreactindsg2": "fers",
        "Vpreactindsg3": "fert",
        "Vpreactindpl1": "ferimus",
        "Vpreactindpl2": "fertis",
        "Vpreactindpl3": "ferunt",
        "Vimpactindsg1": "ferebam",
        "Vimpactindsg2": "ferebas",
        "Vimpactindsg3": "ferebat",
        "Vimpactindpl1": "ferebamus",
        "Vimpactindpl2": "ferebatis",
        "Vimpactindpl3": "ferebant",
        "Vfutactindsg1": "feram",
        "Vfutactindsg2": "feres",
        "Vfutactindsg3": "feret",
        "Vfutactindpl1": "feremus",
        "Vfutactindpl2": "feretis",
        "Vfutactindpl3": "ferent",
        "Vperactindsg1": "tuli",
        "Vperactindsg2": "tulisti",
        "Vperactindsg3": "tulit",
        "Vperactindpl1": "tulimus",
        "Vperactindpl2": "tulistis",
        "Vperactindpl3": "tulerunt",
        "Vplpactindsg1": "tuleram",
        "Vplpactindsg2": "tuleras",
        "Vplpactindsg3": "tulerat",
        "Vplpactindpl1": "tuleramus",
        "Vplpactindpl2": "tuleratis",
        "Vplpactindpl3": "tulerant",
        "Vfpractindsg1": "tulero",
        "Vfpractindsg2": "tuleris",
        "Vfpractindsg3": "tulerit",
        "Vfpractindpl1": "tulerimus",
        "Vfpractindpl2": "tuleritis",
        "Vfpractindpl3": "tulerint",
        "Vprepasindsg1": "feror",
        "Vprepasindsg2": "ferris",
        "Vprepasindsg3": "fertur",
        "Vprepasindpl1": "ferimur",
        "Vprepasindpl2": "ferimini",
        "Vprepasindpl3": "feruntur",
        "Vimppasindsg1": "ferebar",
        "Vimppasindsg2": "ferebaris",
        "Vimppasindsg3": "ferebatur",
        "Vimppasindpl1": "ferebamur",
        "Vimppasindpl2": "ferebamini",
        "Vimppasindpl3": "ferebantur",
        "Vfutpasindsg1": "ferar",
        "Vfutpasindsg2": "fereris",
        "Vfutpasindsg3": "feretur",
        "Vfutpasindpl1": "feremur",
        "Vfutpasindpl2": "feremini",
        "Vfutpasindpl3": "ferentur",
        "Vperpasindsg1": "latus sum",
        "Vperpasindsg2": "latus es",
        "Vperpasindsg3": "latus est",
        "Vperpasindpl1": "lati sumus",
        "Vperpasindpl2": "lati estis",
        "Vperpasindpl3": "lati sunt",
        "Vplppasindsg1": "latus eram",
        "Vplppasindsg2": "latus eras",
        "Vplppasindsg3": "latus erat",
        "Vplppasindpl1": "lati eramus",
        "Vplppasindpl2": "lati eratis",
        "Vplppasindpl3": "lati erant",
        "Vfprpasindsg1": "latus ero",
        "Vfprpasindsg2": "latus eris",
        "Vfprpasindsg3": "latus erit",
        "Vfprpasindpl1": "lati erimus",
        "Vfprpasindpl2": "lati eritis",
        "Vfprpasindpl3": "lati erunt",
        "Vpreactinf   ": "ferre",
        "Vprepasinf   ": "ferri",
        "Vpreactipesg2": "fer",
        "Vpreactipepl2": "ferte",
        "Vimpactsbjsg1": "ferrem",
        "Vimpactsbjsg2": "ferres",
        "Vimpactsbjsg3": "ferret",
        "Vimpactsbjpl1": "ferremus",
        "Vimpactsbjpl2": "ferretis",
        "Vimpactsbjpl3": "ferrent",
        "Vplpactsbjsg1": "tulissem",
        "Vplpactsbjsg2": "tulisses",
        "Vplpactsbjsg3": "tulisset",
        "Vplpactsbjpl1": "tulissemus",
        "Vplpactsbjpl2": "tulissetis",
        "Vplpactsbjpl3": "tulissent",
    },
    "eo": {
        "Vpreactindsg1": "eo",
        "Vpreactindsg2": "is",
        "Vpreactindsg3": "it",
        "Vpreactindpl1": "imus",
        "Vpreactindpl2": "itis",
        "Vpreactindpl3": "eunt",
        "Vimpactindsg1": "ibam",
        "Vimpactindsg2": "ibas",
        "Vimpactindsg3": "ibat",
        "Vimpactindpl1": "ibamus",
        "Vimpactindpl2": "ibatis",
        "Vimpactindpl3": "ibant",
        "Vfutactindsg1": "ibo",
        "Vfutactindsg2": "ibis",
        "Vfutactindsg3": "ibit",
        "Vfutactindpl1": "ibimus",
        "Vfutactindpl2": "ibitis",
        "Vfutactindpl3": "ibunt",
        "Vperactindsg1": "ii",
        "Vperactindsg2": "iisti",
        "Vperactindsg3": "iit",
        "Vperactindpl1": "iimus",
        "Vperactindpl2": "iistis",
        "Vperactindpl3": "ierunt",
        "Vplpactindsg1": "ieram",
        "Vplpactindsg2": "ieras",
        "Vplpactindsg3": "ierat",
        "Vplpactindpl1": "ieramus",
        "Vplpactindpl2": "ieratis",
        "Vplpactindpl3": "ierant",
        "Vfpractindsg1": "iero",
        "Vfpractindsg2": "ieris",
        "Vfpractindsg3": "ierit",
        "Vfpractindpl1": "ierimus",
        "Vfpractindpl2": "ieritis",
        "Vfpractindpl3": "ierint",
        "Vprepasindsg1": "eor",
        "Vprepasindsg2": "iris",
        "Vprepasindsg3": "itur",
        "Vprepasindpl1": "imur",
        "Vprepasindpl2": "imini",
        "Vprepasindpl3": "euntur",
        "Vimppasindsg1": "ibar",
        "Vimppasindsg2": "ibaris",
        "Vimppasindsg3": "ibatur",
        "Vimppasindpl1": "ibamur",
        "Vimppasindpl2": "ibamini",
        "Vimppasindpl3": "ibantur",
        "Vfutpasindsg1": "ibor",
        "Vfutpasindsg2": "iberis",
        "Vfutpasindsg3": "ibitur",
        "Vfutpasindpl1": "ibimur",
        "Vfutpasindpl2": "ibimini",
        "Vfutpasindpl3": "ibuntur",
        "Vperpasindsg1": "itus sum",
        "Vperpasindsg2": "itus es",
        "Vperpasindsg3": "itus est",
        "Vperpasindpl1": "iti sumus",
        "Vperpasindpl2": "iti estis",
        "Vperpasindpl3": "iti sunt",
        "Vplppasindsg1": "itus eram",
        "Vplppasindsg2": "itus eras",
        "Vplppasindsg3": "itus erat",
        "Vplppasindpl1": "iti eramus",
        "Vplppasindpl2": "iti eratis",
        "Vplppasindpl3": "iti erant",
        "Vfprpasindsg1": "itus ero",
        "Vfprpasindsg2": "itus eris",
        "Vfprpasindsg3": "itus erit",
        "Vfprpasindpl1": "iti erimus",
        "Vfprpasindpl2": "iti eritis",
        "Vfprpasindpl3": "iti erunt",
        "Vpreactinf   ": "ire",
        "Vprepasinf   ": "iri",
        "Vpreactipesg2": "i",
        "Vpreactipepl2": "ite",
        "Vimpactsbjsg1": "irem",
        "Vimpactsbjsg2": "ires",
        "Vimpactsbjsg3": "iret",
        "Vimpactsbjpl1": "iremus",
        "Vimpactsbjpl2": "iretis",
        "Vimpactsbjpl3": "irent",
        "Vplpactsbjsg1": "iissem",
        "Vplpactsbjsg2": "iisses",
        "Vplpactsbjsg3": "iisset",
        "Vplpactsbjpl1": "iissemus",
        "Vplpactsbjpl2": "iissetis",
        "Vplpactsbjpl3": "iissent",
    },
    "absum": {  # no imperatives, passives
        "Vpreactindsg1": "absum",
        "Vpreactindsg2": "abes",
        "Vpreactindsg3": "abest",
        "Vpreactindpl1": "absumus",
        "Vpreactindpl2": "abestis",
        "Vpreactindpl3": "absunt",
        "Vimpactindsg1": "aberam",
        "Vimpactindsg2": "aberas",
        "Vimpactindsg3": "aberat",
        "Vimpactindpl1": "aberamus",
        "Vimpactindpl2": "aberatis",
        "Vimpactindpl3": "aberant",
        "Vfutactindsg1": "abero",
        "Vfutactindsg2": "aberis",
        "Vfutactindsg3": "aberit",
        "Vfutactindpl1": "aberimus",
        "Vfutactindpl2": "aberitis",
        "Vfutactindpl3": "aberunt",
        "Vperactindsg1": "afui",
        "Vperactindsg2": "afuisti",
        "Vperactindsg3": "afuit",
        "Vperactindpl1": "afuimus",
        "Vperactindpl2": "afuistis",
        "Vperactindpl3": "afuerunt",
        "Vplpactindsg1": "afueram",
        "Vplpactindsg2": "afueras",
        "Vplpactindsg3": "afuerat",
        "Vplpactindpl1": "afueramus",
        "Vplpactindpl2": "afueratis",
        "Vplpactindpl3": "afuerant",
        "Vfpractindsg1": "afuero",
        "Vfpractindsg2": "afueris",
        "Vfpractindsg3": "afuerit",
        "Vfpractindpl1": "afuerimus",
        "Vfpractindpl2": "afueritis",
        "Vfpractindpl3": "afuerint",
        "Vpreactinf   ": "abesse",
        "Vimpactsbjsg1": "abessem",
        "Vimpactsbjsg2": "abesses",
        "Vimpactsbjsg3": "abesset",
        "Vimpactsbjpl1": "abessemus",
        "Vimpactsbjpl2": "abessetis",
        "Vimpactsbjpl3": "abessent",
        "Vplpactsbjsg1": "afuissem",
        "Vplpactsbjsg2": "afuisses",
        "Vplpactsbjsg3": "afuisset",
        "Vplpactsbjpl1": "afuissemus",
        "Vplpactsbjpl2": "afuissetis",
        "Vplpactsbjpl3": "afuissent",
    },
    "adsum": {  # no imperatives, passives
        "Vpreactindsg1": "adsum",
        "Vpreactindsg2": "ades",
        "Vpreactindsg3": "adest",
        "Vpreactindpl1": "adsumus",
        "Vpreactindpl2": "adestis",
        "Vpreactindpl3": "adsunt",
        "Vimpactindsg1": "aderam",
        "Vimpactindsg2": "aderas",
        "Vimpactindsg3": "aderat",
        "Vimpactindpl1": "aderamus",
        "Vimpactindpl2": "aderatis",
        "Vimpactindpl3": "aderant",
        "Vfutactindsg1": "adero",
        "Vfutactindsg2": "aderis",
        "Vfutactindsg3": "aderit",
        "Vfutactindpl1": "aderimus",
        "Vfutactindpl2": "aderitis",
        "Vfutactindpl3": "aderunt",
        "Vperactindsg1": "adfui",
        "Vperactindsg2": "adfuisti",
        "Vperactindsg3": "adfuit",
        "Vperactindpl1": "adfuimus",
        "Vperactindpl2": "adfuistis",
        "Vperactindpl3": "adfuerunt",
        "Vplpactindsg1": "adfueram",
        "Vplpactindsg2": "adfueras",
        "Vplpactindsg3": "adfuerat",
        "Vplpactindpl1": "adfueramus",
        "Vplpactindpl2": "adfueratis",
        "Vplpactindpl3": "adfuerant",
        "Vfpractindsg1": "adfuero",
        "Vfpractindsg2": "adfueris",
        "Vfpractindsg3": "adfuerit",
        "Vfpractindpl1": "adfuerimus",
        "Vfpractindpl2": "adfueritis",
        "Vfpractindpl3": "adfuerint",
        "Vpreactinf   ": "adesse",
        "Vimpactsbjsg1": "adessem",
        "Vimpactsbjsg2": "adesses",
        "Vimpactsbjsg3": "adesset",
        "Vimpactsbjpl1": "adessemus",
        "Vimpactsbjpl2": "adessetis",
        "Vimpactsbjpl3": "adessent",
        "Vplpactsbjsg1": "adfuissem",
        "Vplpactsbjsg2": "adfuisses",
        "Vplpactsbjsg3": "adfuisset",
        "Vplpactsbjpl1": "adfuissemus",
        "Vplpactsbjpl2": "adfuissetis",
        "Vplpactsbjpl3": "adfuissent",
    },
    "inquam": {  # defective conjugation
        "Vpreactindsg1": "inquam",
        "Vpreactindsg2": "inquis",
        "Vpreactindsg3": "inquit",
        "Vpreactindpl1": "inquimus",
        "Vpreactindpl2": "inquitis",
        "Vpreactindpl3": "inquint",
        "Vimpactindsg3": "inquiebat",
        "Vfutactindsg2": "inquies",
        "Vfutactindsg3": "inquiet",
        "Vperactindsg1": "inquii",
        "Vperactindsg2": "inquisti",
        "Vperactindsg3": "inquit",
        "Vpreactipesg2": "inque",
    },
}


# Contains verbs that are derived from the main irregular verbs (usually
# having a prefix)
DERIVED_IRREGULAR_VERBS: Final[dict[str, set[str]]] = {
    "eo": {
        "abeo",
        "adeo",
        "ambeo",
        "circumeo",
        "coeo",
        "deeo",
        "dispereo",
        "exeo",
        "ineo",
        "intereo",
        "introeo",
        "nequeo",
        "obeo",
        "pereo",
        "praetereo",
        "prodeo",
        "queo",
        "redeo",
        "subeo",
        "transabeo",
        "transeo",
        "veneo",
    },
    "fero": {
        "affero",
        "aufero",
        "circumfero",
        "confero",
        "defero",
        "differo",
        "effero",
        "infero",
        "interfero",
        "introfero",
        "offero",
        "perfero",
        "postfero",
        "praefero",
        "profero",
        "refero",
        "suffero",
        "transfero",
    },
}


# NOTE: This entire thing will probably need to be reworked at some point
# Notably allowing the given perfect stem to be used so that I don't have
# to write everything manually
# FIXME: Complete above as the current system is actually causing bugs
DERIVED_IRREGULAR_ENDINGS: Final[dict[str, Endings]] = {
    "eo": {
        "Vpreactindsg1": "eo",
        "Vpreactindsg2": "is",
        "Vpreactindsg3": "it",
        "Vpreactindpl1": "imus",
        "Vpreactindpl2": "itis",
        "Vpreactindpl3": "eunt",
        "Vimpactindsg1": "ibam",
        "Vimpactindsg2": "ibas",
        "Vimpactindsg3": "ibat",
        "Vimpactindpl1": "ibamus",
        "Vimpactindpl2": "ibatis",
        "Vimpactindpl3": "ibant",
        "Vfutactindsg1": "ibo",
        "Vfutactindsg2": "ibis",
        "Vfutactindsg3": "ibit",
        "Vfutactindpl1": "ibimus",
        "Vfutactindpl2": "ibitis",
        "Vfutactindpl3": "ibunt",
        "Vperactindsg1": "ii",
        "Vperactindsg2": "isti",
        "Vperactindsg3": "iit",
        "Vperactindpl1": "iimus",
        "Vperactindpl2": "istis",
        "Vperactindpl3": "ierunt",
        "Vplpactindsg1": "ieram",
        "Vplpactindsg2": "ieras",
        "Vplpactindsg3": "ierat",
        "Vplpactindpl1": "ieramus",
        "Vplpactindpl2": "ieratis",
        "Vplpactindpl3": "ierant",
        "Vfpractindsg1": "iero",
        "Vfpractindsg2": "ieris",
        "Vfpractindsg3": "ierit",
        "Vfpractindpl1": "ierimus",
        "Vfpractindpl2": "ieritis",
        "Vfpractindpl3": "ierint",
        "Vprepasindsg1": "eor",
        "Vprepasindsg2": "iris",
        "Vprepasindsg3": "itur",
        "Vprepasindpl1": "imur",
        "Vprepasindpl2": "imini",
        "Vprepasindpl3": "euntur",
        "Vimppasindsg1": "ibar",
        "Vimppasindsg2": "ibaris",
        "Vimppasindsg3": "ibatur",
        "Vimppasindpl1": "ibamur",
        "Vimppasindpl2": "ibamini",
        "Vimppasindpl3": "ibantur",
        "Vfutpasindsg1": "ibor",
        "Vfutpasindsg2": "iberis",
        "Vfutpasindsg3": "ibitur",
        "Vfutpasindpl1": "ibimur",
        "Vfutpasindpl2": "ibimini",
        "Vfutpasindpl3": "ibuntur",
        "Vperpasindsg1": "itus sum",
        "Vperpasindsg2": "itus es",
        "Vperpasindsg3": "itus est",
        "Vperpasindpl1": "iti sumus",
        "Vperpasindpl2": "iti estis",
        "Vperpasindpl3": "iti sunt",
        "Vplppasindsg1": "itus eram",
        "Vplppasindsg2": "itus eras",
        "Vplppasindsg3": "itus erat",
        "Vplppasindpl1": "iti eramus",
        "Vplppasindpl2": "iti eratis",
        "Vplppasindpl3": "iti erant",
        "Vfprpasindsg1": "itus ero",
        "Vfprpasindsg2": "itus eris",
        "Vfprpasindsg3": "itus erit",
        "Vfprpasindpl1": "iti erimus",
        "Vfprpasindpl2": "iti eritis",
        "Vfprpasindpl3": "iti erunt",
        "Vpreactinf   ": "ire",
        "Vprepasinf   ": "iri",
        "Vpreactipesg2": "i",
        "Vpreactipepl2": "ite",
        "Vimpactsbjsg1": "irem",
        "Vimpactsbjsg2": "ires",
        "Vimpactsbjsg3": "iret",
        "Vimpactsbjpl1": "iremus",
        "Vimpactsbjpl2": "iretis",
        "Vimpactsbjpl3": "irent",
        "Vplpactsbjsg1": "issem",
        "Vplpactsbjsg2": "isses",
        "Vplpactsbjsg3": "isset",
        "Vplpactsbjpl1": "issemus",
        "Vplpactsbjpl2": "issetis",
        "Vplpactsbjpl3": "issent",
    },
    "fero": {
        "Vpreactindsg1": "fero",
        "Vpreactindsg2": "fers",
        "Vpreactindsg3": "fert",
        "Vpreactindpl1": "ferimus",
        "Vpreactindpl2": "fertis",
        "Vpreactindpl3": "ferunt",
        "Vimpactindsg1": "ferebam",
        "Vimpactindsg2": "ferebas",
        "Vimpactindsg3": "ferebat",
        "Vimpactindpl1": "ferebamus",
        "Vimpactindpl2": "ferebatis",
        "Vimpactindpl3": "ferebant",
        "Vfutactindsg1": "feram",
        "Vfutactindsg2": "feres",
        "Vfutactindsg3": "feret",
        "Vfutactindpl1": "feremus",
        "Vfutactindpl2": "feretis",
        "Vfutactindpl3": "ferent",
        "Vperactindsg1": "tuli",
        "Vperactindsg2": "tulisti",
        "Vperactindsg3": "tulit",
        "Vperactindpl1": "tulimus",
        "Vperactindpl2": "tulistis",
        "Vperactindpl3": "tulerunt",
        "Vplpactindsg1": "tuleram",
        "Vplpactindsg2": "tuleras",
        "Vplpactindsg3": "tulerat",
        "Vplpactindpl1": "tuleramus",
        "Vplpactindpl2": "tuleratis",
        "Vplpactindpl3": "tulerant",
        "Vfpractindsg1": "tulero",
        "Vfpractindsg2": "tuleris",
        "Vfpractindsg3": "tulerit",
        "Vfpractindpl1": "tulerimus",
        "Vfpractindpl2": "tuleritis",
        "Vfpractindpl3": "tulerint",
        "Vprepasindsg1": "feror",
        "Vprepasindsg2": "ferris",
        "Vprepasindsg3": "fertur",
        "Vprepasindpl1": "ferimur",
        "Vprepasindpl2": "ferimini",
        "Vprepasindpl3": "feruntur",
        "Vimppasindsg1": "ferebar",
        "Vimppasindsg2": "ferebaris",
        "Vimppasindsg3": "ferebatur",
        "Vimppasindpl1": "ferebamur",
        "Vimppasindpl2": "ferebamini",
        "Vimppasindpl3": "ferebantur",
        "Vfutpasindsg1": "ferar",
        "Vfutpasindsg2": "fereris",
        "Vfutpasindsg3": "feretur",
        "Vfutpasindpl1": "feremur",
        "Vfutpasindpl2": "feremini",
        "Vfutpasindpl3": "ferentur",
        "Vperpasindsg1": "latus sum",
        "Vperpasindsg2": "latus es",
        "Vperpasindsg3": "latus est",
        "Vperpasindpl1": "lati sumus",
        "Vperpasindpl2": "lati estis",
        "Vperpasindpl3": "lati sunt",
        "Vplppasindsg1": "latus eram",
        "Vplppasindsg2": "latus eras",
        "Vplppasindsg3": "latus erat",
        "Vplppasindpl1": "lati eramus",
        "Vplppasindpl2": "lati eratis",
        "Vplppasindpl3": "lati erant",
        "Vfprpasindsg1": "latus ero",
        "Vfprpasindsg2": "latus eris",
        "Vfprpasindsg3": "latus erit",
        "Vfprpasindpl1": "lati erimus",
        "Vfprpasindpl2": "lati eritis",
        "Vfprpasindpl3": "lati erunt",
        "Vpreactinf   ": "ferre",
        "Vprepasinf   ": "ferri",
        "Vpreactipesg2": "fer",
        "Vpreactipepl2": "ferte",
        "Vimpactsbjsg1": "ferrem",
        "Vimpactsbjsg2": "ferres",
        "Vimpactsbjsg3": "ferret",
        "Vimpactsbjpl1": "ferremus",
        "Vimpactsbjpl2": "ferretis",
        "Vimpactsbjpl3": "ferrent",
        "Vplpactsbjsg1": "tulissem",
        "Vplpactsbjsg2": "tulisses",
        "Vplpactsbjsg3": "tulisset",
        "Vplpactsbjpl1": "tulissemus",
        "Vplpactsbjpl2": "tulissetis",
        "Vplpactsbjpl3": "tulissent",
    },
}


def find_irregular_endings(present: str) -> Endings | None:
    """Detect if a verb is irregular and return its endings.

    Parameters
    ----------
    present : str
        The present form verb to check.

    Returns
    -------
    Endings | None
        The endings. ``None`` if the verb is not irregular.
    """

    def _prefix(
        pre: str, endings: Endings
    ) -> dict[str, str | MultipleEndings]:
        return {key: pre + value for key, value in endings.items()}

    if present in IRREGULAR_VERBS:
        return IRREGULAR_VERBS[present]

    for irregular_suffix, suffix_list in DERIVED_IRREGULAR_VERBS.items():
        if present in suffix_list:
            return _prefix(
                # FIXME: Fix this - use `removesuffix` instead
                present.rstrip(irregular_suffix),
                DERIVED_IRREGULAR_ENDINGS[irregular_suffix],
            )

    return None


# -----------------------------------------------------------------------------
# NOUNS

IRREGULAR_NOUNS: Final[dict[str, Endings]] = {
    "ego": {
        "Nnomsg": "ego",
        "Nvocsg": "ego",
        "Naccsg": "me",
        "Ngensg": "mei",
        "Ndatsg": "mihi",
        "Nablsg": "me",
        "Nnompl": "nos",
        "Nvocpl": "nos",
        "Naccpl": "nos",
        "Ngenpl": MultipleEndings(regular="nostri", partitive="nostrum"),
        "Ndatpl": "nobis",
        "Nablpl": "nobis",
    },
    "tu": {
        "Nnomsg": "tu",
        "Nvocsg": "tu",
        "Naccsg": "te",
        "Ngensg": "tui",
        "Ndatsg": "tibi",
        "Nablsg": "te",
        "Nnompl": "vos",
        "Nvocpl": "vos",
        "Naccpl": "vos",
        "Ngenpl": MultipleEndings(regular="vestri", partitive="vestrum"),
        "Ndatpl": "vobis",
        "Nablpl": "vobis",
    },
    "se": {
        "Naccsg": "se",
        "Ngensg": "sui",
        "Ndatsg": "sibi",
        "Nablsg": "se",
        "Naccpl": "se",
        "Ngenpl": "sui",
        "Ndatpl": "sibi",
        "Nablpl": "se",
    },
}

# -----------------------------------------------------------------------------
# ADJECTIVES

LIS_ADJECTIVES: Final[set[str]] = {
    "facilis",
    "difficilis",
    "similis",
    "dissimilis",
    "gracilis",
    "humilis",
}

# Contains adjectives that have irregular forms in the comparative,
# superlative and adverb forms.
# Note that some of these adjectives do not have adverb forms, so the adverb
# forms are given a None value instead.
IRREGULAR_ADJECTIVES: Final[
    dict[str, tuple[str, str, str | None, str | None, str | None]]
] = {
    "bonus": ("melior", "optim", "bene", "melius", "optime"),
    "malus": ("peior", "pessim", "male", "peius", "pessime"),
    "magnus": ("maior", "maxim", None, None, None),
    "parvus": ("minor", "minim", None, None, None),
    # multo (adverb) exists but that would very much stuff up things
    "multus": ("plus", "plurim", None, None, None),
    # nequam should probably just be put in as a regular
    "nequam": ("nequior", "nequissim", None, None, None),
    "frugi": (
        "frugalior",
        "frugalissim",
        "frugaliter",
        "frugalius",
        "frugalissime",
    ),
    "dexter": ("dexterior", "dextim", None, None, None),
}

# TODO: Add to this
NO_ADVERB_ADJECTIVES = {"ingens"}

# -----------------------------------------------------------------------------
# PRONOUNS

PRONOUNS: Final[dict[str, Endings]] = {
    "hic": {
        "Pmnomsg": "hic",
        "Pmaccsg": "hunc",
        "Pmgensg": "huius",
        "Pmdatsg": "huic",
        "Pmablsg": "hoc",
        "Pmnompl": "hi",
        "Pmaccpl": "hos",
        "Pmgenpl": "horum",
        "Pmdatpl": "his",
        "Pmablpl": "his",
        "Pfnomsg": "haec",
        "Pfaccsg": "hanc",
        "Pfgensg": "huius",
        "Pfdatsg": "huic",
        "Pfablsg": "hac",
        "Pfnompl": "hae",
        "Pfaccpl": "has",
        "Pfgenpl": "harum",
        "Pfdatpl": "his",
        "Pfablpl": "his",
        "Pnnomsg": "hoc",
        "Pnaccsg": "hoc",
        "Pngensg": "huius",
        "Pndatsg": "huic",
        "Pnablsg": "hoc",
        "Pnnompl": "haec",
        "Pnaccpl": "haec",
        "Pngenpl": "horum",
        "Pndatpl": "his",
        "Pnablpl": "his",
    },
    "ille": {
        "Pmnomsg": "ille",
        "Pmaccsg": "illum",
        "Pmgensg": "illius",
        "Pmdatsg": "illi",
        "Pmablsg": "illo",
        "Pmnompl": "illi",
        "Pmaccpl": "illos",
        "Pmgenpl": "illorum",
        "Pmdatpl": "illis",
        "Pmablpl": "illis",
        "Pfnomsg": "illa",
        "Pfaccsg": "illam",
        "Pfgensg": "illius",
        "Pfdatsg": "illi",
        "Pfablsg": "illa",
        "Pfnompl": "illae",
        "Pfaccpl": "illas",
        "Pfgenpl": "illarum",
        "Pfdatpl": "illis",
        "Pfablpl": "illis",
        "Pnnomsg": "illud",
        "Pnaccsg": "illud",
        "Pngensg": "illius",
        "Pndatsg": "illi",
        "Pnablsg": "illo",
        "Pnnompl": "illa",
        "Pnaccpl": "illa",
        "Pngenpl": "illorum",
        "Pndatpl": "illis",
        "Pnablpl": "illis",
    },
    "is": {
        "Pmnomsg": "is",
        "Pmaccsg": "eum",
        "Pmgensg": "eius",
        "Pmdatsg": "ei",
        "Pmablsg": "eo",
        "Pmnompl": "ei",
        "Pmaccpl": "eos",
        "Pmgenpl": "eorum",
        "Pmdatpl": "eis",
        "Pmablpl": "eis",
        "Pfnomsg": "ea",
        "Pfaccsg": "eam",
        "Pfgensg": "eius",
        "Pfdatsg": "ei",
        "Pfablsg": "ea",
        "Pfnompl": "eae",
        "Pfaccpl": "eas",
        "Pfgenpl": "earum",
        "Pfdatpl": "eis",
        "Pfablpl": "eis",
        "Pnnomsg": "id",
        "Pnaccsg": "id",
        "Pngensg": "eius",
        "Pndatsg": "ei",
        "Pnablsg": "eo",
        "Pnnompl": "ea",
        "Pnaccpl": "ea",
        "Pngenpl": "eorum",
        "Pndatpl": "eis",
        "Pnablpl": "eis",
    },
    "ipse": {
        "Pmnomsg": "ipse",
        "Pmaccsg": "ipsum",
        "Pmgensg": "ipsius",
        "Pmdatsg": "ipsi",
        "Pmablsg": "ipso",
        "Pmnompl": "ipsi",
        "Pmaccpl": "ipsos",
        "Pmgenpl": "ipsorum",
        "Pmdatpl": "ipsis",
        "Pmablpl": "ipsis",
        "Pfnomsg": "ipsa",
        "Pfaccsg": "ipsam",
        "Pfgensg": "ipsius",
        "Pfdatsg": "ipsi",
        "Pfablsg": "ipsa",
        "Pfnompl": "ipsae",
        "Pfaccpl": "ipsas",
        "Pfgenpl": "ipsarum",
        "Pfdatpl": "ipsis",
        "Pfablpl": "ipsis",
        "Pnnomsg": "ipsum",
        "Pnaccsg": "ipsum",
        "Pngensg": "ipsius",
        "Pndatsg": "ipsi",
        "Pnablsg": "ipso",
        "Pnnompl": "ipsa",
        "Pnaccpl": "ipsa",
        "Pngenpl": "ipsorum",
        "Pndatpl": "ipsis",
        "Pnablpl": "ipsis",
    },
    "idem": {
        "Pmnomsg": "idem",
        "Pmaccsg": "eundem",
        "Pmgensg": "eiusdem",
        "Pmdatsg": "eidem",
        "Pmablsg": "eodem",
        "Pmnompl": "eidem",
        "Pmaccpl": "eosdem",
        "Pmgenpl": "eorundem",
        "Pmdatpl": "eisdem",
        "Pmablpl": "eisdem",
        "Pfnomsg": "eadem",
        "Pfaccsg": "eandem",
        "Pfgensg": "eiusdem",
        "Pfdatsg": "eidem",
        "Pfablsg": "eadem",
        "Pfnompl": "eaedem",
        "Pfaccpl": "easdem",
        "Pfgenpl": "earundem",
        "Pfdatpl": "eisdem",
        "Pfablpl": "eisdem",
        "Pnnomsg": "idem",
        "Pnaccsg": "idem",
        "Pngensg": "eiusdem",
        "Pndatsg": "eidem",
        "Pnablsg": "eodem",
        "Pnnompl": "eadem",
        "Pnaccpl": "eadem",
        "Pngenpl": "eorundem",
        "Pndatpl": "eisdem",
        "Pnablpl": "eisdem",
    },
    "qui": {
        "Pmnomsg": "qui",
        "Pmaccsg": "quem",
        "Pmgensg": "cuius",
        "Pmdatsg": "cui",
        "Pmablsg": "quo",
        "Pmnompl": "qui",
        "Pmaccpl": "quos",
        "Pmgenpl": "quorum",
        "Pmdatpl": "quibus",
        "Pmablpl": "quibus",
        "Pfnomsg": "quae",
        "Pfaccsg": "quam",
        "Pfgensg": "cuius",
        "Pfdatsg": "cui",
        "Pfablsg": "qua",
        "Pfnompl": "quae",
        "Pfaccpl": "quas",
        "Pfgenpl": "quarum",
        "Pfdatpl": "quibus",
        "Pfablpl": "quibus",
        "Pnnomsg": "quod",
        "Pnaccsg": "quod",
        "Pngensg": "cuius",
        "Pndatsg": "cui",
        "Pnablsg": "quo",
        "Pnnompl": "quae",
        "Pnaccpl": "quae",
        "Pngenpl": "quorum",
        "Pndatpl": "quibus",
        "Pnablpl": "quibus",
    },
    "quidam": {
        "Pmnomsg": "quidam",
        "Pmaccsg": "quendam",
        "Pmgensg": "cuiusdam",
        "Pmdatsg": "cuidam",
        "Pmablsg": "quodam",
        "Pmnompl": "quidam",
        "Pmaccpl": "quosdam",
        "Pmgenpl": "quorundam",
        "Pmdatpl": "quibusdam",
        "Pmablpl": "quibusdam",
        "Pfnomsg": "quaedam",
        "Pfaccsg": "quandam",
        "Pfgensg": "cuiusdam",
        "Pfdatsg": "cuidam",
        "Pfablsg": "quadam",
        "Pfnompl": "quaedam",
        "Pfaccpl": "quasdam",
        "Pfgenpl": "quarundam",
        "Pfdatpl": "quibusdam",
        "Pfablpl": "quibusdam",
        "Pnnomsg": "quoddam",
        "Pnaccsg": "quoddam",
        "Pngensg": "cuiusdam",
        "Pndatsg": "cuidam",
        "Pnablsg": "quodam",
        "Pnnompl": "quaedam",
        "Pnaccpl": "quaedam",
        "Pngenpl": "quorundam",
        "Pndatpl": "quibusdam",
        "Pnablpl": "quibusdam",
    },
}
