name: build-python
on: push

jobs:
  build-linux-x86_64:
    name: Build for Linux on x86_64
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python:
          - 3.13.0

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Install python
        uses: gabrielfalcao/pyenv-action@main
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip # upgrade pip after installing python

      - name: Install deps
        run: |
          python3.13 -m pip install pipx
          pipx install poetry poethepoet
          pipx inject poetry "poetry-dynamic-versioning[plugin]"

      - name: Setup project
        run: |
          pwd
          python3.13 -m venv .venv
          source .venv/bin/activate

      - name: Build project
        run: poe build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: linux-x86_64-artifact
