name: build-python
on: workflow_dispatch

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-20.04,
            ubuntu-22.04-arm, # ubuntu-20.04-arm not supported?
            windows-2019,
            macos-13,
            # macos-13-xlarge,
          ]
        python:
          - 3.13.1

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13.1"

      - name: Install deps
        run: |
          python3 -m pip install pipx
          pipx install poetry poethepoet
          pipx inject poetry "poetry-dynamic-versioning[plugin]"

      - name: Setup project
        run: |
          python3 -m venv .venv

      - name: Build project
        if: ${{ matrix.os != 'macos-13' }}
        run: |
          source .venv/bin/activate
          poe build

      # - name: Build project
      #   if: ${{ matrix.os == 'macos-13-xlarge' }}
      #   run: |
      #     source .venv/bin/activate
      #     poe build --target-arch arm64

      - name: Build project
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          source .venv/bin/activate
          poe build --target-arch x86_64

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            dist/*
