name: build
on: workflow_dispatch

permissions:
  actions: write

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-22.04-arm,
            macos-14,
            windows-2022,
            windows-11-arm,
          ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Verify .python-version file
        run: |
          if [ ! -s .python-version ]; then echo ".python-version is missing or empty" >&2; exit 1; else echo "Found .python-version:"; cat .python-version; fi

      - name: Verify go.mod file
        run: |
          if [ ! -s go.mod ]; then echo "go.mod is missing or empty" >&2; exit 1; else echo "Found go.mod:"; grep '^go ' go.mod; fi

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install deps
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          python -m pip install --user pipx
          pipx ensurepath
          pipx install poetry poethepoet
          pipx inject poetry "poetry-dynamic-versioning[plugin]"

      - name: Install deps
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
          & "$env:APPDATA\pypoetry\venv\Scripts\poetry" self add "poetry-dynamic-versioning[plugin]"
          echo "$env:APPDATA\pypoetry\venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Setup project
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          poetry config virtualenvs.in-project true
          go install ./src/_vendor/mkunion/cmd/mkunion
          go install ./src/_vendor/go-jsonstruct/cmd/gojsonstruct
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Setup project
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          python --version
          poetry config virtualenvs.in-project true
          poetry env use "C:\hostedtoolcache\windows\Python\3.13.5\x64\python.exe"
          go install ./src/_vendor/mkunion/cmd/mkunion
          go install ./src/_vendor/go-jsonstruct/cmd/gojsonstruct
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Setup project
        if: ${{ matrix.os == 'windows-11-arm'}}
        run: |
          poetry config virtualenvs.in-project true
          poetry env use "C:\hostedtoolcache\windows\Python\3.13.5\arm64\python.exe"
          go install ./src/_vendor/mkunion/cmd/mkunion
          go install ./src/_vendor/go-jsonstruct/cmd/gojsonstruct
          echo PATH=$PATH >> $GITHUB_ENV

      # HACK: Have to workaround using poe as there are weird errors for some reason
      - name: Build project
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          scripts/build-gh.ps1
        shell: pwsh

      - name: Build project
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          poe build

      - name: Build project
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          poe build --target-arch universal2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-${{ matrix.os }}
          path: dist/*
